app:
  name: 'usercontrol'
  version: '1.0.0'

swagger:
  host: '127.0.0.1'
  
http:
  host: '127.0.0.1'
  port: '8002'

logger:
  log_level: 'debug'
  rollbar_env: 'usercontrol'

blog_cl:
  proto: "http"
  host: "127.0.0.1"
  port: "8004"

keycloak:
  proto: "https"
  host: "192.168.130.112"
  port: "8443"
  login: "system_admin"
  password: "admin"
  system_realm: "master"
  realm: "grafanasso"
  grafana_client_id: "grafana-sso"
  grafana_client_secret: "uAgEvDTaFYvzqr287p2qZFIi7habElf8"
  grafana_client_uuid: "29a7ef53-ad36-44f3-93be-a70270f439a2"

grafana:
  proto: "https"
  host: "192.168.130.112"
  port: "3000"
  auth_path: "/login/generic_oauth"
  username: "system_admin"
  pass: "admin"