// Code generated by go-swagger; DO NOT EDIT.

package not_implemented

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"api-gateway/pkg/models"
)

// GetAPIV1DashboardsResourcesReader is a Reader for the GetAPIV1DashboardsResources structure.
type GetAPIV1DashboardsResourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1DashboardsResourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1DashboardsResourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV1DashboardsResourcesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1DashboardsResourcesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/dashboards/resources] GetAPIV1DashboardsResources", response, response.Code())
	}
}

// NewGetAPIV1DashboardsResourcesOK creates a GetAPIV1DashboardsResourcesOK with default headers values
func NewGetAPIV1DashboardsResourcesOK() *GetAPIV1DashboardsResourcesOK {
	return &GetAPIV1DashboardsResourcesOK{}
}

/*
GetAPIV1DashboardsResourcesOK describes a response with status code 200, with default header values.

JSON объект, где ключ - URL ресурса, значение - количество обращений
*/
type GetAPIV1DashboardsResourcesOK struct {
	Payload map[string]int64
}

// IsSuccess returns true when this get Api v1 dashboards resources o k response has a 2xx status code
func (o *GetAPIV1DashboardsResourcesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 dashboards resources o k response has a 3xx status code
func (o *GetAPIV1DashboardsResourcesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 dashboards resources o k response has a 4xx status code
func (o *GetAPIV1DashboardsResourcesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 dashboards resources o k response has a 5xx status code
func (o *GetAPIV1DashboardsResourcesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 dashboards resources o k response a status code equal to that given
func (o *GetAPIV1DashboardsResourcesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 dashboards resources o k response
func (o *GetAPIV1DashboardsResourcesOK) Code() int {
	return 200
}

func (o *GetAPIV1DashboardsResourcesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/dashboards/resources][%d] getApiV1DashboardsResourcesOK %s", 200, payload)
}

func (o *GetAPIV1DashboardsResourcesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/dashboards/resources][%d] getApiV1DashboardsResourcesOK %s", 200, payload)
}

func (o *GetAPIV1DashboardsResourcesOK) GetPayload() map[string]int64 {
	return o.Payload
}

func (o *GetAPIV1DashboardsResourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1DashboardsResourcesBadRequest creates a GetAPIV1DashboardsResourcesBadRequest with default headers values
func NewGetAPIV1DashboardsResourcesBadRequest() *GetAPIV1DashboardsResourcesBadRequest {
	return &GetAPIV1DashboardsResourcesBadRequest{}
}

/*
GetAPIV1DashboardsResourcesBadRequest describes a response with status code 400, with default header values.

Неверный формат параметров
*/
type GetAPIV1DashboardsResourcesBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get Api v1 dashboards resources bad request response has a 2xx status code
func (o *GetAPIV1DashboardsResourcesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 dashboards resources bad request response has a 3xx status code
func (o *GetAPIV1DashboardsResourcesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 dashboards resources bad request response has a 4xx status code
func (o *GetAPIV1DashboardsResourcesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 dashboards resources bad request response has a 5xx status code
func (o *GetAPIV1DashboardsResourcesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 dashboards resources bad request response a status code equal to that given
func (o *GetAPIV1DashboardsResourcesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v1 dashboards resources bad request response
func (o *GetAPIV1DashboardsResourcesBadRequest) Code() int {
	return 400
}

func (o *GetAPIV1DashboardsResourcesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/dashboards/resources][%d] getApiV1DashboardsResourcesBadRequest %s", 400, payload)
}

func (o *GetAPIV1DashboardsResourcesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/dashboards/resources][%d] getApiV1DashboardsResourcesBadRequest %s", 400, payload)
}

func (o *GetAPIV1DashboardsResourcesBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetAPIV1DashboardsResourcesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1DashboardsResourcesInternalServerError creates a GetAPIV1DashboardsResourcesInternalServerError with default headers values
func NewGetAPIV1DashboardsResourcesInternalServerError() *GetAPIV1DashboardsResourcesInternalServerError {
	return &GetAPIV1DashboardsResourcesInternalServerError{}
}

/*
GetAPIV1DashboardsResourcesInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера
*/
type GetAPIV1DashboardsResourcesInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get Api v1 dashboards resources internal server error response has a 2xx status code
func (o *GetAPIV1DashboardsResourcesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 dashboards resources internal server error response has a 3xx status code
func (o *GetAPIV1DashboardsResourcesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 dashboards resources internal server error response has a 4xx status code
func (o *GetAPIV1DashboardsResourcesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 dashboards resources internal server error response has a 5xx status code
func (o *GetAPIV1DashboardsResourcesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 dashboards resources internal server error response a status code equal to that given
func (o *GetAPIV1DashboardsResourcesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 dashboards resources internal server error response
func (o *GetAPIV1DashboardsResourcesInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1DashboardsResourcesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/dashboards/resources][%d] getApiV1DashboardsResourcesInternalServerError %s", 500, payload)
}

func (o *GetAPIV1DashboardsResourcesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/dashboards/resources][%d] getApiV1DashboardsResourcesInternalServerError %s", 500, payload)
}

func (o *GetAPIV1DashboardsResourcesInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetAPIV1DashboardsResourcesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
