// Code generated by go-swagger; DO NOT EDIT.

package not_implemented

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV1DashboardsDevicesParams creates a new GetAPIV1DashboardsDevicesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1DashboardsDevicesParams() *GetAPIV1DashboardsDevicesParams {
	return &GetAPIV1DashboardsDevicesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1DashboardsDevicesParamsWithTimeout creates a new GetAPIV1DashboardsDevicesParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1DashboardsDevicesParamsWithTimeout(timeout time.Duration) *GetAPIV1DashboardsDevicesParams {
	return &GetAPIV1DashboardsDevicesParams{
		timeout: timeout,
	}
}

// NewGetAPIV1DashboardsDevicesParamsWithContext creates a new GetAPIV1DashboardsDevicesParams object
// with the ability to set a context for a request.
func NewGetAPIV1DashboardsDevicesParamsWithContext(ctx context.Context) *GetAPIV1DashboardsDevicesParams {
	return &GetAPIV1DashboardsDevicesParams{
		Context: ctx,
	}
}

// NewGetAPIV1DashboardsDevicesParamsWithHTTPClient creates a new GetAPIV1DashboardsDevicesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1DashboardsDevicesParamsWithHTTPClient(client *http.Client) *GetAPIV1DashboardsDevicesParams {
	return &GetAPIV1DashboardsDevicesParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1DashboardsDevicesParams contains all the parameters to send to the API endpoint

	for the get API v1 dashboards devices operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1DashboardsDevicesParams struct {

	/* End.

	   Конец периода в timestamp

	   Format: int64
	*/
	End int64

	/* Start.

	   Начало периода в timestamp

	   Format: int64
	*/
	Start int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 dashboards devices params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1DashboardsDevicesParams) WithDefaults() *GetAPIV1DashboardsDevicesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 dashboards devices params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1DashboardsDevicesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 dashboards devices params
func (o *GetAPIV1DashboardsDevicesParams) WithTimeout(timeout time.Duration) *GetAPIV1DashboardsDevicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 dashboards devices params
func (o *GetAPIV1DashboardsDevicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 dashboards devices params
func (o *GetAPIV1DashboardsDevicesParams) WithContext(ctx context.Context) *GetAPIV1DashboardsDevicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 dashboards devices params
func (o *GetAPIV1DashboardsDevicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 dashboards devices params
func (o *GetAPIV1DashboardsDevicesParams) WithHTTPClient(client *http.Client) *GetAPIV1DashboardsDevicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 dashboards devices params
func (o *GetAPIV1DashboardsDevicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnd adds the end to the get API v1 dashboards devices params
func (o *GetAPIV1DashboardsDevicesParams) WithEnd(end int64) *GetAPIV1DashboardsDevicesParams {
	o.SetEnd(end)
	return o
}

// SetEnd adds the end to the get API v1 dashboards devices params
func (o *GetAPIV1DashboardsDevicesParams) SetEnd(end int64) {
	o.End = end
}

// WithStart adds the start to the get API v1 dashboards devices params
func (o *GetAPIV1DashboardsDevicesParams) WithStart(start int64) *GetAPIV1DashboardsDevicesParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the get API v1 dashboards devices params
func (o *GetAPIV1DashboardsDevicesParams) SetStart(start int64) {
	o.Start = start
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1DashboardsDevicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param end
	qrEnd := o.End
	qEnd := swag.FormatInt64(qrEnd)
	if qEnd != "" {

		if err := r.SetQueryParam("end", qEnd); err != nil {
			return err
		}
	}

	// query param start
	qrStart := o.Start
	qStart := swag.FormatInt64(qrStart)
	if qStart != "" {

		if err := r.SetQueryParam("start", qStart); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
