// Code generated by go-swagger; DO NOT EDIT.

package not_implemented

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"api-gateway/pkg/models"
)

// GetV1DashboardsProhActivityReader is a Reader for the GetV1DashboardsProhActivity structure.
type GetV1DashboardsProhActivityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1DashboardsProhActivityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1DashboardsProhActivityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetV1DashboardsProhActivityBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetV1DashboardsProhActivityInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/dashboards/proh_activity] GetV1DashboardsProhActivity", response, response.Code())
	}
}

// NewGetV1DashboardsProhActivityOK creates a GetV1DashboardsProhActivityOK with default headers values
func NewGetV1DashboardsProhActivityOK() *GetV1DashboardsProhActivityOK {
	return &GetV1DashboardsProhActivityOK{}
}

/*
GetV1DashboardsProhActivityOK describes a response with status code 200, with default header values.

График запрещенной активности
*/
type GetV1DashboardsProhActivityOK struct {
	Payload map[string]int64
}

// IsSuccess returns true when this get v1 dashboards proh activity o k response has a 2xx status code
func (o *GetV1DashboardsProhActivityOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 dashboards proh activity o k response has a 3xx status code
func (o *GetV1DashboardsProhActivityOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 dashboards proh activity o k response has a 4xx status code
func (o *GetV1DashboardsProhActivityOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 dashboards proh activity o k response has a 5xx status code
func (o *GetV1DashboardsProhActivityOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 dashboards proh activity o k response a status code equal to that given
func (o *GetV1DashboardsProhActivityOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 dashboards proh activity o k response
func (o *GetV1DashboardsProhActivityOK) Code() int {
	return 200
}

func (o *GetV1DashboardsProhActivityOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/dashboards/proh_activity][%d] getV1DashboardsProhActivityOK %s", 200, payload)
}

func (o *GetV1DashboardsProhActivityOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/dashboards/proh_activity][%d] getV1DashboardsProhActivityOK %s", 200, payload)
}

func (o *GetV1DashboardsProhActivityOK) GetPayload() map[string]int64 {
	return o.Payload
}

func (o *GetV1DashboardsProhActivityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1DashboardsProhActivityBadRequest creates a GetV1DashboardsProhActivityBadRequest with default headers values
func NewGetV1DashboardsProhActivityBadRequest() *GetV1DashboardsProhActivityBadRequest {
	return &GetV1DashboardsProhActivityBadRequest{}
}

/*
GetV1DashboardsProhActivityBadRequest describes a response with status code 400, with default header values.

Неверный формат параметров
*/
type GetV1DashboardsProhActivityBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 dashboards proh activity bad request response has a 2xx status code
func (o *GetV1DashboardsProhActivityBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 dashboards proh activity bad request response has a 3xx status code
func (o *GetV1DashboardsProhActivityBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 dashboards proh activity bad request response has a 4xx status code
func (o *GetV1DashboardsProhActivityBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 dashboards proh activity bad request response has a 5xx status code
func (o *GetV1DashboardsProhActivityBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 dashboards proh activity bad request response a status code equal to that given
func (o *GetV1DashboardsProhActivityBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get v1 dashboards proh activity bad request response
func (o *GetV1DashboardsProhActivityBadRequest) Code() int {
	return 400
}

func (o *GetV1DashboardsProhActivityBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/dashboards/proh_activity][%d] getV1DashboardsProhActivityBadRequest %s", 400, payload)
}

func (o *GetV1DashboardsProhActivityBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/dashboards/proh_activity][%d] getV1DashboardsProhActivityBadRequest %s", 400, payload)
}

func (o *GetV1DashboardsProhActivityBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1DashboardsProhActivityBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1DashboardsProhActivityInternalServerError creates a GetV1DashboardsProhActivityInternalServerError with default headers values
func NewGetV1DashboardsProhActivityInternalServerError() *GetV1DashboardsProhActivityInternalServerError {
	return &GetV1DashboardsProhActivityInternalServerError{}
}

/*
GetV1DashboardsProhActivityInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера
*/
type GetV1DashboardsProhActivityInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 dashboards proh activity internal server error response has a 2xx status code
func (o *GetV1DashboardsProhActivityInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 dashboards proh activity internal server error response has a 3xx status code
func (o *GetV1DashboardsProhActivityInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 dashboards proh activity internal server error response has a 4xx status code
func (o *GetV1DashboardsProhActivityInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 dashboards proh activity internal server error response has a 5xx status code
func (o *GetV1DashboardsProhActivityInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get v1 dashboards proh activity internal server error response a status code equal to that given
func (o *GetV1DashboardsProhActivityInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get v1 dashboards proh activity internal server error response
func (o *GetV1DashboardsProhActivityInternalServerError) Code() int {
	return 500
}

func (o *GetV1DashboardsProhActivityInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/dashboards/proh_activity][%d] getV1DashboardsProhActivityInternalServerError %s", 500, payload)
}

func (o *GetV1DashboardsProhActivityInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/dashboards/proh_activity][%d] getV1DashboardsProhActivityInternalServerError %s", 500, payload)
}

func (o *GetV1DashboardsProhActivityInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1DashboardsProhActivityInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
