app:
  name: 'tg-etl'
  version: '1.0.1'
  dev_version: '0.1.1-dev.5'

http:
  host: '127.0.0.1'
  port: '7001'

swagger:
  host: '127.0.0.1'
  
logger:
  log_level: 'debug'

ksu_postgres:
  pool_max: 2
  host: "192.168.130.112"
  user: "ksu_user"
  pass: "ksu_password"
  dbname: "ksu"
  port: "5432"
  sslmode: "disable"

etl_postgres:
  #pool_max: 2
  #host: "localhost"
  #user: "etl"
  #pass: "etlpassword"
  #dbname: "etl"
  #port: "5432"
  #sslmode: "disable"
  pool_max: 2
  host: "192.168.130.112"
  user: "etl_user"
  pass: "etl_password"
  dbname: "etl"
  port: "5433"
  sslmode: "disable"


etl_controller:
  refresh: 10
  ttl: 10
  max_count: 100