// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"tg-an/pkg/models"
)

// NewPostAPIV1AddParams creates a new PostAPIV1AddParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1AddParams() *PostAPIV1AddParams {
	return &PostAPIV1AddParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1AddParamsWithTimeout creates a new PostAPIV1AddParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1AddParamsWithTimeout(timeout time.Duration) *PostAPIV1AddParams {
	return &PostAPIV1AddParams{
		timeout: timeout,
	}
}

// NewPostAPIV1AddParamsWithContext creates a new PostAPIV1AddParams object
// with the ability to set a context for a request.
func NewPostAPIV1AddParamsWithContext(ctx context.Context) *PostAPIV1AddParams {
	return &PostAPIV1AddParams{
		Context: ctx,
	}
}

// NewPostAPIV1AddParamsWithHTTPClient creates a new PostAPIV1AddParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1AddParamsWithHTTPClient(client *http.Client) *PostAPIV1AddParams {
	return &PostAPIV1AddParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1AddParams contains all the parameters to send to the API endpoint

	for the post API v1 add operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1AddParams struct {

	/* Record.

	   Структура записи бизнес лога
	*/
	Record *models.DtoBusinessLog

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 add params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AddParams) WithDefaults() *PostAPIV1AddParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 add params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AddParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 add params
func (o *PostAPIV1AddParams) WithTimeout(timeout time.Duration) *PostAPIV1AddParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 add params
func (o *PostAPIV1AddParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 add params
func (o *PostAPIV1AddParams) WithContext(ctx context.Context) *PostAPIV1AddParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 add params
func (o *PostAPIV1AddParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 add params
func (o *PostAPIV1AddParams) WithHTTPClient(client *http.Client) *PostAPIV1AddParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 add params
func (o *PostAPIV1AddParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRecord adds the record to the post API v1 add params
func (o *PostAPIV1AddParams) WithRecord(record *models.DtoBusinessLog) *PostAPIV1AddParams {
	o.SetRecord(record)
	return o
}

// SetRecord adds the record to the post API v1 add params
func (o *PostAPIV1AddParams) SetRecord(record *models.DtoBusinessLog) {
	o.Record = record
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1AddParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Record != nil {
		if err := r.SetBodyParam(o.Record); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
