// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"userctrl/pkg/blog/models"
)

// NewPostAPIV1AddParams creates a new PostAPIV1AddParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1AddParams() *PostAPIV1AddParams {
	return &PostAPIV1AddParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1AddParamsWithTimeout creates a new PostAPIV1AddParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1AddParamsWithTimeout(timeout time.Duration) *PostAPIV1AddParams {
	return &PostAPIV1AddParams{
		timeout: timeout,
	}
}

// NewPostAPIV1AddParamsWithContext creates a new PostAPIV1AddParams object
// with the ability to set a context for a request.
func NewPostAPIV1AddParamsWithContext(ctx context.Context) *PostAPIV1AddParams {
	return &PostAPIV1AddParams{
		Context: ctx,
	}
}

// NewPostAPIV1AddParamsWithHTTPClient creates a new PostAPIV1AddParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1AddParamsWithHTTPClient(client *http.Client) *PostAPIV1AddParams {
	return &PostAPIV1AddParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1AddParams contains all the parameters to send to the API endpoint

	for the post API v1 add operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1AddParams struct {

	/* XCallerService.

	   Имя вызывающего микросервиса

	   Default: "user-service"
	*/
	XCallerService string

	/* XRequestID.

	   Уникальный ID (UUID) запроса

	   Default: "req-abc123-def456"
	*/
	XRequestID string

	/* Record.

	   Структура записи бизнес лога
	*/
	Record *models.DtoBusinessLog

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 add params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AddParams) WithDefaults() *PostAPIV1AddParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 add params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AddParams) SetDefaults() {
	var (
		xCallerServiceDefault = string("user-service")

		xRequestIDDefault = string("req-abc123-def456")
	)

	val := PostAPIV1AddParams{
		XCallerService: xCallerServiceDefault,
		XRequestID:     xRequestIDDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the post API v1 add params
func (o *PostAPIV1AddParams) WithTimeout(timeout time.Duration) *PostAPIV1AddParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 add params
func (o *PostAPIV1AddParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 add params
func (o *PostAPIV1AddParams) WithContext(ctx context.Context) *PostAPIV1AddParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 add params
func (o *PostAPIV1AddParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 add params
func (o *PostAPIV1AddParams) WithHTTPClient(client *http.Client) *PostAPIV1AddParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 add params
func (o *PostAPIV1AddParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCallerService adds the xCallerService to the post API v1 add params
func (o *PostAPIV1AddParams) WithXCallerService(xCallerService string) *PostAPIV1AddParams {
	o.SetXCallerService(xCallerService)
	return o
}

// SetXCallerService adds the xCallerService to the post API v1 add params
func (o *PostAPIV1AddParams) SetXCallerService(xCallerService string) {
	o.XCallerService = xCallerService
}

// WithXRequestID adds the xRequestID to the post API v1 add params
func (o *PostAPIV1AddParams) WithXRequestID(xRequestID string) *PostAPIV1AddParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the post API v1 add params
func (o *PostAPIV1AddParams) SetXRequestID(xRequestID string) {
	o.XRequestID = xRequestID
}

// WithRecord adds the record to the post API v1 add params
func (o *PostAPIV1AddParams) WithRecord(record *models.DtoBusinessLog) *PostAPIV1AddParams {
	o.SetRecord(record)
	return o
}

// SetRecord adds the record to the post API v1 add params
func (o *PostAPIV1AddParams) SetRecord(record *models.DtoBusinessLog) {
	o.Record = record
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1AddParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Caller-Service
	if err := r.SetHeaderParam("X-Caller-Service", o.XCallerService); err != nil {
		return err
	}

	// header param X-Request-ID
	if err := r.SetHeaderParam("X-Request-ID", o.XRequestID); err != nil {
		return err
	}
	if o.Record != nil {
		if err := r.SetBodyParam(o.Record); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
