// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"tg-etl/pkg/models"
)

// NewPostV1AuthSignInParams creates a new PostV1AuthSignInParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1AuthSignInParams() *PostV1AuthSignInParams {
	return &PostV1AuthSignInParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1AuthSignInParamsWithTimeout creates a new PostV1AuthSignInParams object
// with the ability to set a timeout on a request.
func NewPostV1AuthSignInParamsWithTimeout(timeout time.Duration) *PostV1AuthSignInParams {
	return &PostV1AuthSignInParams{
		timeout: timeout,
	}
}

// NewPostV1AuthSignInParamsWithContext creates a new PostV1AuthSignInParams object
// with the ability to set a context for a request.
func NewPostV1AuthSignInParamsWithContext(ctx context.Context) *PostV1AuthSignInParams {
	return &PostV1AuthSignInParams{
		Context: ctx,
	}
}

// NewPostV1AuthSignInParamsWithHTTPClient creates a new PostV1AuthSignInParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1AuthSignInParamsWithHTTPClient(client *http.Client) *PostV1AuthSignInParams {
	return &PostV1AuthSignInParams{
		HTTPClient: client,
	}
}

/*
PostV1AuthSignInParams contains all the parameters to send to the API endpoint

	for the post v1 auth sign in operation.

	Typically these are written to a http.Request.
*/
type PostV1AuthSignInParams struct {

	/* Input.

	   Данные для авторизации
	*/
	Input *models.DtoLogUser

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1 auth sign in params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1AuthSignInParams) WithDefaults() *PostV1AuthSignInParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1 auth sign in params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1AuthSignInParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1 auth sign in params
func (o *PostV1AuthSignInParams) WithTimeout(timeout time.Duration) *PostV1AuthSignInParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 auth sign in params
func (o *PostV1AuthSignInParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 auth sign in params
func (o *PostV1AuthSignInParams) WithContext(ctx context.Context) *PostV1AuthSignInParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 auth sign in params
func (o *PostV1AuthSignInParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 auth sign in params
func (o *PostV1AuthSignInParams) WithHTTPClient(client *http.Client) *PostV1AuthSignInParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 auth sign in params
func (o *PostV1AuthSignInParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInput adds the input to the post v1 auth sign in params
func (o *PostV1AuthSignInParams) WithInput(input *models.DtoLogUser) *PostV1AuthSignInParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the post v1 auth sign in params
func (o *PostV1AuthSignInParams) SetInput(input *models.DtoLogUser) {
	o.Input = input
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1AuthSignInParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
