apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: 192.168.130.112:5432
    database: ksu
    user: ksu_user
    secureJsonData:
      password: "ksu_password"
    editable: true
    jsonData:
      database: ksu
      sslmode: disable
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

