events {
	worker_connections 1024;
}

http {
	server {
		listen 80;
		server_name localhost;
        
		# Редирект всех HTTP запросов на HTTPS
		return 301 https://$host$request_uri;
	}
	
	
	server {
		listen 443 ssl;
		server_name localhost;

		ssl_certificate /etc/nginx/certs/fazenda.crt;
		ssl_certificate_key /etc/nginx/certs/fazenda.key;

		# Обработка статики фронтенда
		location / {
			proxy_pass http://frontend:3001;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}

		# Проксирование API запросов на порт 7999
		location /api/v1/ {
			proxy_pass https://localhost:7999/api/v1/;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}

		location /swagger/ {
			proxy_pass https://localhost:7999/swagger/;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}
	}

	server {
		listen 7999 ssl;
		server_name localhost;

		ssl_certificate /etc/nginx/certs/fazenda.crt;
		ssl_certificate_key /etc/nginx/certs/fazenda.key;

		# Проксирование на API-GW
		location / {
			proxy_pass http://192.168.130.114:8001;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}
	}


}
