{
 "title": "Ids Log Dashboard",
 "tags": [
  "Log",
  "Azone",
  "Continent",
  "Ids"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "POSTGRES", "label": "Datasource", "query": "grafana-postgresql-datasource" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "SELECT DISTINCT hostname FROM ids_log ;"
   },
   {
    "name": "proto",
    "label": "Protocol",
    "query": "SELECT DISTINCT proto FROM ids_log ;"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align: center;font-size:70px;\">${hostname}</p>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as \"BLOCKED\"\nFROM ids_log\nWHERE $__timeFilter(timestamp)\n  AND action = 'blocked'\n  AND hostname = '$hostname'"
    },
    {
     "rawSql": "SELECT COUNT(*) as \"ALLOWED\"\nFROM ids_log\nWHERE $__timeFilter(timestamp)\n  AND action = 'allowed'\n  AND hostname = '$hostname'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as \"UDP\"\nFROM ids_log\nWHERE $__timeFilter(timestamp)\n  AND proto = 'UDP'\n  AND hostname = '$hostname'"
    },
    {
     "rawSql": "SELECT COUNT(*) as \"TCP\"\nFROM ids_log\nWHERE $__timeFilter(timestamp)\n  AND proto = 'TCP'\n  AND hostname = '$hostname'"
    }
   ]
  },
  { "title": "События протокола $proto", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "proto" },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 14 },
   "options": {
    "content": "<p style=\"text-align: center;font-size:80px;\">${proto}</p>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as \"BLOCKED\"\nFROM ids_log\nWHERE $__timeFilter(timestamp)\n  AND proto = $proto \n  AND action = 'blocked'\n  AND hostname = '$hostname'"
    },
    {
     "rawSql": "SELECT COUNT(*) as \"ALLOWED\"\nFROM ids_log\nWHERE $__timeFilter(timestamp)\n  AND proto = $proto \n  AND action = 'allowed'\n  AND hostname = '$hostname'"
    }
   ]
  },
  {
   "title": "Страна отправителя",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    src_country ,\n    COUNT(*) as value\nFROM ids_log\nWHERE $__timeFilter(timestamp)\n  AND proto = $proto\n  AND hostname = '$hostname' \nGROUP BY src_country\nORDER BY value DESC"
    }
   ]
  },
  {
   "title": "Страна получателя",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    dest_country ,\n    COUNT(*) as value\nFROM ids_log\nWHERE $__timeFilter(timestamp)\n  AND proto = $proto\n  AND hostname = '$hostname' \nGROUP BY dest_country\nORDER BY value DESC"
    }
   ]
  },
  {
   "title": "Все события",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT \n    $__timeGroup(timestamp, $__interval) as time,\n    proto,\n    COUNT(*) as \"ALL ACTIONS\"\nFROM ids_log\nWHERE $__timeFilter(timestamp)\n  AND proto = $proto\n  AND hostname = '$hostname' \nGROUP BY time, proto\nORDER BY time"
    }
   ]
  },
  {
   "title": "События Allowed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT \n    $__timeGroup(timestamp, $__interval) as time,\n    proto,\n    COUNT(*) as \"ALLOWED\"\nFROM ids_log\nWHERE $__timeFilter(timestamp)\n  AND proto = $proto\n  AND hostname = '$hostname' \n  AND action = 'allowed'\nGROUP BY time, proto\nORDER BY time"
    }
   ]
  },
  {
   "title": "События Blocked",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT \n    $__timeGroup(timestamp, $__interval) as time,\n    proto,\n    COUNT(*) as \"BLOCKED\"\nFROM ids_log\nWHERE $__timeFilter(timestamp)\n  AND proto = $proto\n  AND hostname = '$hostname' \n  AND action = 'blocked'\nGROUP BY time, proto\nORDER BY time"
    }
   ]
  }
 ]
}