// Code generated by go-swagger; DO NOT EDIT.

package common

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"api-gateway/pkg/models"
)

// GetAPIV1DevicesReader is a Reader for the GetAPIV1Devices structure.
type GetAPIV1DevicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1DevicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1DevicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetAPIV1DevicesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1DevicesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/devices] GetAPIV1Devices", response, response.Code())
	}
}

// NewGetAPIV1DevicesOK creates a GetAPIV1DevicesOK with default headers values
func NewGetAPIV1DevicesOK() *GetAPIV1DevicesOK {
	return &GetAPIV1DevicesOK{}
}

/*
GetAPIV1DevicesOK describes a response with status code 200, with default header values.

Список имен устройств
*/
type GetAPIV1DevicesOK struct {
	Payload []string
}

// IsSuccess returns true when this get Api v1 devices o k response has a 2xx status code
func (o *GetAPIV1DevicesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 devices o k response has a 3xx status code
func (o *GetAPIV1DevicesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 devices o k response has a 4xx status code
func (o *GetAPIV1DevicesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 devices o k response has a 5xx status code
func (o *GetAPIV1DevicesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 devices o k response a status code equal to that given
func (o *GetAPIV1DevicesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 devices o k response
func (o *GetAPIV1DevicesOK) Code() int {
	return 200
}

func (o *GetAPIV1DevicesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/devices][%d] getApiV1DevicesOK %s", 200, payload)
}

func (o *GetAPIV1DevicesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/devices][%d] getApiV1DevicesOK %s", 200, payload)
}

func (o *GetAPIV1DevicesOK) GetPayload() []string {
	return o.Payload
}

func (o *GetAPIV1DevicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1DevicesForbidden creates a GetAPIV1DevicesForbidden with default headers values
func NewGetAPIV1DevicesForbidden() *GetAPIV1DevicesForbidden {
	return &GetAPIV1DevicesForbidden{}
}

/*
GetAPIV1DevicesForbidden describes a response with status code 403, with default header values.

Недостаточно прав для доступа к списку устройств
*/
type GetAPIV1DevicesForbidden struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get Api v1 devices forbidden response has a 2xx status code
func (o *GetAPIV1DevicesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 devices forbidden response has a 3xx status code
func (o *GetAPIV1DevicesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 devices forbidden response has a 4xx status code
func (o *GetAPIV1DevicesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 devices forbidden response has a 5xx status code
func (o *GetAPIV1DevicesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 devices forbidden response a status code equal to that given
func (o *GetAPIV1DevicesForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v1 devices forbidden response
func (o *GetAPIV1DevicesForbidden) Code() int {
	return 403
}

func (o *GetAPIV1DevicesForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/devices][%d] getApiV1DevicesForbidden %s", 403, payload)
}

func (o *GetAPIV1DevicesForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/devices][%d] getApiV1DevicesForbidden %s", 403, payload)
}

func (o *GetAPIV1DevicesForbidden) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetAPIV1DevicesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1DevicesInternalServerError creates a GetAPIV1DevicesInternalServerError with default headers values
func NewGetAPIV1DevicesInternalServerError() *GetAPIV1DevicesInternalServerError {
	return &GetAPIV1DevicesInternalServerError{}
}

/*
GetAPIV1DevicesInternalServerError describes a response with status code 500, with default header values.

Ошибка при получении имен устройств
*/
type GetAPIV1DevicesInternalServerError struct {
	Payload map[string]string
}

// IsSuccess returns true when this get Api v1 devices internal server error response has a 2xx status code
func (o *GetAPIV1DevicesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 devices internal server error response has a 3xx status code
func (o *GetAPIV1DevicesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 devices internal server error response has a 4xx status code
func (o *GetAPIV1DevicesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 devices internal server error response has a 5xx status code
func (o *GetAPIV1DevicesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 devices internal server error response a status code equal to that given
func (o *GetAPIV1DevicesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 devices internal server error response
func (o *GetAPIV1DevicesInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1DevicesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/devices][%d] getApiV1DevicesInternalServerError %s", 500, payload)
}

func (o *GetAPIV1DevicesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/devices][%d] getApiV1DevicesInternalServerError %s", 500, payload)
}

func (o *GetAPIV1DevicesInternalServerError) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetAPIV1DevicesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
