// Code generated by go-swagger; DO NOT EDIT.

package common

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIV1CategoriesReader is a Reader for the GetAPIV1Categories structure.
type GetAPIV1CategoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1CategoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1CategoriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetAPIV1CategoriesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/categories] GetAPIV1Categories", response, response.Code())
	}
}

// NewGetAPIV1CategoriesOK creates a GetAPIV1CategoriesOK with default headers values
func NewGetAPIV1CategoriesOK() *GetAPIV1CategoriesOK {
	return &GetAPIV1CategoriesOK{}
}

/*
GetAPIV1CategoriesOK describes a response with status code 200, with default header values.

Список категорий контента
*/
type GetAPIV1CategoriesOK struct {
	Payload []string
}

// IsSuccess returns true when this get Api v1 categories o k response has a 2xx status code
func (o *GetAPIV1CategoriesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 categories o k response has a 3xx status code
func (o *GetAPIV1CategoriesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 categories o k response has a 4xx status code
func (o *GetAPIV1CategoriesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 categories o k response has a 5xx status code
func (o *GetAPIV1CategoriesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 categories o k response a status code equal to that given
func (o *GetAPIV1CategoriesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 categories o k response
func (o *GetAPIV1CategoriesOK) Code() int {
	return 200
}

func (o *GetAPIV1CategoriesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/categories][%d] getApiV1CategoriesOK %s", 200, payload)
}

func (o *GetAPIV1CategoriesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/categories][%d] getApiV1CategoriesOK %s", 200, payload)
}

func (o *GetAPIV1CategoriesOK) GetPayload() []string {
	return o.Payload
}

func (o *GetAPIV1CategoriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1CategoriesInternalServerError creates a GetAPIV1CategoriesInternalServerError with default headers values
func NewGetAPIV1CategoriesInternalServerError() *GetAPIV1CategoriesInternalServerError {
	return &GetAPIV1CategoriesInternalServerError{}
}

/*
GetAPIV1CategoriesInternalServerError describes a response with status code 500, with default header values.

Ошибка при получении списка категорий
*/
type GetAPIV1CategoriesInternalServerError struct {
	Payload map[string]string
}

// IsSuccess returns true when this get Api v1 categories internal server error response has a 2xx status code
func (o *GetAPIV1CategoriesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 categories internal server error response has a 3xx status code
func (o *GetAPIV1CategoriesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 categories internal server error response has a 4xx status code
func (o *GetAPIV1CategoriesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 categories internal server error response has a 5xx status code
func (o *GetAPIV1CategoriesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 categories internal server error response a status code equal to that given
func (o *GetAPIV1CategoriesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 categories internal server error response
func (o *GetAPIV1CategoriesInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1CategoriesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/categories][%d] getApiV1CategoriesInternalServerError %s", 500, payload)
}

func (o *GetAPIV1CategoriesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/categories][%d] getApiV1CategoriesInternalServerError %s", 500, payload)
}

func (o *GetAPIV1CategoriesInternalServerError) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetAPIV1CategoriesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
