// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/add": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Добавление логов в БД",
                "parameters": [
                    {
                        "description": "Структура записи бизнес лога",
                        "name": "record",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DtoBusinessLog"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успех",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "query params is not valid",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/healthcheck": {
            "get": {
                "summary": "Проверка здоровья сервиса",
                "responses": {
                    "200": {
                        "description": "ready",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает массив логов",
                "summary": "Получение логов из БД с возможностью фильтрации и пагинации",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Номер страницы с 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Колличесвто отображаемых элементов на странице",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Фильтр по роли",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Фильтр по contextID",
                        "name": "context_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "фильтр по username/entity/description",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Отфильтрованные логи",
                        "schema": {
                            "$ref": "#/definitions/models.Logs"
                        }
                    },
                    "400": {
                        "description": "query params is not valid",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.DtoBusinessLog": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "string"
                },
                "context_str": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "entity": {
                    "description": "user, context",
                    "type": "string"
                },
                "entity_id": {
                    "description": "userID or ContextID",
                    "type": "string"
                },
                "event_type": {
                    "description": "Timestamp   time.Time ` + "`" + `json:\"timestamp,omitzero\" gorm:\"column:timestamp;type:timestamp with time zone;not null\"` + "`" + `",
                    "type": "string"
                },
                "new_value": {
                    "$ref": "#/definitions/dto.Value"
                },
                "old_value": {
                    "$ref": "#/definitions/dto.Value"
                },
                "user_name": {
                    "type": "string"
                },
                "user_role": {
                    "description": "SA, CA",
                    "type": "string"
                }
            }
        },
        "dto.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.Value": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "login": {
                    "type": "string"
                },
                "patronymic": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "models.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.BusinessLog": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "string"
                },
                "context_str": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "entity": {
                    "description": "user, context",
                    "type": "string"
                },
                "entity_id": {
                    "description": "userID or ContextID",
                    "type": "string"
                },
                "event_type": {
                    "description": "CREATE, UPDATE, DELETE",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "new_value": {
                    "$ref": "#/definitions/models.JSONB"
                },
                "old_value": {
                    "$ref": "#/definitions/models.JSONB"
                },
                "timestamp": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "user_role": {
                    "description": "SA, CA",
                    "type": "string"
                }
            }
        },
        "models.JSONB": {
            "type": "object",
            "additionalProperties": true
        },
        "models.Logs": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BusinessLog"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/models.Meta"
                }
            }
        },
        "models.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "app for get logs",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
