// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"api-gateway/pkg/models"
)

// PostAPIV1AddReader is a Reader for the PostAPIV1Add structure.
type PostAPIV1AddReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1AddReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1AddOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1AddBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1AddInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/add] PostAPIV1Add", response, response.Code())
	}
}

// NewPostAPIV1AddOK creates a PostAPIV1AddOK with default headers values
func NewPostAPIV1AddOK() *PostAPIV1AddOK {
	return &PostAPIV1AddOK{}
}

/*
PostAPIV1AddOK describes a response with status code 200, with default header values.

Успех
*/
type PostAPIV1AddOK struct {
	Payload *models.DtoSuccessResponse
}

// IsSuccess returns true when this post Api v1 add o k response has a 2xx status code
func (o *PostAPIV1AddOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 add o k response has a 3xx status code
func (o *PostAPIV1AddOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 add o k response has a 4xx status code
func (o *PostAPIV1AddOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 add o k response has a 5xx status code
func (o *PostAPIV1AddOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 add o k response a status code equal to that given
func (o *PostAPIV1AddOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v1 add o k response
func (o *PostAPIV1AddOK) Code() int {
	return 200
}

func (o *PostAPIV1AddOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/add][%d] postApiV1AddOK %s", 200, payload)
}

func (o *PostAPIV1AddOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/add][%d] postApiV1AddOK %s", 200, payload)
}

func (o *PostAPIV1AddOK) GetPayload() *models.DtoSuccessResponse {
	return o.Payload
}

func (o *PostAPIV1AddOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoSuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1AddBadRequest creates a PostAPIV1AddBadRequest with default headers values
func NewPostAPIV1AddBadRequest() *PostAPIV1AddBadRequest {
	return &PostAPIV1AddBadRequest{}
}

/*
PostAPIV1AddBadRequest describes a response with status code 400, with default header values.

query params is not valid
*/
type PostAPIV1AddBadRequest struct {
	Payload *models.ModelsAPIError
}

// IsSuccess returns true when this post Api v1 add bad request response has a 2xx status code
func (o *PostAPIV1AddBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 add bad request response has a 3xx status code
func (o *PostAPIV1AddBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 add bad request response has a 4xx status code
func (o *PostAPIV1AddBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 add bad request response has a 5xx status code
func (o *PostAPIV1AddBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 add bad request response a status code equal to that given
func (o *PostAPIV1AddBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 add bad request response
func (o *PostAPIV1AddBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1AddBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/add][%d] postApiV1AddBadRequest %s", 400, payload)
}

func (o *PostAPIV1AddBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/add][%d] postApiV1AddBadRequest %s", 400, payload)
}

func (o *PostAPIV1AddBadRequest) GetPayload() *models.ModelsAPIError {
	return o.Payload
}

func (o *PostAPIV1AddBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1AddInternalServerError creates a PostAPIV1AddInternalServerError with default headers values
func NewPostAPIV1AddInternalServerError() *PostAPIV1AddInternalServerError {
	return &PostAPIV1AddInternalServerError{}
}

/*
PostAPIV1AddInternalServerError describes a response with status code 500, with default header values.

internal error
*/
type PostAPIV1AddInternalServerError struct {
	Payload *models.ModelsAPIError
}

// IsSuccess returns true when this post Api v1 add internal server error response has a 2xx status code
func (o *PostAPIV1AddInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 add internal server error response has a 3xx status code
func (o *PostAPIV1AddInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 add internal server error response has a 4xx status code
func (o *PostAPIV1AddInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 add internal server error response has a 5xx status code
func (o *PostAPIV1AddInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 add internal server error response a status code equal to that given
func (o *PostAPIV1AddInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 add internal server error response
func (o *PostAPIV1AddInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1AddInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/add][%d] postApiV1AddInternalServerError %s", 500, payload)
}

func (o *PostAPIV1AddInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/add][%d] postApiV1AddInternalServerError %s", 500, payload)
}

func (o *PostAPIV1AddInternalServerError) GetPayload() *models.ModelsAPIError {
	return o.Payload
}

func (o *PostAPIV1AddInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
