// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"api-gateway/pkg/models"
)

// GetV1UsersUserIDReader is a Reader for the GetV1UsersUserID structure.
type GetV1UsersUserIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1UsersUserIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1UsersUserIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetV1UsersUserIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetV1UsersUserIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetV1UsersUserIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetV1UsersUserIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetV1UsersUserIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/users/{userId}] GetV1UsersUserID", response, response.Code())
	}
}

// NewGetV1UsersUserIDOK creates a GetV1UsersUserIDOK with default headers values
func NewGetV1UsersUserIDOK() *GetV1UsersUserIDOK {
	return &GetV1UsersUserIDOK{}
}

/*
GetV1UsersUserIDOK describes a response with status code 200, with default header values.

OK
*/
type GetV1UsersUserIDOK struct {
	Payload *models.ModelsUser
}

// IsSuccess returns true when this get v1 users user Id o k response has a 2xx status code
func (o *GetV1UsersUserIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 users user Id o k response has a 3xx status code
func (o *GetV1UsersUserIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 users user Id o k response has a 4xx status code
func (o *GetV1UsersUserIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 users user Id o k response has a 5xx status code
func (o *GetV1UsersUserIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 users user Id o k response a status code equal to that given
func (o *GetV1UsersUserIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 users user Id o k response
func (o *GetV1UsersUserIDOK) Code() int {
	return 200
}

func (o *GetV1UsersUserIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/{userId}][%d] getV1UsersUserIdOK %s", 200, payload)
}

func (o *GetV1UsersUserIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/{userId}][%d] getV1UsersUserIdOK %s", 200, payload)
}

func (o *GetV1UsersUserIDOK) GetPayload() *models.ModelsUser {
	return o.Payload
}

func (o *GetV1UsersUserIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsUser)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1UsersUserIDBadRequest creates a GetV1UsersUserIDBadRequest with default headers values
func NewGetV1UsersUserIDBadRequest() *GetV1UsersUserIDBadRequest {
	return &GetV1UsersUserIDBadRequest{}
}

/*
GetV1UsersUserIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetV1UsersUserIDBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 users user Id bad request response has a 2xx status code
func (o *GetV1UsersUserIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 users user Id bad request response has a 3xx status code
func (o *GetV1UsersUserIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 users user Id bad request response has a 4xx status code
func (o *GetV1UsersUserIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 users user Id bad request response has a 5xx status code
func (o *GetV1UsersUserIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 users user Id bad request response a status code equal to that given
func (o *GetV1UsersUserIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get v1 users user Id bad request response
func (o *GetV1UsersUserIDBadRequest) Code() int {
	return 400
}

func (o *GetV1UsersUserIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/{userId}][%d] getV1UsersUserIdBadRequest %s", 400, payload)
}

func (o *GetV1UsersUserIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/{userId}][%d] getV1UsersUserIdBadRequest %s", 400, payload)
}

func (o *GetV1UsersUserIDBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1UsersUserIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1UsersUserIDUnauthorized creates a GetV1UsersUserIDUnauthorized with default headers values
func NewGetV1UsersUserIDUnauthorized() *GetV1UsersUserIDUnauthorized {
	return &GetV1UsersUserIDUnauthorized{}
}

/*
GetV1UsersUserIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetV1UsersUserIDUnauthorized struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 users user Id unauthorized response has a 2xx status code
func (o *GetV1UsersUserIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 users user Id unauthorized response has a 3xx status code
func (o *GetV1UsersUserIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 users user Id unauthorized response has a 4xx status code
func (o *GetV1UsersUserIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 users user Id unauthorized response has a 5xx status code
func (o *GetV1UsersUserIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 users user Id unauthorized response a status code equal to that given
func (o *GetV1UsersUserIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get v1 users user Id unauthorized response
func (o *GetV1UsersUserIDUnauthorized) Code() int {
	return 401
}

func (o *GetV1UsersUserIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/{userId}][%d] getV1UsersUserIdUnauthorized %s", 401, payload)
}

func (o *GetV1UsersUserIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/{userId}][%d] getV1UsersUserIdUnauthorized %s", 401, payload)
}

func (o *GetV1UsersUserIDUnauthorized) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1UsersUserIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1UsersUserIDForbidden creates a GetV1UsersUserIDForbidden with default headers values
func NewGetV1UsersUserIDForbidden() *GetV1UsersUserIDForbidden {
	return &GetV1UsersUserIDForbidden{}
}

/*
GetV1UsersUserIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetV1UsersUserIDForbidden struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 users user Id forbidden response has a 2xx status code
func (o *GetV1UsersUserIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 users user Id forbidden response has a 3xx status code
func (o *GetV1UsersUserIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 users user Id forbidden response has a 4xx status code
func (o *GetV1UsersUserIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 users user Id forbidden response has a 5xx status code
func (o *GetV1UsersUserIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 users user Id forbidden response a status code equal to that given
func (o *GetV1UsersUserIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get v1 users user Id forbidden response
func (o *GetV1UsersUserIDForbidden) Code() int {
	return 403
}

func (o *GetV1UsersUserIDForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/{userId}][%d] getV1UsersUserIdForbidden %s", 403, payload)
}

func (o *GetV1UsersUserIDForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/{userId}][%d] getV1UsersUserIdForbidden %s", 403, payload)
}

func (o *GetV1UsersUserIDForbidden) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1UsersUserIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1UsersUserIDNotFound creates a GetV1UsersUserIDNotFound with default headers values
func NewGetV1UsersUserIDNotFound() *GetV1UsersUserIDNotFound {
	return &GetV1UsersUserIDNotFound{}
}

/*
GetV1UsersUserIDNotFound describes a response with status code 404, with default header values.

Пользователь не найден
*/
type GetV1UsersUserIDNotFound struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 users user Id not found response has a 2xx status code
func (o *GetV1UsersUserIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 users user Id not found response has a 3xx status code
func (o *GetV1UsersUserIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 users user Id not found response has a 4xx status code
func (o *GetV1UsersUserIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 users user Id not found response has a 5xx status code
func (o *GetV1UsersUserIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 users user Id not found response a status code equal to that given
func (o *GetV1UsersUserIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get v1 users user Id not found response
func (o *GetV1UsersUserIDNotFound) Code() int {
	return 404
}

func (o *GetV1UsersUserIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/{userId}][%d] getV1UsersUserIdNotFound %s", 404, payload)
}

func (o *GetV1UsersUserIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/{userId}][%d] getV1UsersUserIdNotFound %s", 404, payload)
}

func (o *GetV1UsersUserIDNotFound) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1UsersUserIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1UsersUserIDInternalServerError creates a GetV1UsersUserIDInternalServerError with default headers values
func NewGetV1UsersUserIDInternalServerError() *GetV1UsersUserIDInternalServerError {
	return &GetV1UsersUserIDInternalServerError{}
}

/*
GetV1UsersUserIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetV1UsersUserIDInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 users user Id internal server error response has a 2xx status code
func (o *GetV1UsersUserIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 users user Id internal server error response has a 3xx status code
func (o *GetV1UsersUserIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 users user Id internal server error response has a 4xx status code
func (o *GetV1UsersUserIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 users user Id internal server error response has a 5xx status code
func (o *GetV1UsersUserIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get v1 users user Id internal server error response a status code equal to that given
func (o *GetV1UsersUserIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get v1 users user Id internal server error response
func (o *GetV1UsersUserIDInternalServerError) Code() int {
	return 500
}

func (o *GetV1UsersUserIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/{userId}][%d] getV1UsersUserIdInternalServerError %s", 500, payload)
}

func (o *GetV1UsersUserIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/{userId}][%d] getV1UsersUserIdInternalServerError %s", 500, payload)
}

func (o *GetV1UsersUserIDInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1UsersUserIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
