// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"api-gateway/pkg/models"
)

// GetV1UsersCountByRoleReader is a Reader for the GetV1UsersCountByRole structure.
type GetV1UsersCountByRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1UsersCountByRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1UsersCountByRoleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetV1UsersCountByRoleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetV1UsersCountByRoleUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetV1UsersCountByRoleForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetV1UsersCountByRoleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/users/count-by-role] GetV1UsersCountByRole", response, response.Code())
	}
}

// NewGetV1UsersCountByRoleOK creates a GetV1UsersCountByRoleOK with default headers values
func NewGetV1UsersCountByRoleOK() *GetV1UsersCountByRoleOK {
	return &GetV1UsersCountByRoleOK{}
}

/*
GetV1UsersCountByRoleOK describes a response with status code 200, with default header values.

OK
*/
type GetV1UsersCountByRoleOK struct {
	Payload *models.DtoCountUserByRoleResponse
}

// IsSuccess returns true when this get v1 users count by role o k response has a 2xx status code
func (o *GetV1UsersCountByRoleOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 users count by role o k response has a 3xx status code
func (o *GetV1UsersCountByRoleOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 users count by role o k response has a 4xx status code
func (o *GetV1UsersCountByRoleOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 users count by role o k response has a 5xx status code
func (o *GetV1UsersCountByRoleOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 users count by role o k response a status code equal to that given
func (o *GetV1UsersCountByRoleOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 users count by role o k response
func (o *GetV1UsersCountByRoleOK) Code() int {
	return 200
}

func (o *GetV1UsersCountByRoleOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/count-by-role][%d] getV1UsersCountByRoleOK %s", 200, payload)
}

func (o *GetV1UsersCountByRoleOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/count-by-role][%d] getV1UsersCountByRoleOK %s", 200, payload)
}

func (o *GetV1UsersCountByRoleOK) GetPayload() *models.DtoCountUserByRoleResponse {
	return o.Payload
}

func (o *GetV1UsersCountByRoleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoCountUserByRoleResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1UsersCountByRoleBadRequest creates a GetV1UsersCountByRoleBadRequest with default headers values
func NewGetV1UsersCountByRoleBadRequest() *GetV1UsersCountByRoleBadRequest {
	return &GetV1UsersCountByRoleBadRequest{}
}

/*
GetV1UsersCountByRoleBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetV1UsersCountByRoleBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 users count by role bad request response has a 2xx status code
func (o *GetV1UsersCountByRoleBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 users count by role bad request response has a 3xx status code
func (o *GetV1UsersCountByRoleBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 users count by role bad request response has a 4xx status code
func (o *GetV1UsersCountByRoleBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 users count by role bad request response has a 5xx status code
func (o *GetV1UsersCountByRoleBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 users count by role bad request response a status code equal to that given
func (o *GetV1UsersCountByRoleBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get v1 users count by role bad request response
func (o *GetV1UsersCountByRoleBadRequest) Code() int {
	return 400
}

func (o *GetV1UsersCountByRoleBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/count-by-role][%d] getV1UsersCountByRoleBadRequest %s", 400, payload)
}

func (o *GetV1UsersCountByRoleBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/count-by-role][%d] getV1UsersCountByRoleBadRequest %s", 400, payload)
}

func (o *GetV1UsersCountByRoleBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1UsersCountByRoleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1UsersCountByRoleUnauthorized creates a GetV1UsersCountByRoleUnauthorized with default headers values
func NewGetV1UsersCountByRoleUnauthorized() *GetV1UsersCountByRoleUnauthorized {
	return &GetV1UsersCountByRoleUnauthorized{}
}

/*
GetV1UsersCountByRoleUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetV1UsersCountByRoleUnauthorized struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 users count by role unauthorized response has a 2xx status code
func (o *GetV1UsersCountByRoleUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 users count by role unauthorized response has a 3xx status code
func (o *GetV1UsersCountByRoleUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 users count by role unauthorized response has a 4xx status code
func (o *GetV1UsersCountByRoleUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 users count by role unauthorized response has a 5xx status code
func (o *GetV1UsersCountByRoleUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 users count by role unauthorized response a status code equal to that given
func (o *GetV1UsersCountByRoleUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get v1 users count by role unauthorized response
func (o *GetV1UsersCountByRoleUnauthorized) Code() int {
	return 401
}

func (o *GetV1UsersCountByRoleUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/count-by-role][%d] getV1UsersCountByRoleUnauthorized %s", 401, payload)
}

func (o *GetV1UsersCountByRoleUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/count-by-role][%d] getV1UsersCountByRoleUnauthorized %s", 401, payload)
}

func (o *GetV1UsersCountByRoleUnauthorized) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1UsersCountByRoleUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1UsersCountByRoleForbidden creates a GetV1UsersCountByRoleForbidden with default headers values
func NewGetV1UsersCountByRoleForbidden() *GetV1UsersCountByRoleForbidden {
	return &GetV1UsersCountByRoleForbidden{}
}

/*
GetV1UsersCountByRoleForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetV1UsersCountByRoleForbidden struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 users count by role forbidden response has a 2xx status code
func (o *GetV1UsersCountByRoleForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 users count by role forbidden response has a 3xx status code
func (o *GetV1UsersCountByRoleForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 users count by role forbidden response has a 4xx status code
func (o *GetV1UsersCountByRoleForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 users count by role forbidden response has a 5xx status code
func (o *GetV1UsersCountByRoleForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 users count by role forbidden response a status code equal to that given
func (o *GetV1UsersCountByRoleForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get v1 users count by role forbidden response
func (o *GetV1UsersCountByRoleForbidden) Code() int {
	return 403
}

func (o *GetV1UsersCountByRoleForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/count-by-role][%d] getV1UsersCountByRoleForbidden %s", 403, payload)
}

func (o *GetV1UsersCountByRoleForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/count-by-role][%d] getV1UsersCountByRoleForbidden %s", 403, payload)
}

func (o *GetV1UsersCountByRoleForbidden) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1UsersCountByRoleForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1UsersCountByRoleInternalServerError creates a GetV1UsersCountByRoleInternalServerError with default headers values
func NewGetV1UsersCountByRoleInternalServerError() *GetV1UsersCountByRoleInternalServerError {
	return &GetV1UsersCountByRoleInternalServerError{}
}

/*
GetV1UsersCountByRoleInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetV1UsersCountByRoleInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 users count by role internal server error response has a 2xx status code
func (o *GetV1UsersCountByRoleInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 users count by role internal server error response has a 3xx status code
func (o *GetV1UsersCountByRoleInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 users count by role internal server error response has a 4xx status code
func (o *GetV1UsersCountByRoleInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 users count by role internal server error response has a 5xx status code
func (o *GetV1UsersCountByRoleInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get v1 users count by role internal server error response a status code equal to that given
func (o *GetV1UsersCountByRoleInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get v1 users count by role internal server error response
func (o *GetV1UsersCountByRoleInternalServerError) Code() int {
	return 500
}

func (o *GetV1UsersCountByRoleInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/count-by-role][%d] getV1UsersCountByRoleInternalServerError %s", 500, payload)
}

func (o *GetV1UsersCountByRoleInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/users/count-by-role][%d] getV1UsersCountByRoleInternalServerError %s", 500, payload)
}

func (o *GetV1UsersCountByRoleInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1UsersCountByRoleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
