// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new users API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new users API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new users API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for users API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteV1UsersUserID(params *DeleteV1UsersUserIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteV1UsersUserIDOK, error)

	DeleteV1UsersUserIDRoles(params *DeleteV1UsersUserIDRolesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteV1UsersUserIDRolesOK, error)

	GetV1Users(params *GetV1UsersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1UsersOK, error)

	GetV1UsersCount(params *GetV1UsersCountParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1UsersCountOK, error)

	GetV1UsersCountByRole(params *GetV1UsersCountByRoleParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1UsersCountByRoleOK, error)

	GetV1UsersCountContextContextID(params *GetV1UsersCountContextContextIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1UsersCountContextContextIDOK, error)

	GetV1UsersProfile(params *GetV1UsersProfileParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1UsersProfileOK, error)

	GetV1UsersUserID(params *GetV1UsersUserIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1UsersUserIDOK, error)

	PostV1Users(params *PostV1UsersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostV1UsersCreated, error)

	PutV1UsersProfilePass(params *PutV1UsersProfilePassParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutV1UsersProfilePassOK, error)

	PutV1UsersUserID(params *PutV1UsersUserIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutV1UsersUserIDOK, error)

	PutV1UsersUserIDPassOtp(params *PutV1UsersUserIDPassOtpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutV1UsersUserIDPassOtpOK, error)

	PutV1UsersUserIDRoles(params *PutV1UsersUserIDRolesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutV1UsersUserIDRolesOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteV1UsersUserID удалениеs пользователя из системы

Запрос для удаления существующего пользователя из систему.
*/
func (a *Client) DeleteV1UsersUserID(params *DeleteV1UsersUserIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteV1UsersUserIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteV1UsersUserIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteV1UsersUserID",
		Method:             "DELETE",
		PathPattern:        "/v1/users/{userId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteV1UsersUserIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteV1UsersUserIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteV1UsersUserID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteV1UsersUserIDRoles отзывs ролей пользователя в системе

Запрос для отзыва ролей пользователя из системы.
*/
func (a *Client) DeleteV1UsersUserIDRoles(params *DeleteV1UsersUserIDRolesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteV1UsersUserIDRolesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteV1UsersUserIDRolesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteV1UsersUserIDRoles",
		Method:             "DELETE",
		PathPattern:        "/v1/users/{userId}/roles",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteV1UsersUserIDRolesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteV1UsersUserIDRolesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteV1UsersUserIDRoles: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetV1Users получениеs списка пользователей с пагинацией и фильтрацией

Возвращает список пользователей с возможностью пагинации и фильтрации по ролям
*/
func (a *Client) GetV1Users(params *GetV1UsersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1UsersOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1UsersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetV1Users",
		Method:             "GET",
		PathPattern:        "/v1/users",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1UsersReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetV1UsersOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetV1Users: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetV1UsersCount получениеs числа всех пользователей системы

Получение числа всех пользователей системы.
*/
func (a *Client) GetV1UsersCount(params *GetV1UsersCountParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1UsersCountOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1UsersCountParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetV1UsersCount",
		Method:             "GET",
		PathPattern:        "/v1/users/count",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1UsersCountReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetV1UsersCountOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetV1UsersCount: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetV1UsersCountByRole получениеs информации о числе пользователй по ролям

Получение информации сколько в системе SA, CA и CO
*/
func (a *Client) GetV1UsersCountByRole(params *GetV1UsersCountByRoleParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1UsersCountByRoleOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1UsersCountByRoleParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetV1UsersCountByRole",
		Method:             "GET",
		PathPattern:        "/v1/users/count-by-role",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1UsersCountByRoleReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetV1UsersCountByRoleOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetV1UsersCountByRole: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetV1UsersCountContextContextID получениеs числа c a и c o в контексте

Получение числа CA и CO в контексте.
*/
func (a *Client) GetV1UsersCountContextContextID(params *GetV1UsersCountContextContextIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1UsersCountContextContextIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1UsersCountContextContextIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetV1UsersCountContextContextID",
		Method:             "GET",
		PathPattern:        "/v1/users/count/context/{contextID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1UsersCountContextContextIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetV1UsersCountContextContextIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetV1UsersCountContextContextID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetV1UsersProfile получениеs информации о текущем пользователе

Получение информации об авторизованном в системе пользователе
*/
func (a *Client) GetV1UsersProfile(params *GetV1UsersProfileParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1UsersProfileOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1UsersProfileParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetV1UsersProfile",
		Method:             "GET",
		PathPattern:        "/v1/users/profile",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1UsersProfileReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetV1UsersProfileOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetV1UsersProfile: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetV1UsersUserID получениеs информации о пользователе

Возвращает полную информацию о пользователе по его ID
*/
func (a *Client) GetV1UsersUserID(params *GetV1UsersUserIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1UsersUserIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1UsersUserIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetV1UsersUserID",
		Method:             "GET",
		PathPattern:        "/v1/users/{userId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1UsersUserIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetV1UsersUserIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetV1UsersUserID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostV1Users созданиеs нового пользователя

Создает нового пользователя с указанными данными
*/
func (a *Client) PostV1Users(params *PostV1UsersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostV1UsersCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostV1UsersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostV1Users",
		Method:             "POST",
		PathPattern:        "/v1/users",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostV1UsersReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostV1UsersCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostV1Users: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutV1UsersProfilePass изменениеs пароля текущего пользователя системы

Пользователю необходимо отправить в теле запроса новый пароль.
*/
func (a *Client) PutV1UsersProfilePass(params *PutV1UsersProfilePassParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutV1UsersProfilePassOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutV1UsersProfilePassParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutV1UsersProfilePass",
		Method:             "PUT",
		PathPattern:        "/v1/users/profile/pass",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutV1UsersProfilePassReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PutV1UsersProfilePassOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutV1UsersProfilePass: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutV1UsersUserID обновлениеs информации о пользователе системы

Запрос для обновления существующего пользователя системы.
*/
func (a *Client) PutV1UsersUserID(params *PutV1UsersUserIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutV1UsersUserIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutV1UsersUserIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutV1UsersUserID",
		Method:             "PUT",
		PathPattern:        "/v1/users/{userId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutV1UsersUserIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PutV1UsersUserIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutV1UsersUserID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutV1UsersUserIDPassOtp сбросs пользовательского пароля

Запрос для изменения пароля пользователя.
*/
func (a *Client) PutV1UsersUserIDPassOtp(params *PutV1UsersUserIDPassOtpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutV1UsersUserIDPassOtpOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutV1UsersUserIDPassOtpParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutV1UsersUserIDPassOtp",
		Method:             "PUT",
		PathPattern:        "/v1/users/{userId}/pass/otp",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutV1UsersUserIDPassOtpReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PutV1UsersUserIDPassOtpOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutV1UsersUserIDPassOtp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutV1UsersUserIDRoles обновлениеs ролей пользователя системы

Запрос для обновления списка ролей пользователя системы.
*/
func (a *Client) PutV1UsersUserIDRoles(params *PutV1UsersUserIDRolesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutV1UsersUserIDRolesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutV1UsersUserIDRolesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutV1UsersUserIDRoles",
		Method:             "PUT",
		PathPattern:        "/v1/users/{userId}/roles",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutV1UsersUserIDRolesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PutV1UsersUserIDRolesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutV1UsersUserIDRoles: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
