// Code generated by go-swagger; DO NOT EDIT.

package detection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetV1DetectionsStatParams creates a new GetV1DetectionsStatParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1DetectionsStatParams() *GetV1DetectionsStatParams {
	return &GetV1DetectionsStatParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1DetectionsStatParamsWithTimeout creates a new GetV1DetectionsStatParams object
// with the ability to set a timeout on a request.
func NewGetV1DetectionsStatParamsWithTimeout(timeout time.Duration) *GetV1DetectionsStatParams {
	return &GetV1DetectionsStatParams{
		timeout: timeout,
	}
}

// NewGetV1DetectionsStatParamsWithContext creates a new GetV1DetectionsStatParams object
// with the ability to set a context for a request.
func NewGetV1DetectionsStatParamsWithContext(ctx context.Context) *GetV1DetectionsStatParams {
	return &GetV1DetectionsStatParams{
		Context: ctx,
	}
}

// NewGetV1DetectionsStatParamsWithHTTPClient creates a new GetV1DetectionsStatParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1DetectionsStatParamsWithHTTPClient(client *http.Client) *GetV1DetectionsStatParams {
	return &GetV1DetectionsStatParams{
		HTTPClient: client,
	}
}

/*
GetV1DetectionsStatParams contains all the parameters to send to the API endpoint

	for the get v1 detections stat operation.

	Typically these are written to a http.Request.
*/
type GetV1DetectionsStatParams struct {

	/* End.

	   Конец периода в timestamp
	*/
	End int64

	/* Start.

	   Начало периода в timestamp
	*/
	Start int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 detections stat params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1DetectionsStatParams) WithDefaults() *GetV1DetectionsStatParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 detections stat params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1DetectionsStatParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 detections stat params
func (o *GetV1DetectionsStatParams) WithTimeout(timeout time.Duration) *GetV1DetectionsStatParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 detections stat params
func (o *GetV1DetectionsStatParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 detections stat params
func (o *GetV1DetectionsStatParams) WithContext(ctx context.Context) *GetV1DetectionsStatParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 detections stat params
func (o *GetV1DetectionsStatParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 detections stat params
func (o *GetV1DetectionsStatParams) WithHTTPClient(client *http.Client) *GetV1DetectionsStatParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 detections stat params
func (o *GetV1DetectionsStatParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnd adds the end to the get v1 detections stat params
func (o *GetV1DetectionsStatParams) WithEnd(end int64) *GetV1DetectionsStatParams {
	o.SetEnd(end)
	return o
}

// SetEnd adds the end to the get v1 detections stat params
func (o *GetV1DetectionsStatParams) SetEnd(end int64) {
	o.End = end
}

// WithStart adds the start to the get v1 detections stat params
func (o *GetV1DetectionsStatParams) WithStart(start int64) *GetV1DetectionsStatParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the get v1 detections stat params
func (o *GetV1DetectionsStatParams) SetStart(start int64) {
	o.Start = start
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1DetectionsStatParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param end
	qrEnd := o.End
	qEnd := swag.FormatInt64(qrEnd)
	if qEnd != "" {

		if err := r.SetQueryParam("end", qEnd); err != nil {
			return err
		}
	}

	// query param start
	qrStart := o.Start
	qStart := swag.FormatInt64(qrStart)
	if qStart != "" {

		if err := r.SetQueryParam("start", qStart); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
