// Code generated by go-swagger; DO NOT EDIT.

package reports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"api-gateway/pkg/models"
)

// GetAPIV1ReportsHostnameReader is a Reader for the GetAPIV1ReportsHostname structure.
type GetAPIV1ReportsHostnameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1ReportsHostnameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1ReportsHostnameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV1ReportsHostnameBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAPIV1ReportsHostnameForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV1ReportsHostnameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1ReportsHostnameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/reports/{hostname}] GetAPIV1ReportsHostname", response, response.Code())
	}
}

// NewGetAPIV1ReportsHostnameOK creates a GetAPIV1ReportsHostnameOK with default headers values
func NewGetAPIV1ReportsHostnameOK() *GetAPIV1ReportsHostnameOK {
	return &GetAPIV1ReportsHostnameOK{}
}

/*
GetAPIV1ReportsHostnameOK describes a response with status code 200, with default header values.

Детализированный отчет по устройству
*/
type GetAPIV1ReportsHostnameOK struct {
	Payload *models.ModelsReportForDevice
}

// IsSuccess returns true when this get Api v1 reports hostname o k response has a 2xx status code
func (o *GetAPIV1ReportsHostnameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 reports hostname o k response has a 3xx status code
func (o *GetAPIV1ReportsHostnameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 reports hostname o k response has a 4xx status code
func (o *GetAPIV1ReportsHostnameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 reports hostname o k response has a 5xx status code
func (o *GetAPIV1ReportsHostnameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 reports hostname o k response a status code equal to that given
func (o *GetAPIV1ReportsHostnameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 reports hostname o k response
func (o *GetAPIV1ReportsHostnameOK) Code() int {
	return 200
}

func (o *GetAPIV1ReportsHostnameOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/reports/{hostname}][%d] getApiV1ReportsHostnameOK %s", 200, payload)
}

func (o *GetAPIV1ReportsHostnameOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/reports/{hostname}][%d] getApiV1ReportsHostnameOK %s", 200, payload)
}

func (o *GetAPIV1ReportsHostnameOK) GetPayload() *models.ModelsReportForDevice {
	return o.Payload
}

func (o *GetAPIV1ReportsHostnameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsReportForDevice)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1ReportsHostnameBadRequest creates a GetAPIV1ReportsHostnameBadRequest with default headers values
func NewGetAPIV1ReportsHostnameBadRequest() *GetAPIV1ReportsHostnameBadRequest {
	return &GetAPIV1ReportsHostnameBadRequest{}
}

/*
GetAPIV1ReportsHostnameBadRequest describes a response with status code 400, with default header values.

Неверный формат параметров или устройство не найдено
*/
type GetAPIV1ReportsHostnameBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get Api v1 reports hostname bad request response has a 2xx status code
func (o *GetAPIV1ReportsHostnameBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 reports hostname bad request response has a 3xx status code
func (o *GetAPIV1ReportsHostnameBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 reports hostname bad request response has a 4xx status code
func (o *GetAPIV1ReportsHostnameBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 reports hostname bad request response has a 5xx status code
func (o *GetAPIV1ReportsHostnameBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 reports hostname bad request response a status code equal to that given
func (o *GetAPIV1ReportsHostnameBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v1 reports hostname bad request response
func (o *GetAPIV1ReportsHostnameBadRequest) Code() int {
	return 400
}

func (o *GetAPIV1ReportsHostnameBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/reports/{hostname}][%d] getApiV1ReportsHostnameBadRequest %s", 400, payload)
}

func (o *GetAPIV1ReportsHostnameBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/reports/{hostname}][%d] getApiV1ReportsHostnameBadRequest %s", 400, payload)
}

func (o *GetAPIV1ReportsHostnameBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ReportsHostnameBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1ReportsHostnameForbidden creates a GetAPIV1ReportsHostnameForbidden with default headers values
func NewGetAPIV1ReportsHostnameForbidden() *GetAPIV1ReportsHostnameForbidden {
	return &GetAPIV1ReportsHostnameForbidden{}
}

/*
GetAPIV1ReportsHostnameForbidden describes a response with status code 403, with default header values.

Недостаточно прав для доступа к устройству
*/
type GetAPIV1ReportsHostnameForbidden struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get Api v1 reports hostname forbidden response has a 2xx status code
func (o *GetAPIV1ReportsHostnameForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 reports hostname forbidden response has a 3xx status code
func (o *GetAPIV1ReportsHostnameForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 reports hostname forbidden response has a 4xx status code
func (o *GetAPIV1ReportsHostnameForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 reports hostname forbidden response has a 5xx status code
func (o *GetAPIV1ReportsHostnameForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 reports hostname forbidden response a status code equal to that given
func (o *GetAPIV1ReportsHostnameForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v1 reports hostname forbidden response
func (o *GetAPIV1ReportsHostnameForbidden) Code() int {
	return 403
}

func (o *GetAPIV1ReportsHostnameForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/reports/{hostname}][%d] getApiV1ReportsHostnameForbidden %s", 403, payload)
}

func (o *GetAPIV1ReportsHostnameForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/reports/{hostname}][%d] getApiV1ReportsHostnameForbidden %s", 403, payload)
}

func (o *GetAPIV1ReportsHostnameForbidden) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ReportsHostnameForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1ReportsHostnameNotFound creates a GetAPIV1ReportsHostnameNotFound with default headers values
func NewGetAPIV1ReportsHostnameNotFound() *GetAPIV1ReportsHostnameNotFound {
	return &GetAPIV1ReportsHostnameNotFound{}
}

/*
GetAPIV1ReportsHostnameNotFound describes a response with status code 404, with default header values.

Устройство не найдено в базе данных
*/
type GetAPIV1ReportsHostnameNotFound struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get Api v1 reports hostname not found response has a 2xx status code
func (o *GetAPIV1ReportsHostnameNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 reports hostname not found response has a 3xx status code
func (o *GetAPIV1ReportsHostnameNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 reports hostname not found response has a 4xx status code
func (o *GetAPIV1ReportsHostnameNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 reports hostname not found response has a 5xx status code
func (o *GetAPIV1ReportsHostnameNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 reports hostname not found response a status code equal to that given
func (o *GetAPIV1ReportsHostnameNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api v1 reports hostname not found response
func (o *GetAPIV1ReportsHostnameNotFound) Code() int {
	return 404
}

func (o *GetAPIV1ReportsHostnameNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/reports/{hostname}][%d] getApiV1ReportsHostnameNotFound %s", 404, payload)
}

func (o *GetAPIV1ReportsHostnameNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/reports/{hostname}][%d] getApiV1ReportsHostnameNotFound %s", 404, payload)
}

func (o *GetAPIV1ReportsHostnameNotFound) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ReportsHostnameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1ReportsHostnameInternalServerError creates a GetAPIV1ReportsHostnameInternalServerError with default headers values
func NewGetAPIV1ReportsHostnameInternalServerError() *GetAPIV1ReportsHostnameInternalServerError {
	return &GetAPIV1ReportsHostnameInternalServerError{}
}

/*
GetAPIV1ReportsHostnameInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера при генерации отчета
*/
type GetAPIV1ReportsHostnameInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get Api v1 reports hostname internal server error response has a 2xx status code
func (o *GetAPIV1ReportsHostnameInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 reports hostname internal server error response has a 3xx status code
func (o *GetAPIV1ReportsHostnameInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 reports hostname internal server error response has a 4xx status code
func (o *GetAPIV1ReportsHostnameInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 reports hostname internal server error response has a 5xx status code
func (o *GetAPIV1ReportsHostnameInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 reports hostname internal server error response a status code equal to that given
func (o *GetAPIV1ReportsHostnameInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 reports hostname internal server error response
func (o *GetAPIV1ReportsHostnameInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1ReportsHostnameInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/reports/{hostname}][%d] getApiV1ReportsHostnameInternalServerError %s", 500, payload)
}

func (o *GetAPIV1ReportsHostnameInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/reports/{hostname}][%d] getApiV1ReportsHostnameInternalServerError %s", 500, payload)
}

func (o *GetAPIV1ReportsHostnameInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ReportsHostnameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
