// Code generated by go-swagger; DO NOT EDIT.

package reports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"api-gateway/pkg/models"
)

// GetAPIV1ReportsReader is a Reader for the GetAPIV1Reports structure.
type GetAPIV1ReportsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1ReportsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1ReportsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV1ReportsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1ReportsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/reports] GetAPIV1Reports", response, response.Code())
	}
}

// NewGetAPIV1ReportsOK creates a GetAPIV1ReportsOK with default headers values
func NewGetAPIV1ReportsOK() *GetAPIV1ReportsOK {
	return &GetAPIV1ReportsOK{}
}

/*
GetAPIV1ReportsOK describes a response with status code 200, with default header values.

Полный отчет по активности
*/
type GetAPIV1ReportsOK struct {
	Payload *models.ModelsReport
}

// IsSuccess returns true when this get Api v1 reports o k response has a 2xx status code
func (o *GetAPIV1ReportsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 reports o k response has a 3xx status code
func (o *GetAPIV1ReportsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 reports o k response has a 4xx status code
func (o *GetAPIV1ReportsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 reports o k response has a 5xx status code
func (o *GetAPIV1ReportsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 reports o k response a status code equal to that given
func (o *GetAPIV1ReportsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 reports o k response
func (o *GetAPIV1ReportsOK) Code() int {
	return 200
}

func (o *GetAPIV1ReportsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/reports][%d] getApiV1ReportsOK %s", 200, payload)
}

func (o *GetAPIV1ReportsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/reports][%d] getApiV1ReportsOK %s", 200, payload)
}

func (o *GetAPIV1ReportsOK) GetPayload() *models.ModelsReport {
	return o.Payload
}

func (o *GetAPIV1ReportsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsReport)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1ReportsBadRequest creates a GetAPIV1ReportsBadRequest with default headers values
func NewGetAPIV1ReportsBadRequest() *GetAPIV1ReportsBadRequest {
	return &GetAPIV1ReportsBadRequest{}
}

/*
GetAPIV1ReportsBadRequest describes a response with status code 400, with default header values.

Неверный формат параметров
*/
type GetAPIV1ReportsBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get Api v1 reports bad request response has a 2xx status code
func (o *GetAPIV1ReportsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 reports bad request response has a 3xx status code
func (o *GetAPIV1ReportsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 reports bad request response has a 4xx status code
func (o *GetAPIV1ReportsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 reports bad request response has a 5xx status code
func (o *GetAPIV1ReportsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 reports bad request response a status code equal to that given
func (o *GetAPIV1ReportsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v1 reports bad request response
func (o *GetAPIV1ReportsBadRequest) Code() int {
	return 400
}

func (o *GetAPIV1ReportsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/reports][%d] getApiV1ReportsBadRequest %s", 400, payload)
}

func (o *GetAPIV1ReportsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/reports][%d] getApiV1ReportsBadRequest %s", 400, payload)
}

func (o *GetAPIV1ReportsBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ReportsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1ReportsInternalServerError creates a GetAPIV1ReportsInternalServerError with default headers values
func NewGetAPIV1ReportsInternalServerError() *GetAPIV1ReportsInternalServerError {
	return &GetAPIV1ReportsInternalServerError{}
}

/*
GetAPIV1ReportsInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера при генерации отчета
*/
type GetAPIV1ReportsInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get Api v1 reports internal server error response has a 2xx status code
func (o *GetAPIV1ReportsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 reports internal server error response has a 3xx status code
func (o *GetAPIV1ReportsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 reports internal server error response has a 4xx status code
func (o *GetAPIV1ReportsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 reports internal server error response has a 5xx status code
func (o *GetAPIV1ReportsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 reports internal server error response a status code equal to that given
func (o *GetAPIV1ReportsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 reports internal server error response
func (o *GetAPIV1ReportsInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1ReportsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/reports][%d] getApiV1ReportsInternalServerError %s", 500, payload)
}

func (o *GetAPIV1ReportsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/reports][%d] getApiV1ReportsInternalServerError %s", 500, payload)
}

func (o *GetAPIV1ReportsInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ReportsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
