// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoAuthWebhookRequest dto auth webhook request
//
// swagger:model dto.AuthWebhookRequest
type DtoAuthWebhookRequest struct {

	// Роль пользователя в системе
	Role string `json:"role,omitempty"`

	// Имя пользователя для аутентификации
	Username string `json:"username,omitempty"`
}

// Validate validates this dto auth webhook request
func (m *DtoAuthWebhookRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto auth webhook request based on context it is used
func (m *DtoAuthWebhookRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoAuthWebhookRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoAuthWebhookRequest) UnmarshalBinary(b []byte) error {
	var res DtoAuthWebhookRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
