// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoRequestStatResponse dto request stat response
//
// swagger:model dto.RequestStatResponse
type DtoRequestStatResponse struct {

	// Число точек с данными
	Count int64 `json:"count,omitempty"`

	// Список однотипных данных
	Data struct {
		ModelsRequestStat
	} `json:"data,omitempty"`

	// Тип данных
	Type string `json:"type,omitempty"`
}

// Validate validates this dto request stat response
func (m *DtoRequestStatResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoRequestStatResponse) validateData(formats strfmt.Registry) error {
	if swag.IsZero(m.Data) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this dto request stat response based on the context it is used
func (m *DtoRequestStatResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoRequestStatResponse) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *DtoRequestStatResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoRequestStatResponse) UnmarshalBinary(b []byte) error {
	var res DtoRequestStatResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
