// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoDataPointsResponse dto data points response
//
// swagger:model dto.DataPointsResponse
type DtoDataPointsResponse struct {

	// Число точек с данными
	Count int64 `json:"count,omitempty"`

	// Список однотипных данных
	Data []int64 `json:"data"`

	// Тип данных
	Type string `json:"type,omitempty"`
}

// Validate validates this dto data points response
func (m *DtoDataPointsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto data points response based on context it is used
func (m *DtoDataPointsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoDataPointsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoDataPointsResponse) UnmarshalBinary(b []byte) error {
	var res DtoDataPointsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
