// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoDetectionActRequest dto detection act request
//
// swagger:model dto.DetectionActRequest
type DtoDetectionActRequest struct {

	// action
	Action string `json:"action,omitempty"`

	// path
	Path string `json:"path,omitempty"`
}

// Validate validates this dto detection act request
func (m *DtoDetectionActRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto detection act request based on context it is used
func (m *DtoDetectionActRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoDetectionActRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoDetectionActRequest) UnmarshalBinary(b []byte) error {
	var res DtoDetectionActRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
