// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoSession dto session
//
// swagger:model dto.Session
type DtoSession struct {

	// category
	Category string `json:"category,omitempty"`

	// datetime utc
	DatetimeUtc string `json:"datetime_utc,omitempty"`

	// dst country
	DstCountry string `json:"dst_country,omitempty"`

	// dst ip
	DstIP string `json:"dst_ip,omitempty"`

	// dst port
	DstPort int64 `json:"dst_port,omitempty"`

	// hostname
	Hostname string `json:"hostname,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// proto
	Proto string `json:"proto,omitempty"`

	// src country
	SrcCountry string `json:"src_country,omitempty"`

	// src ip
	SrcIP string `json:"src_ip,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// url
	URL string `json:"url,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this dto session
func (m *DtoSession) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto session based on context it is used
func (m *DtoSession) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoSession) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoSession) UnmarshalBinary(b []byte) error {
	var res DtoSession
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
