// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoCountUserForContextResponse dto count user for context response
//
// swagger:model dto.CountUserForContextResponse
type DtoCountUserForContextResponse struct {

	// count ca
	CountCa int64 `json:"count_ca,omitempty"`

	// count co
	CountCo int64 `json:"count_co,omitempty"`
}

// Validate validates this dto count user for context response
func (m *DtoCountUserForContextResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto count user for context response based on context it is used
func (m *DtoCountUserForContextResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoCountUserForContextResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoCountUserForContextResponse) UnmarshalBinary(b []byte) error {
	var res DtoCountUserForContextResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
