// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoDetection dto detection
//
// swagger:model dto.Detection
type DtoDetection struct {

	// action
	Action string `json:"action,omitempty"`

	// categorized at
	CategorizedAt string `json:"categorized_at,omitempty"`

	// category
	Category string `json:"category,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// domain
	Domain string `json:"domain,omitempty"`

	// host name
	HostName string `json:"hostname,omitempty"`

	// ip
	IP string `json:"ip,omitempty"`

	// location
	Location string `json:"location,omitempty"`

	// port
	Port int64 `json:"port,omitempty"`

	// request count
	RequestCount int64 `json:"request_count,omitempty"`
}

// Validate validates this dto detection
func (m *DtoDetection) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto detection based on context it is used
func (m *DtoDetection) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoDetection) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoDetection) UnmarshalBinary(b []byte) error {
	var res DtoDetection
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
