// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DtoDeviceStatResponse dto device stat response
//
// swagger:model dto.DeviceStatResponse
type DtoDeviceStatResponse struct {

	// count
	Count int64 `json:"count,omitempty"`

	// data
	Data map[string]ModelsDeviceRequestStat `json:"data,omitempty"`

	// time
	Time []string `json:"time"`
}

// Validate validates this dto device stat response
func (m *DtoDeviceStatResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoDeviceStatResponse) validateData(formats strfmt.Registry) error {
	if swag.IsZero(m.Data) { // not required
		return nil
	}

	for k := range m.Data {

		if err := validate.Required("data"+"."+k, "body", m.Data[k]); err != nil {
			return err
		}
		if val, ok := m.Data[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("data" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("data" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this dto device stat response based on the context it is used
func (m *DtoDeviceStatResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoDeviceStatResponse) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Data {

		if val, ok := m.Data[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DtoDeviceStatResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoDeviceStatResponse) UnmarshalBinary(b []byte) error {
	var res DtoDeviceStatResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
