// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DtoUserCreateRequest dto user create request
//
// swagger:model dto.UserCreateRequest
type DtoUserCreateRequest struct {

	// email
	// Example: john.doe@example.com
	Email string `json:"email,omitempty"`

	// first name
	// Example: John
	// Required: true
	// Max Length: 50
	// Min Length: 1
	FirstName *string `json:"first_name"`

	// last name
	// Example: Doe
	// Required: true
	// Max Length: 50
	// Min Length: 1
	LastName *string `json:"last_name"`

	// login
	// Example: johndoe
	// Required: true
	// Max Length: 50
	// Min Length: 4
	Login *string `json:"login"`

	// password
	// Required: true
	// Max Length: 50
	// Min Length: 4
	Password *string `json:"password"`

	// patronymic
	// Example: Ivanovich
	Patronymic string `json:"patronymic,omitempty"`

	// role
	// Example: SA
	// Required: true
	Role *string `json:"role"`
}

// Validate validates this dto user create request
func (m *DtoUserCreateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFirstName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLogin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoUserCreateRequest) validateFirstName(formats strfmt.Registry) error {

	if err := validate.Required("first_name", "body", m.FirstName); err != nil {
		return err
	}

	if err := validate.MinLength("first_name", "body", *m.FirstName, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("first_name", "body", *m.FirstName, 50); err != nil {
		return err
	}

	return nil
}

func (m *DtoUserCreateRequest) validateLastName(formats strfmt.Registry) error {

	if err := validate.Required("last_name", "body", m.LastName); err != nil {
		return err
	}

	if err := validate.MinLength("last_name", "body", *m.LastName, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("last_name", "body", *m.LastName, 50); err != nil {
		return err
	}

	return nil
}

func (m *DtoUserCreateRequest) validateLogin(formats strfmt.Registry) error {

	if err := validate.Required("login", "body", m.Login); err != nil {
		return err
	}

	if err := validate.MinLength("login", "body", *m.Login, 4); err != nil {
		return err
	}

	if err := validate.MaxLength("login", "body", *m.Login, 50); err != nil {
		return err
	}

	return nil
}

func (m *DtoUserCreateRequest) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	if err := validate.MinLength("password", "body", *m.Password, 4); err != nil {
		return err
	}

	if err := validate.MaxLength("password", "body", *m.Password, 50); err != nil {
		return err
	}

	return nil
}

func (m *DtoUserCreateRequest) validateRole(formats strfmt.Registry) error {

	if err := validate.Required("role", "body", m.Role); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this dto user create request based on context it is used
func (m *DtoUserCreateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoUserCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoUserCreateRequest) UnmarshalBinary(b []byte) error {
	var res DtoUserCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
