// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoDetectionStat dto detection stat
//
// swagger:model dto.DetectionStat
type DtoDetectionStat struct {

	// accepted
	Accepted int64 `json:"accepted,omitempty"`

	// denied
	Denied int64 `json:"denied,omitempty"`

	// detected
	Detected int64 `json:"detected,omitempty"`

	// unresolved
	Unresolved int64 `json:"unresolved,omitempty"`
}

// Validate validates this dto detection stat
func (m *DtoDetectionStat) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto detection stat based on context it is used
func (m *DtoDetectionStat) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoDetectionStat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoDetectionStat) UnmarshalBinary(b []byte) error {
	var res DtoDetectionStat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
