// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsAnomalyReport models anomaly report
//
// swagger:model models.AnomalyReport
type ModelsAnomalyReport struct {

	// live count
	LiveCount int64 `json:"live_count,omitempty"`

	// stat
	Stat *ModelsRequestReport `json:"stat,omitempty"`

	// traffic
	Traffic *ModelsTraffic `json:"traffic,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this models anomaly report
func (m *ModelsAnomalyReport) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTraffic(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsAnomalyReport) validateStat(formats strfmt.Registry) error {
	if swag.IsZero(m.Stat) { // not required
		return nil
	}

	if m.Stat != nil {
		if err := m.Stat.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stat")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stat")
			}
			return err
		}
	}

	return nil
}

func (m *ModelsAnomalyReport) validateTraffic(formats strfmt.Registry) error {
	if swag.IsZero(m.Traffic) { // not required
		return nil
	}

	if m.Traffic != nil {
		if err := m.Traffic.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("traffic")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("traffic")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this models anomaly report based on the context it is used
func (m *ModelsAnomalyReport) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStat(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTraffic(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsAnomalyReport) contextValidateStat(ctx context.Context, formats strfmt.Registry) error {

	if m.Stat != nil {

		if swag.IsZero(m.Stat) { // not required
			return nil
		}

		if err := m.Stat.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stat")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stat")
			}
			return err
		}
	}

	return nil
}

func (m *ModelsAnomalyReport) contextValidateTraffic(ctx context.Context, formats strfmt.Registry) error {

	if m.Traffic != nil {

		if swag.IsZero(m.Traffic) { // not required
			return nil
		}

		if err := m.Traffic.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("traffic")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("traffic")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelsAnomalyReport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsAnomalyReport) UnmarshalBinary(b []byte) error {
	var res ModelsAnomalyReport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
