// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsCategoryStat models category stat
//
// swagger:model models.CategoryStat
type ModelsCategoryStat struct {

	// category
	Category string `json:"category,omitempty"`

	// stat
	Stat *ModelsRequestReport `json:"stat,omitempty"`
}

// Validate validates this models category stat
func (m *ModelsCategoryStat) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStat(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsCategoryStat) validateStat(formats strfmt.Registry) error {
	if swag.IsZero(m.Stat) { // not required
		return nil
	}

	if m.Stat != nil {
		if err := m.Stat.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stat")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stat")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this models category stat based on the context it is used
func (m *ModelsCategoryStat) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStat(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsCategoryStat) contextValidateStat(ctx context.Context, formats strfmt.Registry) error {

	if m.Stat != nil {

		if swag.IsZero(m.Stat) { // not required
			return nil
		}

		if err := m.Stat.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stat")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stat")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelsCategoryStat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsCategoryStat) UnmarshalBinary(b []byte) error {
	var res ModelsCategoryStat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
