// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsDeviceReport models device report
//
// swagger:model models.DeviceReport
type ModelsDeviceReport struct {

	// anomaly block stat
	AnomalyBlockStat *ModelsAnomalyBlockStat `json:"anomaly_block_stat,omitempty"`

	// detections
	Detections *ModelsDetectionReport `json:"detections,omitempty"`

	// hostname
	Hostname string `json:"hostname,omitempty"`

	// requests
	Requests int64 `json:"requests,omitempty"`

	// traffic
	Traffic *ModelsTraffic `json:"traffic,omitempty"`
}

// Validate validates this models device report
func (m *ModelsDeviceReport) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAnomalyBlockStat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDetections(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTraffic(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsDeviceReport) validateAnomalyBlockStat(formats strfmt.Registry) error {
	if swag.IsZero(m.AnomalyBlockStat) { // not required
		return nil
	}

	if m.AnomalyBlockStat != nil {
		if err := m.AnomalyBlockStat.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("anomaly_block_stat")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("anomaly_block_stat")
			}
			return err
		}
	}

	return nil
}

func (m *ModelsDeviceReport) validateDetections(formats strfmt.Registry) error {
	if swag.IsZero(m.Detections) { // not required
		return nil
	}

	if m.Detections != nil {
		if err := m.Detections.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("detections")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("detections")
			}
			return err
		}
	}

	return nil
}

func (m *ModelsDeviceReport) validateTraffic(formats strfmt.Registry) error {
	if swag.IsZero(m.Traffic) { // not required
		return nil
	}

	if m.Traffic != nil {
		if err := m.Traffic.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("traffic")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("traffic")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this models device report based on the context it is used
func (m *ModelsDeviceReport) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAnomalyBlockStat(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDetections(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTraffic(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsDeviceReport) contextValidateAnomalyBlockStat(ctx context.Context, formats strfmt.Registry) error {

	if m.AnomalyBlockStat != nil {

		if swag.IsZero(m.AnomalyBlockStat) { // not required
			return nil
		}

		if err := m.AnomalyBlockStat.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("anomaly_block_stat")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("anomaly_block_stat")
			}
			return err
		}
	}

	return nil
}

func (m *ModelsDeviceReport) contextValidateDetections(ctx context.Context, formats strfmt.Registry) error {

	if m.Detections != nil {

		if swag.IsZero(m.Detections) { // not required
			return nil
		}

		if err := m.Detections.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("detections")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("detections")
			}
			return err
		}
	}

	return nil
}

func (m *ModelsDeviceReport) contextValidateTraffic(ctx context.Context, formats strfmt.Registry) error {

	if m.Traffic != nil {

		if swag.IsZero(m.Traffic) { // not required
			return nil
		}

		if err := m.Traffic.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("traffic")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("traffic")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelsDeviceReport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsDeviceReport) UnmarshalBinary(b []byte) error {
	var res ModelsDeviceReport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
