// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsAnomaly models anomaly
//
// swagger:model models.Anomaly
type ModelsAnomaly struct {

	// blocked resources count
	BlockedResourcesCount int64 `json:"blocked_resources_count,omitempty"`

	// firewalls count
	FirewallsCount int64 `json:"firewalls_count,omitempty"`

	// stat
	Stat []*ModelsAnomalyResourse `json:"stat"`
}

// Validate validates this models anomaly
func (m *ModelsAnomaly) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStat(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsAnomaly) validateStat(formats strfmt.Registry) error {
	if swag.IsZero(m.Stat) { // not required
		return nil
	}

	for i := 0; i < len(m.Stat); i++ {
		if swag.IsZero(m.Stat[i]) { // not required
			continue
		}

		if m.Stat[i] != nil {
			if err := m.Stat[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("stat" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("stat" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this models anomaly based on the context it is used
func (m *ModelsAnomaly) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStat(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsAnomaly) contextValidateStat(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Stat); i++ {

		if m.Stat[i] != nil {

			if swag.IsZero(m.Stat[i]) { // not required
				return nil
			}

			if err := m.Stat[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("stat" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("stat" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelsAnomaly) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsAnomaly) UnmarshalBinary(b []byte) error {
	var res ModelsAnomaly
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
