// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsBusinessLog models business log
//
// swagger:model models.BusinessLog
type ModelsBusinessLog struct {

	// context
	Context string `json:"context,omitempty"`

	// context str
	ContextStr string `json:"context_str,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// user, context
	Entity string `json:"entity,omitempty"`

	// userID or ContextID
	EntityID string `json:"entity_id,omitempty"`

	// CREATE, UPDATE, DELETE
	EventType string `json:"event_type,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// new value
	NewValue ModelsJSONB `json:"new_value,omitempty"`

	// old value
	OldValue ModelsJSONB `json:"old_value,omitempty"`

	// timestamp
	Timestamp string `json:"timestamp,omitempty"`

	// user name
	UserName string `json:"user_name,omitempty"`

	// SA, CA
	UserRole string `json:"user_role,omitempty"`
}

// Validate validates this models business log
func (m *ModelsBusinessLog) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models business log based on context it is used
func (m *ModelsBusinessLog) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsBusinessLog) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsBusinessLog) UnmarshalBinary(b []byte) error {
	var res ModelsBusinessLog
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
