// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ModelsReportForDevice models report for device
//
// swagger:model models.ReportForDevice
type ModelsReportForDevice struct {

	// anomalies list page
	AnomaliesListPage map[string]ModelsAnomalyStat `json:"anomalies_list_page,omitempty"`

	// categories page
	CategoriesPage map[string]ModelsTopCategory `json:"categories_page,omitempty"`

	// device analytics page
	DeviceAnalyticsPage *ModelsDeviceAnalyticsPage `json:"device_analytics_page,omitempty"`

	// from
	From string `json:"from,omitempty"`

	// host name
	HostName string `json:"host_name,omitempty"`

	// to
	To string `json:"to,omitempty"`
}

// Validate validates this models report for device
func (m *ModelsReportForDevice) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAnomaliesListPage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCategoriesPage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeviceAnalyticsPage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsReportForDevice) validateAnomaliesListPage(formats strfmt.Registry) error {
	if swag.IsZero(m.AnomaliesListPage) { // not required
		return nil
	}

	for k := range m.AnomaliesListPage {

		if err := validate.Required("anomalies_list_page"+"."+k, "body", m.AnomaliesListPage[k]); err != nil {
			return err
		}
		if val, ok := m.AnomaliesListPage[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("anomalies_list_page" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("anomalies_list_page" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

func (m *ModelsReportForDevice) validateCategoriesPage(formats strfmt.Registry) error {
	if swag.IsZero(m.CategoriesPage) { // not required
		return nil
	}

	for k := range m.CategoriesPage {

		if err := validate.Required("categories_page"+"."+k, "body", m.CategoriesPage[k]); err != nil {
			return err
		}
		if val, ok := m.CategoriesPage[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("categories_page" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("categories_page" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

func (m *ModelsReportForDevice) validateDeviceAnalyticsPage(formats strfmt.Registry) error {
	if swag.IsZero(m.DeviceAnalyticsPage) { // not required
		return nil
	}

	if m.DeviceAnalyticsPage != nil {
		if err := m.DeviceAnalyticsPage.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("device_analytics_page")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("device_analytics_page")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this models report for device based on the context it is used
func (m *ModelsReportForDevice) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAnomaliesListPage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCategoriesPage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDeviceAnalyticsPage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsReportForDevice) contextValidateAnomaliesListPage(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.AnomaliesListPage {

		if val, ok := m.AnomaliesListPage[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *ModelsReportForDevice) contextValidateCategoriesPage(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.CategoriesPage {

		if val, ok := m.CategoriesPage[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *ModelsReportForDevice) contextValidateDeviceAnalyticsPage(ctx context.Context, formats strfmt.Registry) error {

	if m.DeviceAnalyticsPage != nil {

		if swag.IsZero(m.DeviceAnalyticsPage) { // not required
			return nil
		}

		if err := m.DeviceAnalyticsPage.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("device_analytics_page")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("device_analytics_page")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelsReportForDevice) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsReportForDevice) UnmarshalBinary(b []byte) error {
	var res ModelsReportForDevice
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
