// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ModelsMainActivityPage models main activity page
//
// swagger:model models.MainActivityPage
type ModelsMainActivityPage struct {

	// top categories
	TopCategories map[string]ModelsRequestReport `json:"top_categories,omitempty"`

	// top resources
	TopResources map[string]ModelsResourceStat `json:"top_resources,omitempty"`

	// traffic
	Traffic *ModelsTrafficStat `json:"traffic,omitempty"`
}

// Validate validates this models main activity page
func (m *ModelsMainActivityPage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTopCategories(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTopResources(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTraffic(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsMainActivityPage) validateTopCategories(formats strfmt.Registry) error {
	if swag.IsZero(m.TopCategories) { // not required
		return nil
	}

	for k := range m.TopCategories {

		if err := validate.Required("top_categories"+"."+k, "body", m.TopCategories[k]); err != nil {
			return err
		}
		if val, ok := m.TopCategories[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("top_categories" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("top_categories" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

func (m *ModelsMainActivityPage) validateTopResources(formats strfmt.Registry) error {
	if swag.IsZero(m.TopResources) { // not required
		return nil
	}

	for k := range m.TopResources {

		if err := validate.Required("top_resources"+"."+k, "body", m.TopResources[k]); err != nil {
			return err
		}
		if val, ok := m.TopResources[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("top_resources" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("top_resources" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

func (m *ModelsMainActivityPage) validateTraffic(formats strfmt.Registry) error {
	if swag.IsZero(m.Traffic) { // not required
		return nil
	}

	if m.Traffic != nil {
		if err := m.Traffic.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("traffic")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("traffic")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this models main activity page based on the context it is used
func (m *ModelsMainActivityPage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTopCategories(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTopResources(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTraffic(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsMainActivityPage) contextValidateTopCategories(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.TopCategories {

		if val, ok := m.TopCategories[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *ModelsMainActivityPage) contextValidateTopResources(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.TopResources {

		if val, ok := m.TopResources[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *ModelsMainActivityPage) contextValidateTraffic(ctx context.Context, formats strfmt.Registry) error {

	if m.Traffic != nil {

		if swag.IsZero(m.Traffic) { // not required
			return nil
		}

		if err := m.Traffic.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("traffic")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("traffic")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelsMainActivityPage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsMainActivityPage) UnmarshalBinary(b []byte) error {
	var res ModelsMainActivityPage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
