// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsTraffic models traffic
//
// swagger:model models.Traffic
type ModelsTraffic struct {

	// input
	Input int64 `json:"input,omitempty"`

	// output
	Output int64 `json:"output,omitempty"`
}

// Validate validates this models traffic
func (m *ModelsTraffic) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models traffic based on context it is used
func (m *ModelsTraffic) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsTraffic) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsTraffic) UnmarshalBinary(b []byte) error {
	var res ModelsTraffic
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
