app:
  name: 'tg-an'
  version: '1.0.0'
  dev_version: ''
  
analytics:
  neg_detection_threshold: 0.5

logger:
  log_level: 'debug'

etl:
  pool_max: 2
  host: "localhost"
  user: "etl"
  pass: "etlpassword"
  dbname: "etl"
  port: "5432"
  sslmode: "disable"

http:
  host: '127.0.0.1'
  port: '7000'

swagger:
  host: '127.0.0.1:7000'

metrics:
  pool_max: 2
  host: "192.168.130.112"
  user: "ksu_user"
  pass: "ksu_password"
  dbname: "ksu_mon"
  port: "5432"
  sslmode: "disable"

blog_serv:
  proto: "http"
  host: "127.0.0.1"
  port: "8004"