// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tg-etl/pkg/models"
)

// GetAPIV1LogsReader is a Reader for the GetAPIV1Logs structure.
type GetAPIV1LogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1LogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1LogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV1LogsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1LogsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/logs] GetAPIV1Logs", response, response.Code())
	}
}

// NewGetAPIV1LogsOK creates a GetAPIV1LogsOK with default headers values
func NewGetAPIV1LogsOK() *GetAPIV1LogsOK {
	return &GetAPIV1LogsOK{}
}

/*
GetAPIV1LogsOK describes a response with status code 200, with default header values.

Отфильтрованные логи
*/
type GetAPIV1LogsOK struct {
	Payload *models.ModelsLogs
}

// IsSuccess returns true when this get Api v1 logs o k response has a 2xx status code
func (o *GetAPIV1LogsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 logs o k response has a 3xx status code
func (o *GetAPIV1LogsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 logs o k response has a 4xx status code
func (o *GetAPIV1LogsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 logs o k response has a 5xx status code
func (o *GetAPIV1LogsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 logs o k response a status code equal to that given
func (o *GetAPIV1LogsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 logs o k response
func (o *GetAPIV1LogsOK) Code() int {
	return 200
}

func (o *GetAPIV1LogsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/logs][%d] getApiV1LogsOK %s", 200, payload)
}

func (o *GetAPIV1LogsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/logs][%d] getApiV1LogsOK %s", 200, payload)
}

func (o *GetAPIV1LogsOK) GetPayload() *models.ModelsLogs {
	return o.Payload
}

func (o *GetAPIV1LogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsLogs)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1LogsBadRequest creates a GetAPIV1LogsBadRequest with default headers values
func NewGetAPIV1LogsBadRequest() *GetAPIV1LogsBadRequest {
	return &GetAPIV1LogsBadRequest{}
}

/*
GetAPIV1LogsBadRequest describes a response with status code 400, with default header values.

query params is not valid
*/
type GetAPIV1LogsBadRequest struct {
	Payload *models.ModelsAPIError
}

// IsSuccess returns true when this get Api v1 logs bad request response has a 2xx status code
func (o *GetAPIV1LogsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 logs bad request response has a 3xx status code
func (o *GetAPIV1LogsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 logs bad request response has a 4xx status code
func (o *GetAPIV1LogsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 logs bad request response has a 5xx status code
func (o *GetAPIV1LogsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 logs bad request response a status code equal to that given
func (o *GetAPIV1LogsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v1 logs bad request response
func (o *GetAPIV1LogsBadRequest) Code() int {
	return 400
}

func (o *GetAPIV1LogsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/logs][%d] getApiV1LogsBadRequest %s", 400, payload)
}

func (o *GetAPIV1LogsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/logs][%d] getApiV1LogsBadRequest %s", 400, payload)
}

func (o *GetAPIV1LogsBadRequest) GetPayload() *models.ModelsAPIError {
	return o.Payload
}

func (o *GetAPIV1LogsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1LogsInternalServerError creates a GetAPIV1LogsInternalServerError with default headers values
func NewGetAPIV1LogsInternalServerError() *GetAPIV1LogsInternalServerError {
	return &GetAPIV1LogsInternalServerError{}
}

/*
GetAPIV1LogsInternalServerError describes a response with status code 500, with default header values.

internal error
*/
type GetAPIV1LogsInternalServerError struct {
	Payload *models.ModelsAPIError
}

// IsSuccess returns true when this get Api v1 logs internal server error response has a 2xx status code
func (o *GetAPIV1LogsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 logs internal server error response has a 3xx status code
func (o *GetAPIV1LogsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 logs internal server error response has a 4xx status code
func (o *GetAPIV1LogsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 logs internal server error response has a 5xx status code
func (o *GetAPIV1LogsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 logs internal server error response a status code equal to that given
func (o *GetAPIV1LogsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 logs internal server error response
func (o *GetAPIV1LogsInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1LogsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/logs][%d] getApiV1LogsInternalServerError %s", 500, payload)
}

func (o *GetAPIV1LogsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/logs][%d] getApiV1LogsInternalServerError %s", 500, payload)
}

func (o *GetAPIV1LogsInternalServerError) GetPayload() *models.ModelsAPIError {
	return o.Payload
}

func (o *GetAPIV1LogsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
