// Code generated by go-swagger; DO NOT EDIT.

package dashboards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"api-gateway/pkg/models"
)

// GetDashboardsTrafficReader is a Reader for the GetDashboardsTraffic structure.
type GetDashboardsTrafficReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDashboardsTrafficReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDashboardsTrafficOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetDashboardsTrafficBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetDashboardsTrafficInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /dashboards/traffic] GetDashboardsTraffic", response, response.Code())
	}
}

// NewGetDashboardsTrafficOK creates a GetDashboardsTrafficOK with default headers values
func NewGetDashboardsTrafficOK() *GetDashboardsTrafficOK {
	return &GetDashboardsTrafficOK{}
}

/*
GetDashboardsTrafficOK describes a response with status code 200, with default header values.

Успешный ответ со статистикой трафика
*/
type GetDashboardsTrafficOK struct {
	Payload *models.DtoTrafficStatResponse
}

// IsSuccess returns true when this get dashboards traffic o k response has a 2xx status code
func (o *GetDashboardsTrafficOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get dashboards traffic o k response has a 3xx status code
func (o *GetDashboardsTrafficOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get dashboards traffic o k response has a 4xx status code
func (o *GetDashboardsTrafficOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get dashboards traffic o k response has a 5xx status code
func (o *GetDashboardsTrafficOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get dashboards traffic o k response a status code equal to that given
func (o *GetDashboardsTrafficOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get dashboards traffic o k response
func (o *GetDashboardsTrafficOK) Code() int {
	return 200
}

func (o *GetDashboardsTrafficOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dashboards/traffic][%d] getDashboardsTrafficOK %s", 200, payload)
}

func (o *GetDashboardsTrafficOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dashboards/traffic][%d] getDashboardsTrafficOK %s", 200, payload)
}

func (o *GetDashboardsTrafficOK) GetPayload() *models.DtoTrafficStatResponse {
	return o.Payload
}

func (o *GetDashboardsTrafficOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoTrafficStatResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDashboardsTrafficBadRequest creates a GetDashboardsTrafficBadRequest with default headers values
func NewGetDashboardsTrafficBadRequest() *GetDashboardsTrafficBadRequest {
	return &GetDashboardsTrafficBadRequest{}
}

/*
GetDashboardsTrafficBadRequest describes a response with status code 400, with default header values.

Неверный формат параметров запроса
*/
type GetDashboardsTrafficBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get dashboards traffic bad request response has a 2xx status code
func (o *GetDashboardsTrafficBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get dashboards traffic bad request response has a 3xx status code
func (o *GetDashboardsTrafficBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get dashboards traffic bad request response has a 4xx status code
func (o *GetDashboardsTrafficBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get dashboards traffic bad request response has a 5xx status code
func (o *GetDashboardsTrafficBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get dashboards traffic bad request response a status code equal to that given
func (o *GetDashboardsTrafficBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get dashboards traffic bad request response
func (o *GetDashboardsTrafficBadRequest) Code() int {
	return 400
}

func (o *GetDashboardsTrafficBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dashboards/traffic][%d] getDashboardsTrafficBadRequest %s", 400, payload)
}

func (o *GetDashboardsTrafficBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dashboards/traffic][%d] getDashboardsTrafficBadRequest %s", 400, payload)
}

func (o *GetDashboardsTrafficBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetDashboardsTrafficBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDashboardsTrafficInternalServerError creates a GetDashboardsTrafficInternalServerError with default headers values
func NewGetDashboardsTrafficInternalServerError() *GetDashboardsTrafficInternalServerError {
	return &GetDashboardsTrafficInternalServerError{}
}

/*
GetDashboardsTrafficInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера при получении статистики
*/
type GetDashboardsTrafficInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get dashboards traffic internal server error response has a 2xx status code
func (o *GetDashboardsTrafficInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get dashboards traffic internal server error response has a 3xx status code
func (o *GetDashboardsTrafficInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get dashboards traffic internal server error response has a 4xx status code
func (o *GetDashboardsTrafficInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get dashboards traffic internal server error response has a 5xx status code
func (o *GetDashboardsTrafficInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get dashboards traffic internal server error response a status code equal to that given
func (o *GetDashboardsTrafficInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get dashboards traffic internal server error response
func (o *GetDashboardsTrafficInternalServerError) Code() int {
	return 500
}

func (o *GetDashboardsTrafficInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dashboards/traffic][%d] getDashboardsTrafficInternalServerError %s", 500, payload)
}

func (o *GetDashboardsTrafficInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dashboards/traffic][%d] getDashboardsTrafficInternalServerError %s", 500, payload)
}

func (o *GetDashboardsTrafficInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetDashboardsTrafficInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
