// Code generated by go-swagger; DO NOT EDIT.

package dashboards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV1DashboardsTrafficParams creates a new GetAPIV1DashboardsTrafficParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1DashboardsTrafficParams() *GetAPIV1DashboardsTrafficParams {
	return &GetAPIV1DashboardsTrafficParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1DashboardsTrafficParamsWithTimeout creates a new GetAPIV1DashboardsTrafficParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1DashboardsTrafficParamsWithTimeout(timeout time.Duration) *GetAPIV1DashboardsTrafficParams {
	return &GetAPIV1DashboardsTrafficParams{
		timeout: timeout,
	}
}

// NewGetAPIV1DashboardsTrafficParamsWithContext creates a new GetAPIV1DashboardsTrafficParams object
// with the ability to set a context for a request.
func NewGetAPIV1DashboardsTrafficParamsWithContext(ctx context.Context) *GetAPIV1DashboardsTrafficParams {
	return &GetAPIV1DashboardsTrafficParams{
		Context: ctx,
	}
}

// NewGetAPIV1DashboardsTrafficParamsWithHTTPClient creates a new GetAPIV1DashboardsTrafficParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1DashboardsTrafficParamsWithHTTPClient(client *http.Client) *GetAPIV1DashboardsTrafficParams {
	return &GetAPIV1DashboardsTrafficParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1DashboardsTrafficParams contains all the parameters to send to the API endpoint

	for the get API v1 dashboards traffic operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1DashboardsTrafficParams struct {

	/* Count.

	   Количество точек данных для возврата (по умолчанию 20)

	   Default: 20
	*/
	Count *int64

	/* From.

	   Начало временного диапазона в формате парсера времени (по умолчанию now-10m)

	   Default: "now-10m"
	*/
	From *string

	/* To.

	   Конец временного диапазона в формате парсера времени (по умолчанию now)

	   Default: "now"
	*/
	To *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 dashboards traffic params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1DashboardsTrafficParams) WithDefaults() *GetAPIV1DashboardsTrafficParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 dashboards traffic params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1DashboardsTrafficParams) SetDefaults() {
	var (
		countDefault = int64(20)

		fromDefault = string("now-10m")

		toDefault = string("now")
	)

	val := GetAPIV1DashboardsTrafficParams{
		Count: &countDefault,
		From:  &fromDefault,
		To:    &toDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get API v1 dashboards traffic params
func (o *GetAPIV1DashboardsTrafficParams) WithTimeout(timeout time.Duration) *GetAPIV1DashboardsTrafficParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 dashboards traffic params
func (o *GetAPIV1DashboardsTrafficParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 dashboards traffic params
func (o *GetAPIV1DashboardsTrafficParams) WithContext(ctx context.Context) *GetAPIV1DashboardsTrafficParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 dashboards traffic params
func (o *GetAPIV1DashboardsTrafficParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 dashboards traffic params
func (o *GetAPIV1DashboardsTrafficParams) WithHTTPClient(client *http.Client) *GetAPIV1DashboardsTrafficParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 dashboards traffic params
func (o *GetAPIV1DashboardsTrafficParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCount adds the count to the get API v1 dashboards traffic params
func (o *GetAPIV1DashboardsTrafficParams) WithCount(count *int64) *GetAPIV1DashboardsTrafficParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the get API v1 dashboards traffic params
func (o *GetAPIV1DashboardsTrafficParams) SetCount(count *int64) {
	o.Count = count
}

// WithFrom adds the from to the get API v1 dashboards traffic params
func (o *GetAPIV1DashboardsTrafficParams) WithFrom(from *string) *GetAPIV1DashboardsTrafficParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the get API v1 dashboards traffic params
func (o *GetAPIV1DashboardsTrafficParams) SetFrom(from *string) {
	o.From = from
}

// WithTo adds the to to the get API v1 dashboards traffic params
func (o *GetAPIV1DashboardsTrafficParams) WithTo(to *string) *GetAPIV1DashboardsTrafficParams {
	o.SetTo(to)
	return o
}

// SetTo adds the to to the get API v1 dashboards traffic params
func (o *GetAPIV1DashboardsTrafficParams) SetTo(to *string) {
	o.To = to
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1DashboardsTrafficParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Count != nil {

		// query param count
		var qrCount int64

		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := swag.FormatInt64(qrCount)
		if qCount != "" {

			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}
	}

	if o.From != nil {

		// query param from
		var qrFrom string

		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := qrFrom
		if qFrom != "" {

			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}
	}

	if o.To != nil {

		// query param to
		var qrTo string

		if o.To != nil {
			qrTo = *o.To
		}
		qTo := qrTo
		if qTo != "" {

			if err := r.SetQueryParam("to", qTo); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
