// Code generated by go-swagger; DO NOT EDIT.

package dashboards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV1DashboardsTopUnresolvedDetectionsParams creates a new GetAPIV1DashboardsTopUnresolvedDetectionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1DashboardsTopUnresolvedDetectionsParams() *GetAPIV1DashboardsTopUnresolvedDetectionsParams {
	return &GetAPIV1DashboardsTopUnresolvedDetectionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1DashboardsTopUnresolvedDetectionsParamsWithTimeout creates a new GetAPIV1DashboardsTopUnresolvedDetectionsParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1DashboardsTopUnresolvedDetectionsParamsWithTimeout(timeout time.Duration) *GetAPIV1DashboardsTopUnresolvedDetectionsParams {
	return &GetAPIV1DashboardsTopUnresolvedDetectionsParams{
		timeout: timeout,
	}
}

// NewGetAPIV1DashboardsTopUnresolvedDetectionsParamsWithContext creates a new GetAPIV1DashboardsTopUnresolvedDetectionsParams object
// with the ability to set a context for a request.
func NewGetAPIV1DashboardsTopUnresolvedDetectionsParamsWithContext(ctx context.Context) *GetAPIV1DashboardsTopUnresolvedDetectionsParams {
	return &GetAPIV1DashboardsTopUnresolvedDetectionsParams{
		Context: ctx,
	}
}

// NewGetAPIV1DashboardsTopUnresolvedDetectionsParamsWithHTTPClient creates a new GetAPIV1DashboardsTopUnresolvedDetectionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1DashboardsTopUnresolvedDetectionsParamsWithHTTPClient(client *http.Client) *GetAPIV1DashboardsTopUnresolvedDetectionsParams {
	return &GetAPIV1DashboardsTopUnresolvedDetectionsParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1DashboardsTopUnresolvedDetectionsParams contains all the parameters to send to the API endpoint

	for the get API v1 dashboards top unresolved detections operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1DashboardsTopUnresolvedDetectionsParams struct {

	/* Count.

	   Количество возвращаемых записей

	   Default: 5
	*/
	Count *int64

	/* From.

	   Начало временного диапазона (формат: now-10m, 2023-12-01T10:00:00Z)

	   Default: "now-10m"
	*/
	From *string

	/* Hostname.

	   Фильтр по имени хоста
	*/
	Hostname *string

	/* To.

	   Конец временного диапазона (формат: now, 2023-12-01T12:00:00Z)

	   Default: "now"
	*/
	To *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 dashboards top unresolved detections params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1DashboardsTopUnresolvedDetectionsParams) WithDefaults() *GetAPIV1DashboardsTopUnresolvedDetectionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 dashboards top unresolved detections params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1DashboardsTopUnresolvedDetectionsParams) SetDefaults() {
	var (
		countDefault = int64(5)

		fromDefault = string("now-10m")

		toDefault = string("now")
	)

	val := GetAPIV1DashboardsTopUnresolvedDetectionsParams{
		Count: &countDefault,
		From:  &fromDefault,
		To:    &toDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get API v1 dashboards top unresolved detections params
func (o *GetAPIV1DashboardsTopUnresolvedDetectionsParams) WithTimeout(timeout time.Duration) *GetAPIV1DashboardsTopUnresolvedDetectionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 dashboards top unresolved detections params
func (o *GetAPIV1DashboardsTopUnresolvedDetectionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 dashboards top unresolved detections params
func (o *GetAPIV1DashboardsTopUnresolvedDetectionsParams) WithContext(ctx context.Context) *GetAPIV1DashboardsTopUnresolvedDetectionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 dashboards top unresolved detections params
func (o *GetAPIV1DashboardsTopUnresolvedDetectionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 dashboards top unresolved detections params
func (o *GetAPIV1DashboardsTopUnresolvedDetectionsParams) WithHTTPClient(client *http.Client) *GetAPIV1DashboardsTopUnresolvedDetectionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 dashboards top unresolved detections params
func (o *GetAPIV1DashboardsTopUnresolvedDetectionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCount adds the count to the get API v1 dashboards top unresolved detections params
func (o *GetAPIV1DashboardsTopUnresolvedDetectionsParams) WithCount(count *int64) *GetAPIV1DashboardsTopUnresolvedDetectionsParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the get API v1 dashboards top unresolved detections params
func (o *GetAPIV1DashboardsTopUnresolvedDetectionsParams) SetCount(count *int64) {
	o.Count = count
}

// WithFrom adds the from to the get API v1 dashboards top unresolved detections params
func (o *GetAPIV1DashboardsTopUnresolvedDetectionsParams) WithFrom(from *string) *GetAPIV1DashboardsTopUnresolvedDetectionsParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the get API v1 dashboards top unresolved detections params
func (o *GetAPIV1DashboardsTopUnresolvedDetectionsParams) SetFrom(from *string) {
	o.From = from
}

// WithHostname adds the hostname to the get API v1 dashboards top unresolved detections params
func (o *GetAPIV1DashboardsTopUnresolvedDetectionsParams) WithHostname(hostname *string) *GetAPIV1DashboardsTopUnresolvedDetectionsParams {
	o.SetHostname(hostname)
	return o
}

// SetHostname adds the hostname to the get API v1 dashboards top unresolved detections params
func (o *GetAPIV1DashboardsTopUnresolvedDetectionsParams) SetHostname(hostname *string) {
	o.Hostname = hostname
}

// WithTo adds the to to the get API v1 dashboards top unresolved detections params
func (o *GetAPIV1DashboardsTopUnresolvedDetectionsParams) WithTo(to *string) *GetAPIV1DashboardsTopUnresolvedDetectionsParams {
	o.SetTo(to)
	return o
}

// SetTo adds the to to the get API v1 dashboards top unresolved detections params
func (o *GetAPIV1DashboardsTopUnresolvedDetectionsParams) SetTo(to *string) {
	o.To = to
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1DashboardsTopUnresolvedDetectionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Count != nil {

		// query param count
		var qrCount int64

		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := swag.FormatInt64(qrCount)
		if qCount != "" {

			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}
	}

	if o.From != nil {

		// query param from
		var qrFrom string

		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := qrFrom
		if qFrom != "" {

			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}
	}

	if o.Hostname != nil {

		// query param hostname
		var qrHostname string

		if o.Hostname != nil {
			qrHostname = *o.Hostname
		}
		qHostname := qrHostname
		if qHostname != "" {

			if err := r.SetQueryParam("hostname", qHostname); err != nil {
				return err
			}
		}
	}

	if o.To != nil {

		// query param to
		var qrTo string

		if o.To != nil {
			qrTo = *o.To
		}
		qTo := qrTo
		if qTo != "" {

			if err := r.SetQueryParam("to", qTo); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
