// Code generated by go-swagger; DO NOT EDIT.

package dashboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tg-dbd/pkg/models"
)

// GetV1DashboardsEventsReader is a Reader for the GetV1DashboardsEvents structure.
type GetV1DashboardsEventsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1DashboardsEventsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1DashboardsEventsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetV1DashboardsEventsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetV1DashboardsEventsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/dashboards/events] GetV1DashboardsEvents", response, response.Code())
	}
}

// NewGetV1DashboardsEventsOK creates a GetV1DashboardsEventsOK with default headers values
func NewGetV1DashboardsEventsOK() *GetV1DashboardsEventsOK {
	return &GetV1DashboardsEventsOK{}
}

/*
GetV1DashboardsEventsOK describes a response with status code 200, with default header values.

Список уведомлений
*/
type GetV1DashboardsEventsOK struct {
	Payload []*models.ModelsNotification
}

// IsSuccess returns true when this get v1 dashboards events o k response has a 2xx status code
func (o *GetV1DashboardsEventsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 dashboards events o k response has a 3xx status code
func (o *GetV1DashboardsEventsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 dashboards events o k response has a 4xx status code
func (o *GetV1DashboardsEventsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 dashboards events o k response has a 5xx status code
func (o *GetV1DashboardsEventsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 dashboards events o k response a status code equal to that given
func (o *GetV1DashboardsEventsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 dashboards events o k response
func (o *GetV1DashboardsEventsOK) Code() int {
	return 200
}

func (o *GetV1DashboardsEventsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/dashboards/events][%d] getV1DashboardsEventsOK %s", 200, payload)
}

func (o *GetV1DashboardsEventsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/dashboards/events][%d] getV1DashboardsEventsOK %s", 200, payload)
}

func (o *GetV1DashboardsEventsOK) GetPayload() []*models.ModelsNotification {
	return o.Payload
}

func (o *GetV1DashboardsEventsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1DashboardsEventsBadRequest creates a GetV1DashboardsEventsBadRequest with default headers values
func NewGetV1DashboardsEventsBadRequest() *GetV1DashboardsEventsBadRequest {
	return &GetV1DashboardsEventsBadRequest{}
}

/*
GetV1DashboardsEventsBadRequest describes a response with status code 400, with default header values.

Неверный формат параметров
*/
type GetV1DashboardsEventsBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 dashboards events bad request response has a 2xx status code
func (o *GetV1DashboardsEventsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 dashboards events bad request response has a 3xx status code
func (o *GetV1DashboardsEventsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 dashboards events bad request response has a 4xx status code
func (o *GetV1DashboardsEventsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 dashboards events bad request response has a 5xx status code
func (o *GetV1DashboardsEventsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 dashboards events bad request response a status code equal to that given
func (o *GetV1DashboardsEventsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get v1 dashboards events bad request response
func (o *GetV1DashboardsEventsBadRequest) Code() int {
	return 400
}

func (o *GetV1DashboardsEventsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/dashboards/events][%d] getV1DashboardsEventsBadRequest %s", 400, payload)
}

func (o *GetV1DashboardsEventsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/dashboards/events][%d] getV1DashboardsEventsBadRequest %s", 400, payload)
}

func (o *GetV1DashboardsEventsBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1DashboardsEventsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1DashboardsEventsInternalServerError creates a GetV1DashboardsEventsInternalServerError with default headers values
func NewGetV1DashboardsEventsInternalServerError() *GetV1DashboardsEventsInternalServerError {
	return &GetV1DashboardsEventsInternalServerError{}
}

/*
GetV1DashboardsEventsInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера
*/
type GetV1DashboardsEventsInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 dashboards events internal server error response has a 2xx status code
func (o *GetV1DashboardsEventsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 dashboards events internal server error response has a 3xx status code
func (o *GetV1DashboardsEventsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 dashboards events internal server error response has a 4xx status code
func (o *GetV1DashboardsEventsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 dashboards events internal server error response has a 5xx status code
func (o *GetV1DashboardsEventsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get v1 dashboards events internal server error response a status code equal to that given
func (o *GetV1DashboardsEventsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get v1 dashboards events internal server error response
func (o *GetV1DashboardsEventsInternalServerError) Code() int {
	return 500
}

func (o *GetV1DashboardsEventsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/dashboards/events][%d] getV1DashboardsEventsInternalServerError %s", 500, payload)
}

func (o *GetV1DashboardsEventsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/dashboards/events][%d] getV1DashboardsEventsInternalServerError %s", 500, payload)
}

func (o *GetV1DashboardsEventsInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1DashboardsEventsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
