// Code generated by go-swagger; DO NOT EDIT.

package dashboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetV1DashboardsTrafficParams creates a new GetV1DashboardsTrafficParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1DashboardsTrafficParams() *GetV1DashboardsTrafficParams {
	return &GetV1DashboardsTrafficParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1DashboardsTrafficParamsWithTimeout creates a new GetV1DashboardsTrafficParams object
// with the ability to set a timeout on a request.
func NewGetV1DashboardsTrafficParamsWithTimeout(timeout time.Duration) *GetV1DashboardsTrafficParams {
	return &GetV1DashboardsTrafficParams{
		timeout: timeout,
	}
}

// NewGetV1DashboardsTrafficParamsWithContext creates a new GetV1DashboardsTrafficParams object
// with the ability to set a context for a request.
func NewGetV1DashboardsTrafficParamsWithContext(ctx context.Context) *GetV1DashboardsTrafficParams {
	return &GetV1DashboardsTrafficParams{
		Context: ctx,
	}
}

// NewGetV1DashboardsTrafficParamsWithHTTPClient creates a new GetV1DashboardsTrafficParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1DashboardsTrafficParamsWithHTTPClient(client *http.Client) *GetV1DashboardsTrafficParams {
	return &GetV1DashboardsTrafficParams{
		HTTPClient: client,
	}
}

/*
GetV1DashboardsTrafficParams contains all the parameters to send to the API endpoint

	for the get v1 dashboards traffic operation.

	Typically these are written to a http.Request.
*/
type GetV1DashboardsTrafficParams struct {

	/* End.

	   Конец периода в timestamp
	*/
	End int64

	/* Start.

	   Начало периода в timestamp
	*/
	Start int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 dashboards traffic params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1DashboardsTrafficParams) WithDefaults() *GetV1DashboardsTrafficParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 dashboards traffic params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1DashboardsTrafficParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 dashboards traffic params
func (o *GetV1DashboardsTrafficParams) WithTimeout(timeout time.Duration) *GetV1DashboardsTrafficParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 dashboards traffic params
func (o *GetV1DashboardsTrafficParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 dashboards traffic params
func (o *GetV1DashboardsTrafficParams) WithContext(ctx context.Context) *GetV1DashboardsTrafficParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 dashboards traffic params
func (o *GetV1DashboardsTrafficParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 dashboards traffic params
func (o *GetV1DashboardsTrafficParams) WithHTTPClient(client *http.Client) *GetV1DashboardsTrafficParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 dashboards traffic params
func (o *GetV1DashboardsTrafficParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnd adds the end to the get v1 dashboards traffic params
func (o *GetV1DashboardsTrafficParams) WithEnd(end int64) *GetV1DashboardsTrafficParams {
	o.SetEnd(end)
	return o
}

// SetEnd adds the end to the get v1 dashboards traffic params
func (o *GetV1DashboardsTrafficParams) SetEnd(end int64) {
	o.End = end
}

// WithStart adds the start to the get v1 dashboards traffic params
func (o *GetV1DashboardsTrafficParams) WithStart(start int64) *GetV1DashboardsTrafficParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the get v1 dashboards traffic params
func (o *GetV1DashboardsTrafficParams) SetStart(start int64) {
	o.Start = start
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1DashboardsTrafficParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param end
	qrEnd := o.End
	qEnd := swag.FormatInt64(qrEnd)
	if qEnd != "" {

		if err := r.SetQueryParam("end", qEnd); err != nil {
			return err
		}
	}

	// query param start
	qrStart := o.Start
	qStart := swag.FormatInt64(qrStart)
	if qStart != "" {

		if err := r.SetQueryParam("start", qStart); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
