// Code generated by go-swagger; DO NOT EDIT.

package utils

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"userctrl/pkg/blog/models"
)

// GetAPIV1VersionReader is a Reader for the GetAPIV1Version structure.
type GetAPIV1VersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1VersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1VersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/version] GetAPIV1Version", response, response.Code())
	}
}

// NewGetAPIV1VersionOK creates a GetAPIV1VersionOK with default headers values
func NewGetAPIV1VersionOK() *GetAPIV1VersionOK {
	return &GetAPIV1VersionOK{}
}

/*
GetAPIV1VersionOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1VersionOK struct {
	Payload *models.DtoSuccessResponse
}

// IsSuccess returns true when this get Api v1 version o k response has a 2xx status code
func (o *GetAPIV1VersionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 version o k response has a 3xx status code
func (o *GetAPIV1VersionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 version o k response has a 4xx status code
func (o *GetAPIV1VersionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 version o k response has a 5xx status code
func (o *GetAPIV1VersionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 version o k response a status code equal to that given
func (o *GetAPIV1VersionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 version o k response
func (o *GetAPIV1VersionOK) Code() int {
	return 200
}

func (o *GetAPIV1VersionOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/version][%d] getApiV1VersionOK %s", 200, payload)
}

func (o *GetAPIV1VersionOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/version][%d] getApiV1VersionOK %s", 200, payload)
}

func (o *GetAPIV1VersionOK) GetPayload() *models.DtoSuccessResponse {
	return o.Payload
}

func (o *GetAPIV1VersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoSuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
