// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetV1RolesParams creates a new GetV1RolesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1RolesParams() *GetV1RolesParams {
	return &GetV1RolesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1RolesParamsWithTimeout creates a new GetV1RolesParams object
// with the ability to set a timeout on a request.
func NewGetV1RolesParamsWithTimeout(timeout time.Duration) *GetV1RolesParams {
	return &GetV1RolesParams{
		timeout: timeout,
	}
}

// NewGetV1RolesParamsWithContext creates a new GetV1RolesParams object
// with the ability to set a context for a request.
func NewGetV1RolesParamsWithContext(ctx context.Context) *GetV1RolesParams {
	return &GetV1RolesParams{
		Context: ctx,
	}
}

// NewGetV1RolesParamsWithHTTPClient creates a new GetV1RolesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1RolesParamsWithHTTPClient(client *http.Client) *GetV1RolesParams {
	return &GetV1RolesParams{
		HTTPClient: client,
	}
}

/*
GetV1RolesParams contains all the parameters to send to the API endpoint

	for the get v1 roles operation.

	Typically these are written to a http.Request.
*/
type GetV1RolesParams struct {

	/* Limit.

	   Количество элементов на странице

	   Default: 10
	*/
	Limit *int64

	/* Page.

	   Номер страницы

	   Default: 1
	*/
	Page *int64

	/* Search.

	   Поиск по названию роли
	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 roles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1RolesParams) WithDefaults() *GetV1RolesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 roles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1RolesParams) SetDefaults() {
	var (
		limitDefault = int64(10)

		pageDefault = int64(1)
	)

	val := GetV1RolesParams{
		Limit: &limitDefault,
		Page:  &pageDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get v1 roles params
func (o *GetV1RolesParams) WithTimeout(timeout time.Duration) *GetV1RolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 roles params
func (o *GetV1RolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 roles params
func (o *GetV1RolesParams) WithContext(ctx context.Context) *GetV1RolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 roles params
func (o *GetV1RolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 roles params
func (o *GetV1RolesParams) WithHTTPClient(client *http.Client) *GetV1RolesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 roles params
func (o *GetV1RolesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get v1 roles params
func (o *GetV1RolesParams) WithLimit(limit *int64) *GetV1RolesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get v1 roles params
func (o *GetV1RolesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithPage adds the page to the get v1 roles params
func (o *GetV1RolesParams) WithPage(page *int64) *GetV1RolesParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get v1 roles params
func (o *GetV1RolesParams) SetPage(page *int64) {
	o.Page = page
}

// WithSearch adds the search to the get v1 roles params
func (o *GetV1RolesParams) WithSearch(search *string) *GetV1RolesParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the get v1 roles params
func (o *GetV1RolesParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1RolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.Search != nil {

		// query param search
		var qrSearch string

		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {

			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
