// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tg-etl/pkg/models"
)

// GetV1RolesReader is a Reader for the GetV1Roles structure.
type GetV1RolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1RolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1RolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetV1RolesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetV1RolesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetV1RolesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetV1RolesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/roles] GetV1Roles", response, response.Code())
	}
}

// NewGetV1RolesOK creates a GetV1RolesOK with default headers values
func NewGetV1RolesOK() *GetV1RolesOK {
	return &GetV1RolesOK{}
}

/*
GetV1RolesOK describes a response with status code 200, with default header values.

OK
*/
type GetV1RolesOK struct {
	Payload *models.DtoRolesListResponse
}

// IsSuccess returns true when this get v1 roles o k response has a 2xx status code
func (o *GetV1RolesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 roles o k response has a 3xx status code
func (o *GetV1RolesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 roles o k response has a 4xx status code
func (o *GetV1RolesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 roles o k response has a 5xx status code
func (o *GetV1RolesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 roles o k response a status code equal to that given
func (o *GetV1RolesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 roles o k response
func (o *GetV1RolesOK) Code() int {
	return 200
}

func (o *GetV1RolesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/roles][%d] getV1RolesOK %s", 200, payload)
}

func (o *GetV1RolesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/roles][%d] getV1RolesOK %s", 200, payload)
}

func (o *GetV1RolesOK) GetPayload() *models.DtoRolesListResponse {
	return o.Payload
}

func (o *GetV1RolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoRolesListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1RolesBadRequest creates a GetV1RolesBadRequest with default headers values
func NewGetV1RolesBadRequest() *GetV1RolesBadRequest {
	return &GetV1RolesBadRequest{}
}

/*
GetV1RolesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetV1RolesBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 roles bad request response has a 2xx status code
func (o *GetV1RolesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 roles bad request response has a 3xx status code
func (o *GetV1RolesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 roles bad request response has a 4xx status code
func (o *GetV1RolesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 roles bad request response has a 5xx status code
func (o *GetV1RolesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 roles bad request response a status code equal to that given
func (o *GetV1RolesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get v1 roles bad request response
func (o *GetV1RolesBadRequest) Code() int {
	return 400
}

func (o *GetV1RolesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/roles][%d] getV1RolesBadRequest %s", 400, payload)
}

func (o *GetV1RolesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/roles][%d] getV1RolesBadRequest %s", 400, payload)
}

func (o *GetV1RolesBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1RolesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1RolesUnauthorized creates a GetV1RolesUnauthorized with default headers values
func NewGetV1RolesUnauthorized() *GetV1RolesUnauthorized {
	return &GetV1RolesUnauthorized{}
}

/*
GetV1RolesUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetV1RolesUnauthorized struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 roles unauthorized response has a 2xx status code
func (o *GetV1RolesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 roles unauthorized response has a 3xx status code
func (o *GetV1RolesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 roles unauthorized response has a 4xx status code
func (o *GetV1RolesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 roles unauthorized response has a 5xx status code
func (o *GetV1RolesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 roles unauthorized response a status code equal to that given
func (o *GetV1RolesUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get v1 roles unauthorized response
func (o *GetV1RolesUnauthorized) Code() int {
	return 401
}

func (o *GetV1RolesUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/roles][%d] getV1RolesUnauthorized %s", 401, payload)
}

func (o *GetV1RolesUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/roles][%d] getV1RolesUnauthorized %s", 401, payload)
}

func (o *GetV1RolesUnauthorized) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1RolesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1RolesForbidden creates a GetV1RolesForbidden with default headers values
func NewGetV1RolesForbidden() *GetV1RolesForbidden {
	return &GetV1RolesForbidden{}
}

/*
GetV1RolesForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetV1RolesForbidden struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 roles forbidden response has a 2xx status code
func (o *GetV1RolesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 roles forbidden response has a 3xx status code
func (o *GetV1RolesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 roles forbidden response has a 4xx status code
func (o *GetV1RolesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 roles forbidden response has a 5xx status code
func (o *GetV1RolesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 roles forbidden response a status code equal to that given
func (o *GetV1RolesForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get v1 roles forbidden response
func (o *GetV1RolesForbidden) Code() int {
	return 403
}

func (o *GetV1RolesForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/roles][%d] getV1RolesForbidden %s", 403, payload)
}

func (o *GetV1RolesForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/roles][%d] getV1RolesForbidden %s", 403, payload)
}

func (o *GetV1RolesForbidden) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1RolesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1RolesInternalServerError creates a GetV1RolesInternalServerError with default headers values
func NewGetV1RolesInternalServerError() *GetV1RolesInternalServerError {
	return &GetV1RolesInternalServerError{}
}

/*
GetV1RolesInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetV1RolesInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 roles internal server error response has a 2xx status code
func (o *GetV1RolesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 roles internal server error response has a 3xx status code
func (o *GetV1RolesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 roles internal server error response has a 4xx status code
func (o *GetV1RolesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 roles internal server error response has a 5xx status code
func (o *GetV1RolesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get v1 roles internal server error response a status code equal to that given
func (o *GetV1RolesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get v1 roles internal server error response
func (o *GetV1RolesInternalServerError) Code() int {
	return 500
}

func (o *GetV1RolesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/roles][%d] getV1RolesInternalServerError %s", 500, payload)
}

func (o *GetV1RolesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/roles][%d] getV1RolesInternalServerError %s", 500, payload)
}

func (o *GetV1RolesInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1RolesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
