app:
  name: 'tg-etl'
  version: '1.0.1'

logger:
  log_level: 'debug'

postgres:
  pool_max: 2
  host: "localhost"
  user: "etl"
  pass: "etlpassword"
  dbname: "etl"
  port: "5432"
  sslmode: "disable"

