definitions:
  dto.ErrorResponse:
    properties:
      error:
        description: Описание ошибки
        type: string
    type: object
  dto.PaginationMeta:
    properties:
      limit:
        description: Количество элементов на странице
        type: integer
      page:
        description: Текущая страница (начинается с 1)
        type: integer
      pages:
        description: Общее количество страниц
        type: integer
      total:
        description: Общее количество элементов
        type: integer
    type: object
  dto.SessionListResponse:
    properties:
      data:
        description: Список контекстов
        items:
          $ref: '#/definitions/models.Session'
        type: array
      meta:
        allOf:
        - $ref: '#/definitions/dto.PaginationMeta'
        description: Метаданные пагинации
    type: object
  dto.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  models.Anomaly:
    properties:
      blocked_resources_count:
        type: integer
      firewalls_count:
        type: integer
      stat:
        items:
          $ref: '#/definitions/models.AnomalyResourse'
        type: array
    type: object
  models.AnomalyResourse:
    properties:
      resourse_name:
        type: string
      unblocked_requests:
        type: integer
    type: object
  models.Detection:
    properties:
      accessCount:
        type: integer
      action:
        type: string
      category:
        type: string
      dateTime:
        type: string
      description:
        type: string
      host:
        type: string
      ngfw:
        type: string
      url:
        type: string
    type: object
  models.DetectionStat:
    properties:
      accepted:
        type: integer
      denied:
        type: integer
      detected:
        type: integer
      unresolved:
        type: integer
    type: object
  models.DeviceStat:
    properties:
      name:
        type: string
      state:
        type: string
      statistics:
        items:
          $ref: '#/definitions/models.ResourcePoint'
        type: array
    type: object
  models.Notification:
    properties:
      dateTime:
        type: string
      description:
        type: string
      username:
        type: string
    type: object
  models.RequestPoint:
    properties:
      count:
        type: integer
      date:
        type: integer
    type: object
  models.RequestsStat:
    properties:
      accepted:
        items:
          $ref: '#/definitions/models.RequestPoint'
        type: array
      before_blocked:
        items:
          $ref: '#/definitions/models.RequestPoint'
        type: array
      blocked:
        items:
          $ref: '#/definitions/models.RequestPoint'
        type: array
      delayed:
        items:
          $ref: '#/definitions/models.RequestPoint'
        type: array
    type: object
  models.ResourcePoint:
    properties:
      date:
        type: integer
      delayed:
        type: integer
      locked:
        type: integer
    type: object
  models.Session:
    properties:
      category:
        type: string
      dateTime:
        type: string
      ip:
        type: string
      ngfw:
        type: string
      sessionType:
        type: string
      status:
        type: string
      url:
        type: string
      username:
        type: string
    type: object
  models.TrafficPoint:
    properties:
      date:
        type: integer
      input:
        type: integer
      output:
        type: integer
    type: object
info:
  contact: {}
paths:
  /v1/dashboards/anomalies:
    get:
      description: Получение списка обнаруженных аномалий в сетевом трафике за указанный
        период
      parameters:
      - description: Начало периода в timestamp
        in: query
        name: start
        required: true
        type: integer
      - description: Конец периода в timestamp
        in: query
        name: end
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Список обнаруженных аномалий
          schema:
            items:
              $ref: '#/definitions/models.Anomaly'
            type: array
        "400":
          description: Неверный формат параметров
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Получение информации об аномалиях
      tags:
      - dashboard
  /v1/dashboards/categories:
    get:
      description: Получение топ категорий с указанием количества обращений за указанный
        период
      parameters:
      - description: Начало периода в timestamp
        in: query
        name: start
        required: true
        type: integer
      - description: Конец периода в timestamp
        in: query
        name: end
        required: true
        type: integer
      - description: Количество возвращаемых категорий (по умолчанию 5)
        in: query
        name: count
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: JSON объект, где ключ - название категории, значение - количество
            обращений
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Неверный формат параметров
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Получение списка категорий
      tags:
      - dashboard
  /v1/dashboards/devices:
    get:
      description: Получение агрегированной статистики по сетевым узлам за указанный
        период
      parameters:
      - description: Начало периода в timestamp
        in: query
        name: start
        required: true
        type: integer
      - description: Конец периода в timestamp
        in: query
        name: end
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Статистика по устройствам
          schema:
            $ref: '#/definitions/models.DeviceStat'
        "400":
          description: Неверный формат параметров
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Получение статистики по устройствам
      tags:
      - dashboard
  /v1/dashboards/events:
    get:
      description: Получение списка уведомлений системы безопасности за указанный
        период
      parameters:
      - description: Начало периода в timestamp
        in: query
        name: start
        required: true
        type: integer
      - description: Конец периода в timestamp
        in: query
        name: end
        required: true
        type: integer
      - description: Количество возвращаемых уведомлений (по умолчанию 5)
        in: query
        name: count
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Список уведомлений
          schema:
            items:
              $ref: '#/definitions/models.Notification'
            type: array
        "400":
          description: Неверный формат параметров
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Получение списка уведомлений
      tags:
      - dashboard
  /v1/dashboards/proh_activity:
    get:
      description: Получение расписания запрещенной активности начиная с указанной
        даты
      parameters:
      - description: Дата начала в timestamp
        in: query
        name: start
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: График запрещенной активности
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Неверный формат параметров
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Получение графика запрещенной активности
      tags:
      - dashboard
  /v1/dashboards/requests:
    get:
      description: Получение агрегированной статистики по HTTP-запросам за указанный
        период
      parameters:
      - description: Начало периода в timestamp
        in: query
        name: start
        required: true
        type: integer
      - description: Конец периода в timestamp
        in: query
        name: end
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Статистика HTTP-запросов
          schema:
            $ref: '#/definitions/models.RequestsStat'
        "400":
          description: Неверный формат параметров
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Получение статистики HTTP-запросов
      tags:
      - dashboard
  /v1/dashboards/resources:
    get:
      description: Получение топ ресурсов с указанием количества обращений за указанный
        период
      parameters:
      - description: Начало периода в timestamp
        in: query
        name: start
        required: true
        type: integer
      - description: Конец периода в timestamp
        in: query
        name: end
        required: true
        type: integer
      - description: Количество возвращаемых ресурсов (по умолчанию 5)
        in: query
        name: count
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: JSON объект, где ключ - URL ресурса, значение - количество
            обращений
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Неверный формат параметров
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Получение списка популярных ресурсов
      tags:
      - dashboard
  /v1/dashboards/traffic:
    get:
      description: Получение агрегированной статистики по сетевому трафику за указанный
        период
      parameters:
      - description: Начало периода в timestamp
        in: query
        name: start
        required: true
        type: integer
      - description: Конец периода в timestamp
        in: query
        name: end
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Статистика сетевого трафика
          schema:
            items:
              $ref: '#/definitions/models.TrafficPoint'
            type: array
        "400":
          description: Неверный формат параметров
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Получение статистики сетевого трафика
      tags:
      - dashboard
  /v1/detections:
    get:
      description: Получение списка обнаружений с фильтрацией по дате
      parameters:
      - description: Начало периода в timestamp
        in: query
        name: start
        required: true
        type: integer
      - description: Конец периода в timestamp
        in: query
        name: end
        required: true
        type: integer
      - description: Количество записей (по умолчанию 5)
        in: query
        name: count
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Detection'
        "400":
          description: Неверный формат параметров
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Получение информации об обнаружениях
      tags:
      - detection
  /v1/detections/stat:
    get:
      description: Получение агрегированной статистики обнаружений за указанный период
      parameters:
      - description: Начало периода в timestamp
        in: query
        name: start
        required: true
        type: integer
      - description: Конец периода в timestamp
        in: query
        name: end
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DetectionStat'
        "400":
          description: Неверный формат параметров
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Получение статистики обнаружений
      tags:
      - detection
  /v1/healthcheck:
    get:
      description: Проверка, что сервер работает
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
      summary: Проверка работоспособности сервера
      tags:
      - utils
  /v1/sessions:
    get:
      consumes:
      - application/json
      description: Метод возвращает список сессий с поддержкой пагинации и сортировки
      parameters:
      - description: Начальный timestamp диапазона
        in: query
        name: start
        required: true
        type: integer
      - description: Конечный timestamp диапазона
        in: query
        name: end
        required: true
        type: integer
      - description: Номер страницы
        in: query
        name: page
        type: integer
      - description: Количество записей на странице
        in: query
        name: limit
        type: integer
      - description: Поле для сортировки
        in: query
        name: order_by
        type: string
      - description: Направление сортировки
        in: query
        name: order_dir
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ
          schema:
            $ref: '#/definitions/dto.SessionListResponse'
        "400":
          description: Неверный формат параметров
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Получение списка сессий в заданном временном диапазоне
      tags:
      - session
swagger: "2.0"
