// Code generated by go-swagger; DO NOT EDIT.

package contexts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"api-gateway/pkg/models"
)

// DeleteV1ContextsContextIDReader is a Reader for the DeleteV1ContextsContextID structure.
type DeleteV1ContextsContextIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteV1ContextsContextIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteV1ContextsContextIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteV1ContextsContextIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteV1ContextsContextIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteV1ContextsContextIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteV1ContextsContextIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteV1ContextsContextIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /v1/contexts/{context_id}] DeleteV1ContextsContextID", response, response.Code())
	}
}

// NewDeleteV1ContextsContextIDOK creates a DeleteV1ContextsContextIDOK with default headers values
func NewDeleteV1ContextsContextIDOK() *DeleteV1ContextsContextIDOK {
	return &DeleteV1ContextsContextIDOK{}
}

/*
DeleteV1ContextsContextIDOK describes a response with status code 200, with default header values.

OK
*/
type DeleteV1ContextsContextIDOK struct {
	Payload *models.DtoSuccessResponse
}

// IsSuccess returns true when this delete v1 contexts context Id o k response has a 2xx status code
func (o *DeleteV1ContextsContextIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete v1 contexts context Id o k response has a 3xx status code
func (o *DeleteV1ContextsContextIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v1 contexts context Id o k response has a 4xx status code
func (o *DeleteV1ContextsContextIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete v1 contexts context Id o k response has a 5xx status code
func (o *DeleteV1ContextsContextIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v1 contexts context Id o k response a status code equal to that given
func (o *DeleteV1ContextsContextIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete v1 contexts context Id o k response
func (o *DeleteV1ContextsContextIDOK) Code() int {
	return 200
}

func (o *DeleteV1ContextsContextIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/contexts/{context_id}][%d] deleteV1ContextsContextIdOK %s", 200, payload)
}

func (o *DeleteV1ContextsContextIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/contexts/{context_id}][%d] deleteV1ContextsContextIdOK %s", 200, payload)
}

func (o *DeleteV1ContextsContextIDOK) GetPayload() *models.DtoSuccessResponse {
	return o.Payload
}

func (o *DeleteV1ContextsContextIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoSuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteV1ContextsContextIDBadRequest creates a DeleteV1ContextsContextIDBadRequest with default headers values
func NewDeleteV1ContextsContextIDBadRequest() *DeleteV1ContextsContextIDBadRequest {
	return &DeleteV1ContextsContextIDBadRequest{}
}

/*
DeleteV1ContextsContextIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteV1ContextsContextIDBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this delete v1 contexts context Id bad request response has a 2xx status code
func (o *DeleteV1ContextsContextIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete v1 contexts context Id bad request response has a 3xx status code
func (o *DeleteV1ContextsContextIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v1 contexts context Id bad request response has a 4xx status code
func (o *DeleteV1ContextsContextIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete v1 contexts context Id bad request response has a 5xx status code
func (o *DeleteV1ContextsContextIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v1 contexts context Id bad request response a status code equal to that given
func (o *DeleteV1ContextsContextIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete v1 contexts context Id bad request response
func (o *DeleteV1ContextsContextIDBadRequest) Code() int {
	return 400
}

func (o *DeleteV1ContextsContextIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/contexts/{context_id}][%d] deleteV1ContextsContextIdBadRequest %s", 400, payload)
}

func (o *DeleteV1ContextsContextIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/contexts/{context_id}][%d] deleteV1ContextsContextIdBadRequest %s", 400, payload)
}

func (o *DeleteV1ContextsContextIDBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *DeleteV1ContextsContextIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteV1ContextsContextIDUnauthorized creates a DeleteV1ContextsContextIDUnauthorized with default headers values
func NewDeleteV1ContextsContextIDUnauthorized() *DeleteV1ContextsContextIDUnauthorized {
	return &DeleteV1ContextsContextIDUnauthorized{}
}

/*
DeleteV1ContextsContextIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteV1ContextsContextIDUnauthorized struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this delete v1 contexts context Id unauthorized response has a 2xx status code
func (o *DeleteV1ContextsContextIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete v1 contexts context Id unauthorized response has a 3xx status code
func (o *DeleteV1ContextsContextIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v1 contexts context Id unauthorized response has a 4xx status code
func (o *DeleteV1ContextsContextIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete v1 contexts context Id unauthorized response has a 5xx status code
func (o *DeleteV1ContextsContextIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v1 contexts context Id unauthorized response a status code equal to that given
func (o *DeleteV1ContextsContextIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete v1 contexts context Id unauthorized response
func (o *DeleteV1ContextsContextIDUnauthorized) Code() int {
	return 401
}

func (o *DeleteV1ContextsContextIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/contexts/{context_id}][%d] deleteV1ContextsContextIdUnauthorized %s", 401, payload)
}

func (o *DeleteV1ContextsContextIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/contexts/{context_id}][%d] deleteV1ContextsContextIdUnauthorized %s", 401, payload)
}

func (o *DeleteV1ContextsContextIDUnauthorized) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *DeleteV1ContextsContextIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteV1ContextsContextIDForbidden creates a DeleteV1ContextsContextIDForbidden with default headers values
func NewDeleteV1ContextsContextIDForbidden() *DeleteV1ContextsContextIDForbidden {
	return &DeleteV1ContextsContextIDForbidden{}
}

/*
DeleteV1ContextsContextIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteV1ContextsContextIDForbidden struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this delete v1 contexts context Id forbidden response has a 2xx status code
func (o *DeleteV1ContextsContextIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete v1 contexts context Id forbidden response has a 3xx status code
func (o *DeleteV1ContextsContextIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v1 contexts context Id forbidden response has a 4xx status code
func (o *DeleteV1ContextsContextIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete v1 contexts context Id forbidden response has a 5xx status code
func (o *DeleteV1ContextsContextIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v1 contexts context Id forbidden response a status code equal to that given
func (o *DeleteV1ContextsContextIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete v1 contexts context Id forbidden response
func (o *DeleteV1ContextsContextIDForbidden) Code() int {
	return 403
}

func (o *DeleteV1ContextsContextIDForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/contexts/{context_id}][%d] deleteV1ContextsContextIdForbidden %s", 403, payload)
}

func (o *DeleteV1ContextsContextIDForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/contexts/{context_id}][%d] deleteV1ContextsContextIdForbidden %s", 403, payload)
}

func (o *DeleteV1ContextsContextIDForbidden) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *DeleteV1ContextsContextIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteV1ContextsContextIDNotFound creates a DeleteV1ContextsContextIDNotFound with default headers values
func NewDeleteV1ContextsContextIDNotFound() *DeleteV1ContextsContextIDNotFound {
	return &DeleteV1ContextsContextIDNotFound{}
}

/*
DeleteV1ContextsContextIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteV1ContextsContextIDNotFound struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this delete v1 contexts context Id not found response has a 2xx status code
func (o *DeleteV1ContextsContextIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete v1 contexts context Id not found response has a 3xx status code
func (o *DeleteV1ContextsContextIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v1 contexts context Id not found response has a 4xx status code
func (o *DeleteV1ContextsContextIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete v1 contexts context Id not found response has a 5xx status code
func (o *DeleteV1ContextsContextIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v1 contexts context Id not found response a status code equal to that given
func (o *DeleteV1ContextsContextIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete v1 contexts context Id not found response
func (o *DeleteV1ContextsContextIDNotFound) Code() int {
	return 404
}

func (o *DeleteV1ContextsContextIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/contexts/{context_id}][%d] deleteV1ContextsContextIdNotFound %s", 404, payload)
}

func (o *DeleteV1ContextsContextIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/contexts/{context_id}][%d] deleteV1ContextsContextIdNotFound %s", 404, payload)
}

func (o *DeleteV1ContextsContextIDNotFound) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *DeleteV1ContextsContextIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteV1ContextsContextIDInternalServerError creates a DeleteV1ContextsContextIDInternalServerError with default headers values
func NewDeleteV1ContextsContextIDInternalServerError() *DeleteV1ContextsContextIDInternalServerError {
	return &DeleteV1ContextsContextIDInternalServerError{}
}

/*
DeleteV1ContextsContextIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteV1ContextsContextIDInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this delete v1 contexts context Id internal server error response has a 2xx status code
func (o *DeleteV1ContextsContextIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete v1 contexts context Id internal server error response has a 3xx status code
func (o *DeleteV1ContextsContextIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v1 contexts context Id internal server error response has a 4xx status code
func (o *DeleteV1ContextsContextIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete v1 contexts context Id internal server error response has a 5xx status code
func (o *DeleteV1ContextsContextIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete v1 contexts context Id internal server error response a status code equal to that given
func (o *DeleteV1ContextsContextIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete v1 contexts context Id internal server error response
func (o *DeleteV1ContextsContextIDInternalServerError) Code() int {
	return 500
}

func (o *DeleteV1ContextsContextIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/contexts/{context_id}][%d] deleteV1ContextsContextIdInternalServerError %s", 500, payload)
}

func (o *DeleteV1ContextsContextIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/contexts/{context_id}][%d] deleteV1ContextsContextIdInternalServerError %s", 500, payload)
}

func (o *DeleteV1ContextsContextIDInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *DeleteV1ContextsContextIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
