// Code generated by go-swagger; DO NOT EDIT.

package contexts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1ContextsFreePortsParams creates a new GetV1ContextsFreePortsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1ContextsFreePortsParams() *GetV1ContextsFreePortsParams {
	return &GetV1ContextsFreePortsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1ContextsFreePortsParamsWithTimeout creates a new GetV1ContextsFreePortsParams object
// with the ability to set a timeout on a request.
func NewGetV1ContextsFreePortsParamsWithTimeout(timeout time.Duration) *GetV1ContextsFreePortsParams {
	return &GetV1ContextsFreePortsParams{
		timeout: timeout,
	}
}

// NewGetV1ContextsFreePortsParamsWithContext creates a new GetV1ContextsFreePortsParams object
// with the ability to set a context for a request.
func NewGetV1ContextsFreePortsParamsWithContext(ctx context.Context) *GetV1ContextsFreePortsParams {
	return &GetV1ContextsFreePortsParams{
		Context: ctx,
	}
}

// NewGetV1ContextsFreePortsParamsWithHTTPClient creates a new GetV1ContextsFreePortsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1ContextsFreePortsParamsWithHTTPClient(client *http.Client) *GetV1ContextsFreePortsParams {
	return &GetV1ContextsFreePortsParams{
		HTTPClient: client,
	}
}

/*
GetV1ContextsFreePortsParams contains all the parameters to send to the API endpoint

	for the get v1 contexts free ports operation.

	Typically these are written to a http.Request.
*/
type GetV1ContextsFreePortsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 contexts free ports params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1ContextsFreePortsParams) WithDefaults() *GetV1ContextsFreePortsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 contexts free ports params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1ContextsFreePortsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 contexts free ports params
func (o *GetV1ContextsFreePortsParams) WithTimeout(timeout time.Duration) *GetV1ContextsFreePortsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 contexts free ports params
func (o *GetV1ContextsFreePortsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 contexts free ports params
func (o *GetV1ContextsFreePortsParams) WithContext(ctx context.Context) *GetV1ContextsFreePortsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 contexts free ports params
func (o *GetV1ContextsFreePortsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 contexts free ports params
func (o *GetV1ContextsFreePortsParams) WithHTTPClient(client *http.Client) *GetV1ContextsFreePortsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 contexts free ports params
func (o *GetV1ContextsFreePortsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1ContextsFreePortsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
