// Code generated by go-swagger; DO NOT EDIT.

package contexts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"api-gateway/pkg/models"
)

// GetV1ContextsReader is a Reader for the GetV1Contexts structure.
type GetV1ContextsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1ContextsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1ContextsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetV1ContextsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetV1ContextsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetV1ContextsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetV1ContextsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/contexts] GetV1Contexts", response, response.Code())
	}
}

// NewGetV1ContextsOK creates a GetV1ContextsOK with default headers values
func NewGetV1ContextsOK() *GetV1ContextsOK {
	return &GetV1ContextsOK{}
}

/*
GetV1ContextsOK describes a response with status code 200, with default header values.

OK
*/
type GetV1ContextsOK struct {
	Payload *models.DtoContextListResponse
}

// IsSuccess returns true when this get v1 contexts o k response has a 2xx status code
func (o *GetV1ContextsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 contexts o k response has a 3xx status code
func (o *GetV1ContextsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 contexts o k response has a 4xx status code
func (o *GetV1ContextsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 contexts o k response has a 5xx status code
func (o *GetV1ContextsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 contexts o k response a status code equal to that given
func (o *GetV1ContextsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 contexts o k response
func (o *GetV1ContextsOK) Code() int {
	return 200
}

func (o *GetV1ContextsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/contexts][%d] getV1ContextsOK %s", 200, payload)
}

func (o *GetV1ContextsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/contexts][%d] getV1ContextsOK %s", 200, payload)
}

func (o *GetV1ContextsOK) GetPayload() *models.DtoContextListResponse {
	return o.Payload
}

func (o *GetV1ContextsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoContextListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1ContextsBadRequest creates a GetV1ContextsBadRequest with default headers values
func NewGetV1ContextsBadRequest() *GetV1ContextsBadRequest {
	return &GetV1ContextsBadRequest{}
}

/*
GetV1ContextsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetV1ContextsBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 contexts bad request response has a 2xx status code
func (o *GetV1ContextsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 contexts bad request response has a 3xx status code
func (o *GetV1ContextsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 contexts bad request response has a 4xx status code
func (o *GetV1ContextsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 contexts bad request response has a 5xx status code
func (o *GetV1ContextsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 contexts bad request response a status code equal to that given
func (o *GetV1ContextsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get v1 contexts bad request response
func (o *GetV1ContextsBadRequest) Code() int {
	return 400
}

func (o *GetV1ContextsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/contexts][%d] getV1ContextsBadRequest %s", 400, payload)
}

func (o *GetV1ContextsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/contexts][%d] getV1ContextsBadRequest %s", 400, payload)
}

func (o *GetV1ContextsBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1ContextsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1ContextsUnauthorized creates a GetV1ContextsUnauthorized with default headers values
func NewGetV1ContextsUnauthorized() *GetV1ContextsUnauthorized {
	return &GetV1ContextsUnauthorized{}
}

/*
GetV1ContextsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetV1ContextsUnauthorized struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 contexts unauthorized response has a 2xx status code
func (o *GetV1ContextsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 contexts unauthorized response has a 3xx status code
func (o *GetV1ContextsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 contexts unauthorized response has a 4xx status code
func (o *GetV1ContextsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 contexts unauthorized response has a 5xx status code
func (o *GetV1ContextsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 contexts unauthorized response a status code equal to that given
func (o *GetV1ContextsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get v1 contexts unauthorized response
func (o *GetV1ContextsUnauthorized) Code() int {
	return 401
}

func (o *GetV1ContextsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/contexts][%d] getV1ContextsUnauthorized %s", 401, payload)
}

func (o *GetV1ContextsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/contexts][%d] getV1ContextsUnauthorized %s", 401, payload)
}

func (o *GetV1ContextsUnauthorized) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1ContextsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1ContextsForbidden creates a GetV1ContextsForbidden with default headers values
func NewGetV1ContextsForbidden() *GetV1ContextsForbidden {
	return &GetV1ContextsForbidden{}
}

/*
GetV1ContextsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetV1ContextsForbidden struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 contexts forbidden response has a 2xx status code
func (o *GetV1ContextsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 contexts forbidden response has a 3xx status code
func (o *GetV1ContextsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 contexts forbidden response has a 4xx status code
func (o *GetV1ContextsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 contexts forbidden response has a 5xx status code
func (o *GetV1ContextsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 contexts forbidden response a status code equal to that given
func (o *GetV1ContextsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get v1 contexts forbidden response
func (o *GetV1ContextsForbidden) Code() int {
	return 403
}

func (o *GetV1ContextsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/contexts][%d] getV1ContextsForbidden %s", 403, payload)
}

func (o *GetV1ContextsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/contexts][%d] getV1ContextsForbidden %s", 403, payload)
}

func (o *GetV1ContextsForbidden) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1ContextsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1ContextsInternalServerError creates a GetV1ContextsInternalServerError with default headers values
func NewGetV1ContextsInternalServerError() *GetV1ContextsInternalServerError {
	return &GetV1ContextsInternalServerError{}
}

/*
GetV1ContextsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetV1ContextsInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get v1 contexts internal server error response has a 2xx status code
func (o *GetV1ContextsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 contexts internal server error response has a 3xx status code
func (o *GetV1ContextsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 contexts internal server error response has a 4xx status code
func (o *GetV1ContextsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 contexts internal server error response has a 5xx status code
func (o *GetV1ContextsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get v1 contexts internal server error response a status code equal to that given
func (o *GetV1ContextsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get v1 contexts internal server error response
func (o *GetV1ContextsInternalServerError) Code() int {
	return 500
}

func (o *GetV1ContextsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/contexts][%d] getV1ContextsInternalServerError %s", 500, payload)
}

func (o *GetV1ContextsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/contexts][%d] getV1ContextsInternalServerError %s", 500, payload)
}

func (o *GetV1ContextsInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetV1ContextsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
