// Code generated by go-swagger; DO NOT EDIT.

package contexts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1ContextsContextIDParams creates a new GetV1ContextsContextIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1ContextsContextIDParams() *GetV1ContextsContextIDParams {
	return &GetV1ContextsContextIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1ContextsContextIDParamsWithTimeout creates a new GetV1ContextsContextIDParams object
// with the ability to set a timeout on a request.
func NewGetV1ContextsContextIDParamsWithTimeout(timeout time.Duration) *GetV1ContextsContextIDParams {
	return &GetV1ContextsContextIDParams{
		timeout: timeout,
	}
}

// NewGetV1ContextsContextIDParamsWithContext creates a new GetV1ContextsContextIDParams object
// with the ability to set a context for a request.
func NewGetV1ContextsContextIDParamsWithContext(ctx context.Context) *GetV1ContextsContextIDParams {
	return &GetV1ContextsContextIDParams{
		Context: ctx,
	}
}

// NewGetV1ContextsContextIDParamsWithHTTPClient creates a new GetV1ContextsContextIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1ContextsContextIDParamsWithHTTPClient(client *http.Client) *GetV1ContextsContextIDParams {
	return &GetV1ContextsContextIDParams{
		HTTPClient: client,
	}
}

/*
GetV1ContextsContextIDParams contains all the parameters to send to the API endpoint

	for the get v1 contexts context ID operation.

	Typically these are written to a http.Request.
*/
type GetV1ContextsContextIDParams struct {

	/* ContextID.

	   ID контекста
	*/
	ContextID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 contexts context ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1ContextsContextIDParams) WithDefaults() *GetV1ContextsContextIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 contexts context ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1ContextsContextIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 contexts context ID params
func (o *GetV1ContextsContextIDParams) WithTimeout(timeout time.Duration) *GetV1ContextsContextIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 contexts context ID params
func (o *GetV1ContextsContextIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 contexts context ID params
func (o *GetV1ContextsContextIDParams) WithContext(ctx context.Context) *GetV1ContextsContextIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 contexts context ID params
func (o *GetV1ContextsContextIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 contexts context ID params
func (o *GetV1ContextsContextIDParams) WithHTTPClient(client *http.Client) *GetV1ContextsContextIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 contexts context ID params
func (o *GetV1ContextsContextIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContextID adds the contextID to the get v1 contexts context ID params
func (o *GetV1ContextsContextIDParams) WithContextID(contextID string) *GetV1ContextsContextIDParams {
	o.SetContextID(contextID)
	return o
}

// SetContextID adds the contextId to the get v1 contexts context ID params
func (o *GetV1ContextsContextIDParams) SetContextID(contextID string) {
	o.ContextID = contextID
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1ContextsContextIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param context_id
	if err := r.SetPathParam("context_id", o.ContextID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
