// Code generated by go-swagger; DO NOT EDIT.

package contexts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"api-gateway/pkg/models"
)

// PostV1ContextsReader is a Reader for the PostV1Contexts structure.
type PostV1ContextsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1ContextsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostV1ContextsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostV1ContextsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostV1ContextsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostV1ContextsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostV1ContextsConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostV1ContextsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/contexts] PostV1Contexts", response, response.Code())
	}
}

// NewPostV1ContextsOK creates a PostV1ContextsOK with default headers values
func NewPostV1ContextsOK() *PostV1ContextsOK {
	return &PostV1ContextsOK{}
}

/*
PostV1ContextsOK describes a response with status code 200, with default header values.

OK
*/
type PostV1ContextsOK struct {
	Payload *models.ModelsContext
}

// IsSuccess returns true when this post v1 contexts o k response has a 2xx status code
func (o *PostV1ContextsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post v1 contexts o k response has a 3xx status code
func (o *PostV1ContextsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 contexts o k response has a 4xx status code
func (o *PostV1ContextsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1 contexts o k response has a 5xx status code
func (o *PostV1ContextsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 contexts o k response a status code equal to that given
func (o *PostV1ContextsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post v1 contexts o k response
func (o *PostV1ContextsOK) Code() int {
	return 200
}

func (o *PostV1ContextsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/contexts][%d] postV1ContextsOK %s", 200, payload)
}

func (o *PostV1ContextsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/contexts][%d] postV1ContextsOK %s", 200, payload)
}

func (o *PostV1ContextsOK) GetPayload() *models.ModelsContext {
	return o.Payload
}

func (o *PostV1ContextsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsContext)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostV1ContextsBadRequest creates a PostV1ContextsBadRequest with default headers values
func NewPostV1ContextsBadRequest() *PostV1ContextsBadRequest {
	return &PostV1ContextsBadRequest{}
}

/*
PostV1ContextsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostV1ContextsBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post v1 contexts bad request response has a 2xx status code
func (o *PostV1ContextsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post v1 contexts bad request response has a 3xx status code
func (o *PostV1ContextsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 contexts bad request response has a 4xx status code
func (o *PostV1ContextsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post v1 contexts bad request response has a 5xx status code
func (o *PostV1ContextsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 contexts bad request response a status code equal to that given
func (o *PostV1ContextsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post v1 contexts bad request response
func (o *PostV1ContextsBadRequest) Code() int {
	return 400
}

func (o *PostV1ContextsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/contexts][%d] postV1ContextsBadRequest %s", 400, payload)
}

func (o *PostV1ContextsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/contexts][%d] postV1ContextsBadRequest %s", 400, payload)
}

func (o *PostV1ContextsBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostV1ContextsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostV1ContextsUnauthorized creates a PostV1ContextsUnauthorized with default headers values
func NewPostV1ContextsUnauthorized() *PostV1ContextsUnauthorized {
	return &PostV1ContextsUnauthorized{}
}

/*
PostV1ContextsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostV1ContextsUnauthorized struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post v1 contexts unauthorized response has a 2xx status code
func (o *PostV1ContextsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post v1 contexts unauthorized response has a 3xx status code
func (o *PostV1ContextsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 contexts unauthorized response has a 4xx status code
func (o *PostV1ContextsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post v1 contexts unauthorized response has a 5xx status code
func (o *PostV1ContextsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 contexts unauthorized response a status code equal to that given
func (o *PostV1ContextsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post v1 contexts unauthorized response
func (o *PostV1ContextsUnauthorized) Code() int {
	return 401
}

func (o *PostV1ContextsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/contexts][%d] postV1ContextsUnauthorized %s", 401, payload)
}

func (o *PostV1ContextsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/contexts][%d] postV1ContextsUnauthorized %s", 401, payload)
}

func (o *PostV1ContextsUnauthorized) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostV1ContextsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostV1ContextsForbidden creates a PostV1ContextsForbidden with default headers values
func NewPostV1ContextsForbidden() *PostV1ContextsForbidden {
	return &PostV1ContextsForbidden{}
}

/*
PostV1ContextsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PostV1ContextsForbidden struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post v1 contexts forbidden response has a 2xx status code
func (o *PostV1ContextsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post v1 contexts forbidden response has a 3xx status code
func (o *PostV1ContextsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 contexts forbidden response has a 4xx status code
func (o *PostV1ContextsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post v1 contexts forbidden response has a 5xx status code
func (o *PostV1ContextsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 contexts forbidden response a status code equal to that given
func (o *PostV1ContextsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post v1 contexts forbidden response
func (o *PostV1ContextsForbidden) Code() int {
	return 403
}

func (o *PostV1ContextsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/contexts][%d] postV1ContextsForbidden %s", 403, payload)
}

func (o *PostV1ContextsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/contexts][%d] postV1ContextsForbidden %s", 403, payload)
}

func (o *PostV1ContextsForbidden) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostV1ContextsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostV1ContextsConflict creates a PostV1ContextsConflict with default headers values
func NewPostV1ContextsConflict() *PostV1ContextsConflict {
	return &PostV1ContextsConflict{}
}

/*
PostV1ContextsConflict describes a response with status code 409, with default header values.

Conflict
*/
type PostV1ContextsConflict struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post v1 contexts conflict response has a 2xx status code
func (o *PostV1ContextsConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post v1 contexts conflict response has a 3xx status code
func (o *PostV1ContextsConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 contexts conflict response has a 4xx status code
func (o *PostV1ContextsConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this post v1 contexts conflict response has a 5xx status code
func (o *PostV1ContextsConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 contexts conflict response a status code equal to that given
func (o *PostV1ContextsConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the post v1 contexts conflict response
func (o *PostV1ContextsConflict) Code() int {
	return 409
}

func (o *PostV1ContextsConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/contexts][%d] postV1ContextsConflict %s", 409, payload)
}

func (o *PostV1ContextsConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/contexts][%d] postV1ContextsConflict %s", 409, payload)
}

func (o *PostV1ContextsConflict) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostV1ContextsConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostV1ContextsInternalServerError creates a PostV1ContextsInternalServerError with default headers values
func NewPostV1ContextsInternalServerError() *PostV1ContextsInternalServerError {
	return &PostV1ContextsInternalServerError{}
}

/*
PostV1ContextsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostV1ContextsInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post v1 contexts internal server error response has a 2xx status code
func (o *PostV1ContextsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post v1 contexts internal server error response has a 3xx status code
func (o *PostV1ContextsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 contexts internal server error response has a 4xx status code
func (o *PostV1ContextsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1 contexts internal server error response has a 5xx status code
func (o *PostV1ContextsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post v1 contexts internal server error response a status code equal to that given
func (o *PostV1ContextsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post v1 contexts internal server error response
func (o *PostV1ContextsInternalServerError) Code() int {
	return 500
}

func (o *PostV1ContextsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/contexts][%d] postV1ContextsInternalServerError %s", 500, payload)
}

func (o *PostV1ContextsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/contexts][%d] postV1ContextsInternalServerError %s", 500, payload)
}

func (o *PostV1ContextsInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostV1ContextsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
