// Code generated by go-swagger; DO NOT EDIT.

package contexts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"api-gateway/pkg/models"
)

// PutV1ContextsContextIDReader is a Reader for the PutV1ContextsContextID structure.
type PutV1ContextsContextIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutV1ContextsContextIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutV1ContextsContextIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutV1ContextsContextIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPutV1ContextsContextIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPutV1ContextsContextIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutV1ContextsContextIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutV1ContextsContextIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /v1/contexts/{context_id}] PutV1ContextsContextID", response, response.Code())
	}
}

// NewPutV1ContextsContextIDOK creates a PutV1ContextsContextIDOK with default headers values
func NewPutV1ContextsContextIDOK() *PutV1ContextsContextIDOK {
	return &PutV1ContextsContextIDOK{}
}

/*
PutV1ContextsContextIDOK describes a response with status code 200, with default header values.

OK
*/
type PutV1ContextsContextIDOK struct {
	Payload *models.ModelsContext
}

// IsSuccess returns true when this put v1 contexts context Id o k response has a 2xx status code
func (o *PutV1ContextsContextIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put v1 contexts context Id o k response has a 3xx status code
func (o *PutV1ContextsContextIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put v1 contexts context Id o k response has a 4xx status code
func (o *PutV1ContextsContextIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put v1 contexts context Id o k response has a 5xx status code
func (o *PutV1ContextsContextIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put v1 contexts context Id o k response a status code equal to that given
func (o *PutV1ContextsContextIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put v1 contexts context Id o k response
func (o *PutV1ContextsContextIDOK) Code() int {
	return 200
}

func (o *PutV1ContextsContextIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/contexts/{context_id}][%d] putV1ContextsContextIdOK %s", 200, payload)
}

func (o *PutV1ContextsContextIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/contexts/{context_id}][%d] putV1ContextsContextIdOK %s", 200, payload)
}

func (o *PutV1ContextsContextIDOK) GetPayload() *models.ModelsContext {
	return o.Payload
}

func (o *PutV1ContextsContextIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsContext)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutV1ContextsContextIDBadRequest creates a PutV1ContextsContextIDBadRequest with default headers values
func NewPutV1ContextsContextIDBadRequest() *PutV1ContextsContextIDBadRequest {
	return &PutV1ContextsContextIDBadRequest{}
}

/*
PutV1ContextsContextIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PutV1ContextsContextIDBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this put v1 contexts context Id bad request response has a 2xx status code
func (o *PutV1ContextsContextIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put v1 contexts context Id bad request response has a 3xx status code
func (o *PutV1ContextsContextIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put v1 contexts context Id bad request response has a 4xx status code
func (o *PutV1ContextsContextIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put v1 contexts context Id bad request response has a 5xx status code
func (o *PutV1ContextsContextIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put v1 contexts context Id bad request response a status code equal to that given
func (o *PutV1ContextsContextIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put v1 contexts context Id bad request response
func (o *PutV1ContextsContextIDBadRequest) Code() int {
	return 400
}

func (o *PutV1ContextsContextIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/contexts/{context_id}][%d] putV1ContextsContextIdBadRequest %s", 400, payload)
}

func (o *PutV1ContextsContextIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/contexts/{context_id}][%d] putV1ContextsContextIdBadRequest %s", 400, payload)
}

func (o *PutV1ContextsContextIDBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PutV1ContextsContextIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutV1ContextsContextIDUnauthorized creates a PutV1ContextsContextIDUnauthorized with default headers values
func NewPutV1ContextsContextIDUnauthorized() *PutV1ContextsContextIDUnauthorized {
	return &PutV1ContextsContextIDUnauthorized{}
}

/*
PutV1ContextsContextIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PutV1ContextsContextIDUnauthorized struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this put v1 contexts context Id unauthorized response has a 2xx status code
func (o *PutV1ContextsContextIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put v1 contexts context Id unauthorized response has a 3xx status code
func (o *PutV1ContextsContextIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put v1 contexts context Id unauthorized response has a 4xx status code
func (o *PutV1ContextsContextIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this put v1 contexts context Id unauthorized response has a 5xx status code
func (o *PutV1ContextsContextIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this put v1 contexts context Id unauthorized response a status code equal to that given
func (o *PutV1ContextsContextIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the put v1 contexts context Id unauthorized response
func (o *PutV1ContextsContextIDUnauthorized) Code() int {
	return 401
}

func (o *PutV1ContextsContextIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/contexts/{context_id}][%d] putV1ContextsContextIdUnauthorized %s", 401, payload)
}

func (o *PutV1ContextsContextIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/contexts/{context_id}][%d] putV1ContextsContextIdUnauthorized %s", 401, payload)
}

func (o *PutV1ContextsContextIDUnauthorized) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PutV1ContextsContextIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutV1ContextsContextIDForbidden creates a PutV1ContextsContextIDForbidden with default headers values
func NewPutV1ContextsContextIDForbidden() *PutV1ContextsContextIDForbidden {
	return &PutV1ContextsContextIDForbidden{}
}

/*
PutV1ContextsContextIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PutV1ContextsContextIDForbidden struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this put v1 contexts context Id forbidden response has a 2xx status code
func (o *PutV1ContextsContextIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put v1 contexts context Id forbidden response has a 3xx status code
func (o *PutV1ContextsContextIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put v1 contexts context Id forbidden response has a 4xx status code
func (o *PutV1ContextsContextIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this put v1 contexts context Id forbidden response has a 5xx status code
func (o *PutV1ContextsContextIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this put v1 contexts context Id forbidden response a status code equal to that given
func (o *PutV1ContextsContextIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the put v1 contexts context Id forbidden response
func (o *PutV1ContextsContextIDForbidden) Code() int {
	return 403
}

func (o *PutV1ContextsContextIDForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/contexts/{context_id}][%d] putV1ContextsContextIdForbidden %s", 403, payload)
}

func (o *PutV1ContextsContextIDForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/contexts/{context_id}][%d] putV1ContextsContextIdForbidden %s", 403, payload)
}

func (o *PutV1ContextsContextIDForbidden) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PutV1ContextsContextIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutV1ContextsContextIDNotFound creates a PutV1ContextsContextIDNotFound with default headers values
func NewPutV1ContextsContextIDNotFound() *PutV1ContextsContextIDNotFound {
	return &PutV1ContextsContextIDNotFound{}
}

/*
PutV1ContextsContextIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PutV1ContextsContextIDNotFound struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this put v1 contexts context Id not found response has a 2xx status code
func (o *PutV1ContextsContextIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put v1 contexts context Id not found response has a 3xx status code
func (o *PutV1ContextsContextIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put v1 contexts context Id not found response has a 4xx status code
func (o *PutV1ContextsContextIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this put v1 contexts context Id not found response has a 5xx status code
func (o *PutV1ContextsContextIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this put v1 contexts context Id not found response a status code equal to that given
func (o *PutV1ContextsContextIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the put v1 contexts context Id not found response
func (o *PutV1ContextsContextIDNotFound) Code() int {
	return 404
}

func (o *PutV1ContextsContextIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/contexts/{context_id}][%d] putV1ContextsContextIdNotFound %s", 404, payload)
}

func (o *PutV1ContextsContextIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/contexts/{context_id}][%d] putV1ContextsContextIdNotFound %s", 404, payload)
}

func (o *PutV1ContextsContextIDNotFound) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PutV1ContextsContextIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutV1ContextsContextIDInternalServerError creates a PutV1ContextsContextIDInternalServerError with default headers values
func NewPutV1ContextsContextIDInternalServerError() *PutV1ContextsContextIDInternalServerError {
	return &PutV1ContextsContextIDInternalServerError{}
}

/*
PutV1ContextsContextIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PutV1ContextsContextIDInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this put v1 contexts context Id internal server error response has a 2xx status code
func (o *PutV1ContextsContextIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put v1 contexts context Id internal server error response has a 3xx status code
func (o *PutV1ContextsContextIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put v1 contexts context Id internal server error response has a 4xx status code
func (o *PutV1ContextsContextIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this put v1 contexts context Id internal server error response has a 5xx status code
func (o *PutV1ContextsContextIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this put v1 contexts context Id internal server error response a status code equal to that given
func (o *PutV1ContextsContextIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the put v1 contexts context Id internal server error response
func (o *PutV1ContextsContextIDInternalServerError) Code() int {
	return 500
}

func (o *PutV1ContextsContextIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/contexts/{context_id}][%d] putV1ContextsContextIdInternalServerError %s", 500, payload)
}

func (o *PutV1ContextsContextIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/contexts/{context_id}][%d] putV1ContextsContextIdInternalServerError %s", 500, payload)
}

func (o *PutV1ContextsContextIDInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PutV1ContextsContextIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
