// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetV1SessionsParams creates a new GetV1SessionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1SessionsParams() *GetV1SessionsParams {
	return &GetV1SessionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1SessionsParamsWithTimeout creates a new GetV1SessionsParams object
// with the ability to set a timeout on a request.
func NewGetV1SessionsParamsWithTimeout(timeout time.Duration) *GetV1SessionsParams {
	return &GetV1SessionsParams{
		timeout: timeout,
	}
}

// NewGetV1SessionsParamsWithContext creates a new GetV1SessionsParams object
// with the ability to set a context for a request.
func NewGetV1SessionsParamsWithContext(ctx context.Context) *GetV1SessionsParams {
	return &GetV1SessionsParams{
		Context: ctx,
	}
}

// NewGetV1SessionsParamsWithHTTPClient creates a new GetV1SessionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1SessionsParamsWithHTTPClient(client *http.Client) *GetV1SessionsParams {
	return &GetV1SessionsParams{
		HTTPClient: client,
	}
}

/*
GetV1SessionsParams contains all the parameters to send to the API endpoint

	for the get v1 sessions operation.

	Typically these are written to a http.Request.
*/
type GetV1SessionsParams struct {

	/* End.

	   Конечный timestamp диапазона
	*/
	End int64

	/* Limit.

	   Количество записей на странице
	*/
	Limit *int64

	/* OrderBy.

	   Поле для сортировки
	*/
	OrderBy *string

	/* OrderDir.

	   Направление сортировки
	*/
	OrderDir *string

	/* Page.

	   Номер страницы
	*/
	Page *int64

	/* Start.

	   Начальный timestamp диапазона
	*/
	Start int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 sessions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1SessionsParams) WithDefaults() *GetV1SessionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 sessions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1SessionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 sessions params
func (o *GetV1SessionsParams) WithTimeout(timeout time.Duration) *GetV1SessionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 sessions params
func (o *GetV1SessionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 sessions params
func (o *GetV1SessionsParams) WithContext(ctx context.Context) *GetV1SessionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 sessions params
func (o *GetV1SessionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 sessions params
func (o *GetV1SessionsParams) WithHTTPClient(client *http.Client) *GetV1SessionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 sessions params
func (o *GetV1SessionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnd adds the end to the get v1 sessions params
func (o *GetV1SessionsParams) WithEnd(end int64) *GetV1SessionsParams {
	o.SetEnd(end)
	return o
}

// SetEnd adds the end to the get v1 sessions params
func (o *GetV1SessionsParams) SetEnd(end int64) {
	o.End = end
}

// WithLimit adds the limit to the get v1 sessions params
func (o *GetV1SessionsParams) WithLimit(limit *int64) *GetV1SessionsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get v1 sessions params
func (o *GetV1SessionsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOrderBy adds the orderBy to the get v1 sessions params
func (o *GetV1SessionsParams) WithOrderBy(orderBy *string) *GetV1SessionsParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get v1 sessions params
func (o *GetV1SessionsParams) SetOrderBy(orderBy *string) {
	o.OrderBy = orderBy
}

// WithOrderDir adds the orderDir to the get v1 sessions params
func (o *GetV1SessionsParams) WithOrderDir(orderDir *string) *GetV1SessionsParams {
	o.SetOrderDir(orderDir)
	return o
}

// SetOrderDir adds the orderDir to the get v1 sessions params
func (o *GetV1SessionsParams) SetOrderDir(orderDir *string) {
	o.OrderDir = orderDir
}

// WithPage adds the page to the get v1 sessions params
func (o *GetV1SessionsParams) WithPage(page *int64) *GetV1SessionsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get v1 sessions params
func (o *GetV1SessionsParams) SetPage(page *int64) {
	o.Page = page
}

// WithStart adds the start to the get v1 sessions params
func (o *GetV1SessionsParams) WithStart(start int64) *GetV1SessionsParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the get v1 sessions params
func (o *GetV1SessionsParams) SetStart(start int64) {
	o.Start = start
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1SessionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param end
	qrEnd := o.End
	qEnd := swag.FormatInt64(qrEnd)
	if qEnd != "" {

		if err := r.SetQueryParam("end", qEnd); err != nil {
			return err
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.OrderBy != nil {

		// query param order_by
		var qrOrderBy string

		if o.OrderBy != nil {
			qrOrderBy = *o.OrderBy
		}
		qOrderBy := qrOrderBy
		if qOrderBy != "" {

			if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
				return err
			}
		}
	}

	if o.OrderDir != nil {

		// query param order_dir
		var qrOrderDir string

		if o.OrderDir != nil {
			qrOrderDir = *o.OrderDir
		}
		qOrderDir := qrOrderDir
		if qOrderDir != "" {

			if err := r.SetQueryParam("order_dir", qOrderDir); err != nil {
				return err
			}
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	// query param start
	qrStart := o.Start
	qStart := swag.FormatInt64(qrStart)
	if qStart != "" {

		if err := r.SetQueryParam("start", qStart); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
