// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1UsersCountParams creates a new GetV1UsersCountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1UsersCountParams() *GetV1UsersCountParams {
	return &GetV1UsersCountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1UsersCountParamsWithTimeout creates a new GetV1UsersCountParams object
// with the ability to set a timeout on a request.
func NewGetV1UsersCountParamsWithTimeout(timeout time.Duration) *GetV1UsersCountParams {
	return &GetV1UsersCountParams{
		timeout: timeout,
	}
}

// NewGetV1UsersCountParamsWithContext creates a new GetV1UsersCountParams object
// with the ability to set a context for a request.
func NewGetV1UsersCountParamsWithContext(ctx context.Context) *GetV1UsersCountParams {
	return &GetV1UsersCountParams{
		Context: ctx,
	}
}

// NewGetV1UsersCountParamsWithHTTPClient creates a new GetV1UsersCountParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1UsersCountParamsWithHTTPClient(client *http.Client) *GetV1UsersCountParams {
	return &GetV1UsersCountParams{
		HTTPClient: client,
	}
}

/*
GetV1UsersCountParams contains all the parameters to send to the API endpoint

	for the get v1 users count operation.

	Typically these are written to a http.Request.
*/
type GetV1UsersCountParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 users count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1UsersCountParams) WithDefaults() *GetV1UsersCountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 users count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1UsersCountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 users count params
func (o *GetV1UsersCountParams) WithTimeout(timeout time.Duration) *GetV1UsersCountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 users count params
func (o *GetV1UsersCountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 users count params
func (o *GetV1UsersCountParams) WithContext(ctx context.Context) *GetV1UsersCountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 users count params
func (o *GetV1UsersCountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 users count params
func (o *GetV1UsersCountParams) WithHTTPClient(client *http.Client) *GetV1UsersCountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 users count params
func (o *GetV1UsersCountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1UsersCountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
