// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"tg-etl/pkg/models"
)

// NewPostV1UsersParams creates a new PostV1UsersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1UsersParams() *PostV1UsersParams {
	return &PostV1UsersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1UsersParamsWithTimeout creates a new PostV1UsersParams object
// with the ability to set a timeout on a request.
func NewPostV1UsersParamsWithTimeout(timeout time.Duration) *PostV1UsersParams {
	return &PostV1UsersParams{
		timeout: timeout,
	}
}

// NewPostV1UsersParamsWithContext creates a new PostV1UsersParams object
// with the ability to set a context for a request.
func NewPostV1UsersParamsWithContext(ctx context.Context) *PostV1UsersParams {
	return &PostV1UsersParams{
		Context: ctx,
	}
}

// NewPostV1UsersParamsWithHTTPClient creates a new PostV1UsersParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1UsersParamsWithHTTPClient(client *http.Client) *PostV1UsersParams {
	return &PostV1UsersParams{
		HTTPClient: client,
	}
}

/*
PostV1UsersParams contains all the parameters to send to the API endpoint

	for the post v1 users operation.

	Typically these are written to a http.Request.
*/
type PostV1UsersParams struct {

	/* Input.

	   Данные пользователя
	*/
	Input *models.DtoUserCreateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1 users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1UsersParams) WithDefaults() *PostV1UsersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1 users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1UsersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1 users params
func (o *PostV1UsersParams) WithTimeout(timeout time.Duration) *PostV1UsersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 users params
func (o *PostV1UsersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 users params
func (o *PostV1UsersParams) WithContext(ctx context.Context) *PostV1UsersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 users params
func (o *PostV1UsersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 users params
func (o *PostV1UsersParams) WithHTTPClient(client *http.Client) *PostV1UsersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 users params
func (o *PostV1UsersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInput adds the input to the post v1 users params
func (o *PostV1UsersParams) WithInput(input *models.DtoUserCreateRequest) *PostV1UsersParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the post v1 users params
func (o *PostV1UsersParams) SetInput(input *models.DtoUserCreateRequest) {
	o.Input = input
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1UsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
