// Code generated by go-swagger; DO NOT EDIT.

package detections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDetectionsStatParams creates a new GetDetectionsStatParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDetectionsStatParams() *GetDetectionsStatParams {
	return &GetDetectionsStatParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDetectionsStatParamsWithTimeout creates a new GetDetectionsStatParams object
// with the ability to set a timeout on a request.
func NewGetDetectionsStatParamsWithTimeout(timeout time.Duration) *GetDetectionsStatParams {
	return &GetDetectionsStatParams{
		timeout: timeout,
	}
}

// NewGetDetectionsStatParamsWithContext creates a new GetDetectionsStatParams object
// with the ability to set a context for a request.
func NewGetDetectionsStatParamsWithContext(ctx context.Context) *GetDetectionsStatParams {
	return &GetDetectionsStatParams{
		Context: ctx,
	}
}

// NewGetDetectionsStatParamsWithHTTPClient creates a new GetDetectionsStatParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDetectionsStatParamsWithHTTPClient(client *http.Client) *GetDetectionsStatParams {
	return &GetDetectionsStatParams{
		HTTPClient: client,
	}
}

/*
GetDetectionsStatParams contains all the parameters to send to the API endpoint

	for the get detections stat operation.

	Typically these are written to a http.Request.
*/
type GetDetectionsStatParams struct {

	/* Category.

	   Фильтр по категории
	*/
	Category *string

	/* From.

	   Начало временного диапазона (формат: now-10m, now-1h, 2024-01-01T00:00:00Z)

	   Default: "now-10m"
	*/
	From *string

	/* Hostname.

	   Фильтр по имени хоста
	*/
	Hostname *string

	/* To.

	   Конец временного диапазона (формат: now, 2024-01-01T00:00:00Z)

	   Default: "now"
	*/
	To *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get detections stat params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDetectionsStatParams) WithDefaults() *GetDetectionsStatParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get detections stat params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDetectionsStatParams) SetDefaults() {
	var (
		fromDefault = string("now-10m")

		toDefault = string("now")
	)

	val := GetDetectionsStatParams{
		From: &fromDefault,
		To:   &toDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get detections stat params
func (o *GetDetectionsStatParams) WithTimeout(timeout time.Duration) *GetDetectionsStatParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get detections stat params
func (o *GetDetectionsStatParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get detections stat params
func (o *GetDetectionsStatParams) WithContext(ctx context.Context) *GetDetectionsStatParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get detections stat params
func (o *GetDetectionsStatParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get detections stat params
func (o *GetDetectionsStatParams) WithHTTPClient(client *http.Client) *GetDetectionsStatParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get detections stat params
func (o *GetDetectionsStatParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCategory adds the category to the get detections stat params
func (o *GetDetectionsStatParams) WithCategory(category *string) *GetDetectionsStatParams {
	o.SetCategory(category)
	return o
}

// SetCategory adds the category to the get detections stat params
func (o *GetDetectionsStatParams) SetCategory(category *string) {
	o.Category = category
}

// WithFrom adds the from to the get detections stat params
func (o *GetDetectionsStatParams) WithFrom(from *string) *GetDetectionsStatParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the get detections stat params
func (o *GetDetectionsStatParams) SetFrom(from *string) {
	o.From = from
}

// WithHostname adds the hostname to the get detections stat params
func (o *GetDetectionsStatParams) WithHostname(hostname *string) *GetDetectionsStatParams {
	o.SetHostname(hostname)
	return o
}

// SetHostname adds the hostname to the get detections stat params
func (o *GetDetectionsStatParams) SetHostname(hostname *string) {
	o.Hostname = hostname
}

// WithTo adds the to to the get detections stat params
func (o *GetDetectionsStatParams) WithTo(to *string) *GetDetectionsStatParams {
	o.SetTo(to)
	return o
}

// SetTo adds the to to the get detections stat params
func (o *GetDetectionsStatParams) SetTo(to *string) {
	o.To = to
}

// WriteToRequest writes these params to a swagger request
func (o *GetDetectionsStatParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Category != nil {

		// query param category
		var qrCategory string

		if o.Category != nil {
			qrCategory = *o.Category
		}
		qCategory := qrCategory
		if qCategory != "" {

			if err := r.SetQueryParam("category", qCategory); err != nil {
				return err
			}
		}
	}

	if o.From != nil {

		// query param from
		var qrFrom string

		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := qrFrom
		if qFrom != "" {

			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}
	}

	if o.Hostname != nil {

		// query param hostname
		var qrHostname string

		if o.Hostname != nil {
			qrHostname = *o.Hostname
		}
		qHostname := qrHostname
		if qHostname != "" {

			if err := r.SetQueryParam("hostname", qHostname); err != nil {
				return err
			}
		}
	}

	if o.To != nil {

		// query param to
		var qrTo string

		if o.To != nil {
			qrTo = *o.To
		}
		qTo := qrTo
		if qTo != "" {

			if err := r.SetQueryParam("to", qTo); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
