// Code generated by go-swagger; DO NOT EDIT.

package detections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"api-gateway/pkg/models"
)

// GetAPIV2DetectionsReader is a Reader for the GetAPIV2Detections structure.
type GetAPIV2DetectionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV2DetectionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV2DetectionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV2DetectionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAPIV2DetectionsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV2DetectionsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v2/detections] GetAPIV2Detections", response, response.Code())
	}
}

// NewGetAPIV2DetectionsOK creates a GetAPIV2DetectionsOK with default headers values
func NewGetAPIV2DetectionsOK() *GetAPIV2DetectionsOK {
	return &GetAPIV2DetectionsOK{}
}

/*
GetAPIV2DetectionsOK describes a response with status code 200, with default header values.

Успешный ответ
*/
type GetAPIV2DetectionsOK struct {
	Payload *models.DtoGetDetectionsResponseV2
}

// IsSuccess returns true when this get Api v2 detections o k response has a 2xx status code
func (o *GetAPIV2DetectionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v2 detections o k response has a 3xx status code
func (o *GetAPIV2DetectionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 detections o k response has a 4xx status code
func (o *GetAPIV2DetectionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v2 detections o k response has a 5xx status code
func (o *GetAPIV2DetectionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 detections o k response a status code equal to that given
func (o *GetAPIV2DetectionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v2 detections o k response
func (o *GetAPIV2DetectionsOK) Code() int {
	return 200
}

func (o *GetAPIV2DetectionsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/detections][%d] getApiV2DetectionsOK %s", 200, payload)
}

func (o *GetAPIV2DetectionsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/detections][%d] getApiV2DetectionsOK %s", 200, payload)
}

func (o *GetAPIV2DetectionsOK) GetPayload() *models.DtoGetDetectionsResponseV2 {
	return o.Payload
}

func (o *GetAPIV2DetectionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoGetDetectionsResponseV2)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV2DetectionsBadRequest creates a GetAPIV2DetectionsBadRequest with default headers values
func NewGetAPIV2DetectionsBadRequest() *GetAPIV2DetectionsBadRequest {
	return &GetAPIV2DetectionsBadRequest{}
}

/*
GetAPIV2DetectionsBadRequest describes a response with status code 400, with default header values.

Неверный формат параметров
*/
type GetAPIV2DetectionsBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get Api v2 detections bad request response has a 2xx status code
func (o *GetAPIV2DetectionsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v2 detections bad request response has a 3xx status code
func (o *GetAPIV2DetectionsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 detections bad request response has a 4xx status code
func (o *GetAPIV2DetectionsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v2 detections bad request response has a 5xx status code
func (o *GetAPIV2DetectionsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 detections bad request response a status code equal to that given
func (o *GetAPIV2DetectionsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v2 detections bad request response
func (o *GetAPIV2DetectionsBadRequest) Code() int {
	return 400
}

func (o *GetAPIV2DetectionsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/detections][%d] getApiV2DetectionsBadRequest %s", 400, payload)
}

func (o *GetAPIV2DetectionsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/detections][%d] getApiV2DetectionsBadRequest %s", 400, payload)
}

func (o *GetAPIV2DetectionsBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetAPIV2DetectionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV2DetectionsForbidden creates a GetAPIV2DetectionsForbidden with default headers values
func NewGetAPIV2DetectionsForbidden() *GetAPIV2DetectionsForbidden {
	return &GetAPIV2DetectionsForbidden{}
}

/*
GetAPIV2DetectionsForbidden describes a response with status code 403, with default header values.

Недостаточно прав для доступа к выявлениям
*/
type GetAPIV2DetectionsForbidden struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get Api v2 detections forbidden response has a 2xx status code
func (o *GetAPIV2DetectionsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v2 detections forbidden response has a 3xx status code
func (o *GetAPIV2DetectionsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 detections forbidden response has a 4xx status code
func (o *GetAPIV2DetectionsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v2 detections forbidden response has a 5xx status code
func (o *GetAPIV2DetectionsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 detections forbidden response a status code equal to that given
func (o *GetAPIV2DetectionsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v2 detections forbidden response
func (o *GetAPIV2DetectionsForbidden) Code() int {
	return 403
}

func (o *GetAPIV2DetectionsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/detections][%d] getApiV2DetectionsForbidden %s", 403, payload)
}

func (o *GetAPIV2DetectionsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/detections][%d] getApiV2DetectionsForbidden %s", 403, payload)
}

func (o *GetAPIV2DetectionsForbidden) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetAPIV2DetectionsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV2DetectionsInternalServerError creates a GetAPIV2DetectionsInternalServerError with default headers values
func NewGetAPIV2DetectionsInternalServerError() *GetAPIV2DetectionsInternalServerError {
	return &GetAPIV2DetectionsInternalServerError{}
}

/*
GetAPIV2DetectionsInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера
*/
type GetAPIV2DetectionsInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get Api v2 detections internal server error response has a 2xx status code
func (o *GetAPIV2DetectionsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v2 detections internal server error response has a 3xx status code
func (o *GetAPIV2DetectionsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 detections internal server error response has a 4xx status code
func (o *GetAPIV2DetectionsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v2 detections internal server error response has a 5xx status code
func (o *GetAPIV2DetectionsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v2 detections internal server error response a status code equal to that given
func (o *GetAPIV2DetectionsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v2 detections internal server error response
func (o *GetAPIV2DetectionsInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV2DetectionsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/detections][%d] getApiV2DetectionsInternalServerError %s", 500, payload)
}

func (o *GetAPIV2DetectionsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/detections][%d] getApiV2DetectionsInternalServerError %s", 500, payload)
}

func (o *GetAPIV2DetectionsInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetAPIV2DetectionsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
