// Code generated by go-swagger; DO NOT EDIT.

package detections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"api-gateway/pkg/models"
)

// GetDetectionsReader is a Reader for the GetDetections structure.
type GetDetectionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDetectionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDetectionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetDetectionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetDetectionsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /detections] GetDetections", response, response.Code())
	}
}

// NewGetDetectionsOK creates a GetDetectionsOK with default headers values
func NewGetDetectionsOK() *GetDetectionsOK {
	return &GetDetectionsOK{}
}

/*
GetDetectionsOK describes a response with status code 200, with default header values.

Успешный ответ
*/
type GetDetectionsOK struct {
	Payload *models.DtoListResponse
}

// IsSuccess returns true when this get detections o k response has a 2xx status code
func (o *GetDetectionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get detections o k response has a 3xx status code
func (o *GetDetectionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get detections o k response has a 4xx status code
func (o *GetDetectionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get detections o k response has a 5xx status code
func (o *GetDetectionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get detections o k response a status code equal to that given
func (o *GetDetectionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get detections o k response
func (o *GetDetectionsOK) Code() int {
	return 200
}

func (o *GetDetectionsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /detections][%d] getDetectionsOK %s", 200, payload)
}

func (o *GetDetectionsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /detections][%d] getDetectionsOK %s", 200, payload)
}

func (o *GetDetectionsOK) GetPayload() *models.DtoListResponse {
	return o.Payload
}

func (o *GetDetectionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDetectionsBadRequest creates a GetDetectionsBadRequest with default headers values
func NewGetDetectionsBadRequest() *GetDetectionsBadRequest {
	return &GetDetectionsBadRequest{}
}

/*
GetDetectionsBadRequest describes a response with status code 400, with default header values.

Неверный формат параметров
*/
type GetDetectionsBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this get detections bad request response has a 2xx status code
func (o *GetDetectionsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get detections bad request response has a 3xx status code
func (o *GetDetectionsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get detections bad request response has a 4xx status code
func (o *GetDetectionsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get detections bad request response has a 5xx status code
func (o *GetDetectionsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get detections bad request response a status code equal to that given
func (o *GetDetectionsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get detections bad request response
func (o *GetDetectionsBadRequest) Code() int {
	return 400
}

func (o *GetDetectionsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /detections][%d] getDetectionsBadRequest %s", 400, payload)
}

func (o *GetDetectionsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /detections][%d] getDetectionsBadRequest %s", 400, payload)
}

func (o *GetDetectionsBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *GetDetectionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDetectionsInternalServerError creates a GetDetectionsInternalServerError with default headers values
func NewGetDetectionsInternalServerError() *GetDetectionsInternalServerError {
	return &GetDetectionsInternalServerError{}
}

/*
GetDetectionsInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера
*/
type GetDetectionsInternalServerError struct {
	Payload interface{}
}

// IsSuccess returns true when this get detections internal server error response has a 2xx status code
func (o *GetDetectionsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get detections internal server error response has a 3xx status code
func (o *GetDetectionsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get detections internal server error response has a 4xx status code
func (o *GetDetectionsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get detections internal server error response has a 5xx status code
func (o *GetDetectionsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get detections internal server error response a status code equal to that given
func (o *GetDetectionsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get detections internal server error response
func (o *GetDetectionsInternalServerError) Code() int {
	return 500
}

func (o *GetDetectionsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /detections][%d] getDetectionsInternalServerError %s", 500, payload)
}

func (o *GetDetectionsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /detections][%d] getDetectionsInternalServerError %s", 500, payload)
}

func (o *GetDetectionsInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *GetDetectionsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
