services:
  traffic-classifier:
    image: traffic-classifier:cuda13
    build:
      context: ..
      dockerfile: deploy/Dockerfile

    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - KAFKA_CONSUMER_GROUP_ID=${KAFKA_CONSUMER_GROUP_ID}
      - KAFKA_PRODUCER_GROUP_ID=${KAFKA_PRODUCER_GROUP_ID}
      - KAFKA_TIMEOUT=${KAFKA_TIMEOUT}
      - KAFKA_URL=${KAFKA_URL}
      - PRODUCER_TOPIC=${PRODUCER_TOPIC}
      - CONSUMER_TOPIC=${CONSUMER_TOPIC}
      - CONTENT_ONNX_PATH=${CONTENT_ONNX_PATH}
      - SENTIMENT_ONNX_PATH=${SENTIMENT_ONNX_PATH}
      - TOKENIZER_DIR=${TOKENIZER_DIR}
      - ORT_PROVIDER=${ORT_PROVIDER}
      - MAX_LENGTH=${MAX_LENGTH}
      - TOP_K=${TOP_K}

    container_name: traffic-classifier
    restart: unless-stopped


    volumes:
      - ../models:/models:ro

    # gpus: all

