services:
  app:
    container_name: classificator
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - KAFKA_CONSUMER_GROUP_ID=${KAFKA_CONSUMER_GROUP_ID}
      - KAFKA_PRODUCER_GROUP_ID=${KAFKA_PRODUCER_GROUP_ID}
      - KAFKA_TIMEOUT=${KAFKA_TIMEOUT}
      - KAFKA_URL=${KAFKA_URL}
      - MODEL_NAME=${MODEL_NAME}
      - LLM_URL=${LLM_URL}
      - PRODUCER_TOPIC=${PRODUCER_TOPIC}
      - CONSUMER_TOPIC=${CONSUMER_TOPIC}
