// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsRequestsStat models requests stat
//
// swagger:model models.RequestsStat
type ModelsRequestsStat struct {

	// accepted
	Accepted []*ModelsRequestPoint `json:"accepted"`

	// before blocked
	BeforeBlocked []*ModelsRequestPoint `json:"before_blocked"`

	// blocked
	Blocked []*ModelsRequestPoint `json:"blocked"`

	// delayed
	Delayed []*ModelsRequestPoint `json:"delayed"`
}

// Validate validates this models requests stat
func (m *ModelsRequestsStat) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccepted(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBeforeBlocked(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBlocked(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDelayed(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsRequestsStat) validateAccepted(formats strfmt.Registry) error {
	if swag.IsZero(m.Accepted) { // not required
		return nil
	}

	for i := 0; i < len(m.Accepted); i++ {
		if swag.IsZero(m.Accepted[i]) { // not required
			continue
		}

		if m.Accepted[i] != nil {
			if err := m.Accepted[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("accepted" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("accepted" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ModelsRequestsStat) validateBeforeBlocked(formats strfmt.Registry) error {
	if swag.IsZero(m.BeforeBlocked) { // not required
		return nil
	}

	for i := 0; i < len(m.BeforeBlocked); i++ {
		if swag.IsZero(m.BeforeBlocked[i]) { // not required
			continue
		}

		if m.BeforeBlocked[i] != nil {
			if err := m.BeforeBlocked[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("before_blocked" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("before_blocked" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ModelsRequestsStat) validateBlocked(formats strfmt.Registry) error {
	if swag.IsZero(m.Blocked) { // not required
		return nil
	}

	for i := 0; i < len(m.Blocked); i++ {
		if swag.IsZero(m.Blocked[i]) { // not required
			continue
		}

		if m.Blocked[i] != nil {
			if err := m.Blocked[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("blocked" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("blocked" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ModelsRequestsStat) validateDelayed(formats strfmt.Registry) error {
	if swag.IsZero(m.Delayed) { // not required
		return nil
	}

	for i := 0; i < len(m.Delayed); i++ {
		if swag.IsZero(m.Delayed[i]) { // not required
			continue
		}

		if m.Delayed[i] != nil {
			if err := m.Delayed[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("delayed" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("delayed" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this models requests stat based on the context it is used
func (m *ModelsRequestsStat) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAccepted(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateBeforeBlocked(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateBlocked(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDelayed(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsRequestsStat) contextValidateAccepted(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Accepted); i++ {

		if m.Accepted[i] != nil {

			if swag.IsZero(m.Accepted[i]) { // not required
				return nil
			}

			if err := m.Accepted[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("accepted" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("accepted" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ModelsRequestsStat) contextValidateBeforeBlocked(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.BeforeBlocked); i++ {

		if m.BeforeBlocked[i] != nil {

			if swag.IsZero(m.BeforeBlocked[i]) { // not required
				return nil
			}

			if err := m.BeforeBlocked[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("before_blocked" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("before_blocked" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ModelsRequestsStat) contextValidateBlocked(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Blocked); i++ {

		if m.Blocked[i] != nil {

			if swag.IsZero(m.Blocked[i]) { // not required
				return nil
			}

			if err := m.Blocked[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("blocked" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("blocked" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ModelsRequestsStat) contextValidateDelayed(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Delayed); i++ {

		if m.Delayed[i] != nil {

			if swag.IsZero(m.Delayed[i]) { // not required
				return nil
			}

			if err := m.Delayed[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("delayed" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("delayed" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelsRequestsStat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsRequestsStat) UnmarshalBinary(b []byte) error {
	var res ModelsRequestsStat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
