// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsSession models session
//
// swagger:model models.Session
type ModelsSession struct {

	// category
	Category string `json:"category,omitempty"`

	// date time
	DateTime string `json:"dateTime,omitempty"`

	// ip
	IP string `json:"ip,omitempty"`

	// ngfw
	Ngfw string `json:"ngfw,omitempty"`

	// session type
	SessionType string `json:"sessionType,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// url
	URL string `json:"url,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this models session
func (m *ModelsSession) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models session based on context it is used
func (m *ModelsSession) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsSession) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsSession) UnmarshalBinary(b []byte) error {
	var res ModelsSession
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
