// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"api-gateway/pkg/models"
)

// PutV1RolesContextReader is a Reader for the PutV1RolesContext structure.
type PutV1RolesContextReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutV1RolesContextReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutV1RolesContextOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutV1RolesContextBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPutV1RolesContextUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPutV1RolesContextForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutV1RolesContextInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /v1/roles/context] PutV1RolesContext", response, response.Code())
	}
}

// NewPutV1RolesContextOK creates a PutV1RolesContextOK with default headers values
func NewPutV1RolesContextOK() *PutV1RolesContextOK {
	return &PutV1RolesContextOK{}
}

/*
PutV1RolesContextOK describes a response with status code 200, with default header values.

OK
*/
type PutV1RolesContextOK struct {
	Payload *models.DtoSuccessResponse
}

// IsSuccess returns true when this put v1 roles context o k response has a 2xx status code
func (o *PutV1RolesContextOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put v1 roles context o k response has a 3xx status code
func (o *PutV1RolesContextOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put v1 roles context o k response has a 4xx status code
func (o *PutV1RolesContextOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put v1 roles context o k response has a 5xx status code
func (o *PutV1RolesContextOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put v1 roles context o k response a status code equal to that given
func (o *PutV1RolesContextOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put v1 roles context o k response
func (o *PutV1RolesContextOK) Code() int {
	return 200
}

func (o *PutV1RolesContextOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/roles/context][%d] putV1RolesContextOK %s", 200, payload)
}

func (o *PutV1RolesContextOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/roles/context][%d] putV1RolesContextOK %s", 200, payload)
}

func (o *PutV1RolesContextOK) GetPayload() *models.DtoSuccessResponse {
	return o.Payload
}

func (o *PutV1RolesContextOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoSuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutV1RolesContextBadRequest creates a PutV1RolesContextBadRequest with default headers values
func NewPutV1RolesContextBadRequest() *PutV1RolesContextBadRequest {
	return &PutV1RolesContextBadRequest{}
}

/*
PutV1RolesContextBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PutV1RolesContextBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this put v1 roles context bad request response has a 2xx status code
func (o *PutV1RolesContextBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put v1 roles context bad request response has a 3xx status code
func (o *PutV1RolesContextBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put v1 roles context bad request response has a 4xx status code
func (o *PutV1RolesContextBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put v1 roles context bad request response has a 5xx status code
func (o *PutV1RolesContextBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put v1 roles context bad request response a status code equal to that given
func (o *PutV1RolesContextBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put v1 roles context bad request response
func (o *PutV1RolesContextBadRequest) Code() int {
	return 400
}

func (o *PutV1RolesContextBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/roles/context][%d] putV1RolesContextBadRequest %s", 400, payload)
}

func (o *PutV1RolesContextBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/roles/context][%d] putV1RolesContextBadRequest %s", 400, payload)
}

func (o *PutV1RolesContextBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PutV1RolesContextBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutV1RolesContextUnauthorized creates a PutV1RolesContextUnauthorized with default headers values
func NewPutV1RolesContextUnauthorized() *PutV1RolesContextUnauthorized {
	return &PutV1RolesContextUnauthorized{}
}

/*
PutV1RolesContextUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PutV1RolesContextUnauthorized struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this put v1 roles context unauthorized response has a 2xx status code
func (o *PutV1RolesContextUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put v1 roles context unauthorized response has a 3xx status code
func (o *PutV1RolesContextUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put v1 roles context unauthorized response has a 4xx status code
func (o *PutV1RolesContextUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this put v1 roles context unauthorized response has a 5xx status code
func (o *PutV1RolesContextUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this put v1 roles context unauthorized response a status code equal to that given
func (o *PutV1RolesContextUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the put v1 roles context unauthorized response
func (o *PutV1RolesContextUnauthorized) Code() int {
	return 401
}

func (o *PutV1RolesContextUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/roles/context][%d] putV1RolesContextUnauthorized %s", 401, payload)
}

func (o *PutV1RolesContextUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/roles/context][%d] putV1RolesContextUnauthorized %s", 401, payload)
}

func (o *PutV1RolesContextUnauthorized) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PutV1RolesContextUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutV1RolesContextForbidden creates a PutV1RolesContextForbidden with default headers values
func NewPutV1RolesContextForbidden() *PutV1RolesContextForbidden {
	return &PutV1RolesContextForbidden{}
}

/*
PutV1RolesContextForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PutV1RolesContextForbidden struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this put v1 roles context forbidden response has a 2xx status code
func (o *PutV1RolesContextForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put v1 roles context forbidden response has a 3xx status code
func (o *PutV1RolesContextForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put v1 roles context forbidden response has a 4xx status code
func (o *PutV1RolesContextForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this put v1 roles context forbidden response has a 5xx status code
func (o *PutV1RolesContextForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this put v1 roles context forbidden response a status code equal to that given
func (o *PutV1RolesContextForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the put v1 roles context forbidden response
func (o *PutV1RolesContextForbidden) Code() int {
	return 403
}

func (o *PutV1RolesContextForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/roles/context][%d] putV1RolesContextForbidden %s", 403, payload)
}

func (o *PutV1RolesContextForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/roles/context][%d] putV1RolesContextForbidden %s", 403, payload)
}

func (o *PutV1RolesContextForbidden) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PutV1RolesContextForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutV1RolesContextInternalServerError creates a PutV1RolesContextInternalServerError with default headers values
func NewPutV1RolesContextInternalServerError() *PutV1RolesContextInternalServerError {
	return &PutV1RolesContextInternalServerError{}
}

/*
PutV1RolesContextInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PutV1RolesContextInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this put v1 roles context internal server error response has a 2xx status code
func (o *PutV1RolesContextInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put v1 roles context internal server error response has a 3xx status code
func (o *PutV1RolesContextInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put v1 roles context internal server error response has a 4xx status code
func (o *PutV1RolesContextInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this put v1 roles context internal server error response has a 5xx status code
func (o *PutV1RolesContextInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this put v1 roles context internal server error response a status code equal to that given
func (o *PutV1RolesContextInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the put v1 roles context internal server error response
func (o *PutV1RolesContextInternalServerError) Code() int {
	return 500
}

func (o *PutV1RolesContextInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/roles/context][%d] putV1RolesContextInternalServerError %s", 500, payload)
}

func (o *PutV1RolesContextInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/roles/context][%d] putV1RolesContextInternalServerError %s", 500, payload)
}

func (o *PutV1RolesContextInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PutV1RolesContextInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
