// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoUserUpdateData dto user update data
//
// swagger:model dto.UserUpdateData
type DtoUserUpdateData struct {

	// email
	Email string `json:"email,omitempty"`

	// first name
	FirstName string `json:"first_name,omitempty"`

	// last name
	LastName string `json:"last_name,omitempty"`

	// patronymic
	Patronymic string `json:"patronymic,omitempty"`

	// role
	Role string `json:"role,omitempty"`
}

// Validate validates this dto user update data
func (m *DtoUserUpdateData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto user update data based on context it is used
func (m *DtoUserUpdateData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoUserUpdateData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoUserUpdateData) UnmarshalBinary(b []byte) error {
	var res DtoUserUpdateData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
