// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoSuccessResponse dto success response
//
// swagger:model dto.SuccessResponse
type DtoSuccessResponse struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this dto success response
func (m *DtoSuccessResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto success response based on context it is used
func (m *DtoSuccessResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoSuccessResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoSuccessResponse) UnmarshalBinary(b []byte) error {
	var res DtoSuccessResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
