// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoBusinessLog dto business log
//
// swagger:model dto.BusinessLog
type DtoBusinessLog struct {

	// context
	Context string `json:"context,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// user, context
	Entity string `json:"entity,omitempty"`

	// userID or ContextID
	EntityID string `json:"entity_id,omitempty"`

	// CREATE, UPDATE, DELETE
	EventType string `json:"event_type,omitempty"`

	// new value
	NewValue interface{} `json:"new_value,omitempty"`

	// old value
	OldValue interface{} `json:"old_value,omitempty"`

	// user name
	UserName string `json:"user_name,omitempty"`

	// SA, CA
	UserRole string `json:"user_role,omitempty"`
}

// Validate validates this dto business log
func (m *DtoBusinessLog) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto business log based on context it is used
func (m *DtoBusinessLog) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoBusinessLog) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoBusinessLog) UnmarshalBinary(b []byte) error {
	var res DtoBusinessLog
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
