// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsUser models user
//
// swagger:model models.User
type ModelsUser struct {

	// created at
	// Example: 2023-04-01T12:00:00Z
	CreatedAt string `json:"created_at,omitempty"`

	// email
	// Example: john.doe@example.com
	Email string `json:"email,omitempty"`

	// first name
	// Example: John
	FirstName string `json:"first_name,omitempty"`

	// is need to change password
	// Example: true
	IsNeedToChangePassword bool `json:"is_need_to_change_password,omitempty"`

	// is super admin
	// Example: false
	IsSuperAdmin bool `json:"is_super_admin,omitempty"`

	// last name
	// Example: Doe
	LastName string `json:"last_name,omitempty"`

	// login
	// Example: johndoe
	Login string `json:"login,omitempty"`

	// patronymic
	// Example: Ivanovich
	Patronymic string `json:"patronymic,omitempty"`

	// role
	// Example: SA
	Role string `json:"role,omitempty"`

	// user id
	// Example: a71032a2-87eb-4d4e-a2a0-d86404672799
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this models user
func (m *ModelsUser) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models user based on context it is used
func (m *ModelsUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsUser) UnmarshalBinary(b []byte) error {
	var res ModelsUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
