package usecase

import (
	"context"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// getServiceAuthInfo создает authInfo для сервисных вызовов к Keycloak
func (uc *UseCase) getServiceAuthInfo(ctx context.Context) (runtime.ClientAuthInfoWriterFunc, error) {
	// TODO: Реализовать функционал автоматического получения токена
	serviceToken := "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ4X0tXNFpzdmlId3VEa1dNbnI3RXk2MXQ3Wk8zT2JaWTBSd3U1OHJ3U2NzIn0.eyJleHAiOjE3NjI0NjExMDEsImlhdCI6MTc2MjQ2MDgwMSwianRpIjoiNDIxYWE2N2QtNzg5Ni00N2Q1LThmMzgtODI2MWUwMWM0YjExIiwiaXNzIjoiaHR0cHM6Ly8xOTIuMTY4LjEzMC4xMTI6ODQ0My9yZWFsbXMvZ3JhZmFuYXNzbyIsImF1ZCI6InJlYWxtLW1hbmFnZW1lbnQiLCJzdWIiOiIxMDVmNzE2Ni00OWUxLTQyY2MtOGFhNS1iNTA4Zjc5NDI0YTgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJncmFmYW5hLXNzbyIsInNlc3Npb25fc3RhdGUiOiJlODY2NDU2YS05Mzk0LTQwOWEtYmJjYi01MDVjNWY0MWJkMGMiLCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJ2aWV3LXJlYWxtIiwidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJtYW5hZ2UtaWRlbnRpdHktcHJvdmlkZXJzIiwiaW1wZXJzb25hdGlvbiIsInJlYWxtLWFkbWluIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1ZXJ5LXJlYWxtcyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJncmFmYW5hLXNzbyI6eyJyb2xlcyI6WyJTQSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJzaWQiOiJlODY2NDU2YS05Mzk0LTQwOWEtYmJjYi01MDVjNWY0MWJkMGMiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInJvbGVzIjpbInZpZXctcmVhbG0iLCJ2aWV3LWlkZW50aXR5LXByb3ZpZGVycyIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwicmVhbG0tYWRtaW4iLCJjcmVhdGUtY2xpZW50IiwibWFuYWdlLXVzZXJzIiwicXVlcnktcmVhbG1zIiwidmlldy1hdXRob3JpemF0aW9uIiwicXVlcnktY2xpZW50cyIsInF1ZXJ5LXVzZXJzIiwibWFuYWdlLWV2ZW50cyIsIm1hbmFnZS1yZWFsbSIsInZpZXctZXZlbnRzIiwidmlldy11c2VycyIsInZpZXctY2xpZW50cyIsIm1hbmFnZS1hdXRob3JpemF0aW9uIiwibWFuYWdlLWNsaWVudHMiLCJxdWVyeS1ncm91cHMiLCJTQSJdLCJuYW1lIjoiQWRtaW4gQWRtaW4iLCJncm91cHMiOlsiL2dsb2JhbC1TQSJdLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbiIsImdpdmVuX25hbWUiOiJBZG1pbiIsImZhbWlseV9uYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQHRhcmdvcy5jb20ifQ.Gxta4MB69pnoMhbCtxXJDUgxTOvwMfAZl8eFLEwVvm4dYWjHKPsX1bKzRWHBYM2fwgp5GU250l5V_bh-E3o4G1TDaVTUSy_isiX-EZit4CPRSiUI_in9U7sL69nSl4M9suTkz5HdCN8g5-ebRo4XceCcGfoSZJyMsdLBdyTVvcj4Xlauv2m6xr1IkZBinaay8q1in4xKlPNqErzteeBCHqAtX_YYBBG_-cA9xZu5Sg8G1EQm8QUvXVjY9F6u7tC6JQ33n3NfeX1eQHWaN5phgGehDUVPmQYQ34t4K9m5XNhkZlTuMx-hqjOAi5xqdoUm7WEVhcuQlnLq63DUMiPmdg"

	authInfo := runtime.ClientAuthInfoWriterFunc(func(r runtime.ClientRequest, _ strfmt.Registry) error {
		if err := r.SetHeaderParam("Authorization", "Bearer "+serviceToken); err != nil {
			return err
		}
		// Добавляем request ID если нужно
		if requestID, ok := ctx.Value("request_id").(string); ok {
			if err := r.SetHeaderParam("X-Request-ID", requestID); err != nil {
				return err
			}
		}
		return nil
	})

	return authInfo, nil
}
