// Code generated by go-swagger; DO NOT EDIT.

package analytics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"api-gateway/pkg/analytics/actions"
	"api-gateway/pkg/analytics/common"
	"api-gateway/pkg/analytics/dashboards"
	"api-gateway/pkg/analytics/detections"
	"api-gateway/pkg/analytics/reports"
	"api-gateway/pkg/analytics/sessions"
	"api-gateway/pkg/analytics/utils"
)

// Default analytics HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new analytics HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Analytics {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new analytics HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Analytics {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new analytics client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Analytics {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Analytics)
	cli.Transport = transport
	cli.Actions = actions.New(transport, formats)
	cli.Common = common.New(transport, formats)
	cli.Dashboards = dashboards.New(transport, formats)
	cli.Detections = detections.New(transport, formats)
	cli.Reports = reports.New(transport, formats)
	cli.Sessions = sessions.New(transport, formats)
	cli.Utils = utils.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Analytics is a client for analytics
type Analytics struct {
	Actions actions.ClientService

	Common common.ClientService

	Dashboards dashboards.ClientService

	Detections detections.ClientService

	Reports reports.ClientService

	Sessions sessions.ClientService

	Utils utils.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Analytics) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Actions.SetTransport(transport)
	c.Common.SetTransport(transport)
	c.Dashboards.SetTransport(transport)
	c.Detections.SetTransport(transport)
	c.Reports.SetTransport(transport)
	c.Sessions.SetTransport(transport)
	c.Utils.SetTransport(transport)
}
